### ISSUE TITLE
Filtrar actividades por país

### ISSUE THREAD

**Issue by pilote** [techo/voluntariado-eventual#147]
**Si tu idea o funcionalidad está relacionada a un problema, describilo.**
Una descripción clara y concisa de cual es el problema. Por ejemplo, siempre me frustro cuando [...].

> Al querer utilizar la plataforma para países que no sean argentina se genera un problema ya que la interfaz no permite filtrar las actividades por país.

**Describí la funcionalidad te gustaría tener**
Una descripción clara y concisa de que querés que pase. Utilizá el formato *historia de usuario* para contar tu idea, Por ejemplo: [**como** usuario registrado] [**quiero** loguearme con facebook] [**para** hacer más fácil la inscripción].

> **Cómo** usuario que navega la plataforma, **quiero** filtrar actividades por el país en el que ocurren (o por el país en donde se encuentran los puntos de encuentro) **para** ver solo las actividades del país que me interesa sin necesitar buscarlas manualmente entre actividades de otros países.

**Capturas de pantalla o bocetos**
Agregá cualquier captura de pantalla, boceto, maqueta o información adicional que ayude a aclarar tu pedido.

Algunas maquetas que se hicieron al respecto, aunque creo que son más adecuadas para el idioma que como filtro de país (para analizar con Ale Rao)
![03 1](https://user-images.githubusercontent.com/1020106/45002284-70b55300-afab-11e8-8f87-003ce868fa14.png)
![03-3](https://user-images.githubusercontent.com/1020106/45002285-70b55300-afab-11e8-8dfc-6b3d0d1f24c3.png)
![01-2](https://user-images.githubusercontent.com/1020106/45002286-70b55300-afab-11e8-86e4-8b1f554f8ac1.png)

**Describí alternativas que hayas considerado**
Una descripción clara de las soluciones alternativas que se te hayan ocurrido.

> Sería **interesante** poder darle inteligencia a la plataforma para que filtre las actividades por el país en el que estoy por defecto y además me permita cambiarlo. Podría hacerlo por dns o por ip.

**Información adicional**
Para que esto ocurra es necesario que esté cargada la información socio-política de todos los países donde tenemos operación.

Tareas:
- [x] Cargar info socio-política países.

**Comment by wmarcos** [comment]
La implementación que se eligió por temas de costo-valor es la que genera un subdominio por país y incorpora una página landing para seleccionar el país al que quiero ingresar.

**Comment by MicaelaTangorra** [comment]
TESTING --> OK

**Comment by wmarcos** [comment]
Esto sería re-aplicar los cambios que hizo @gabystallo a la rama nueva.

![image](https://user-images.githubusercontent.com/94343/67691535-84750300-f97d-11e9-81c1-588426770756.png)

Y agregar una variable de configuración para "apagar/prender" este comportamiento, así esperamos el mejor momento para lanzarlo.

Necesita estar acompañado de cambios en el DNS, eso lo deberíamos ver para que lo puedas tener en cuenta.

**Comment by wmarcos** [comment]
Para aclarar, la implementación permite filtrar país según el subdominio al que te conectes:

ar.actividades.techo.org -> filtra actividades en Argentina
py.actividades.techo.org -> filtra actividades en Paraguay
...

actividades.techo.org es un índice de países solamente.

Es una implementación con varios acoples, pero dada la lógica del sistema (una única base multi-país) no hay muchas opciones.

Acoples:
- Necesario tener información de provincias por cada país
- Necesario un dominio https para el login social en cada país (sino las apis fb/ig no funcionan)
- Necesario cargar algunas cosas en varios idiomas en la db (clases, tipos, etc).

**Comment by wmarcos** [comment]
Cambio de estrategia para evitar la complejidad de mantener dominios separados. Se pierde un poquito de usabilidad pero se vuelve mucho más simple mantener a la larga.

Un solo sitio con un selector de país y se guarda la selección en la sesión.

![image](https://user-images.githubusercontent.com/94343/68612885-4fe46980-049c-11ea-948c-3cd2a597468d.png)

**Comment by wmarcos** [comment]
Oficinas Paraguay: 
- Central
- Alto Paraná
- Itapua
- Caaguazu

**Comment by agustempo** [comment]
Sumamos a este ticket que

- el botón "Ayuda" este por fuera de la hamburguesa en version Mobile y que también le aparezca al usuario NO logueado
- Selección de Pais fuera de la hamburguesa version Mobile
