### ISSUE TITLE
Politica de Privacidad 

### ISSUE THREAD

**Issue by lucascarra** [techo/voluntariado-eventual#150]
Aceptar el uso de cookies (opcional, falta la redacción del uso de cookies)
Aceptar las reglas de la carta de voluntariado en cada actividad que se anota (obligatorio, falta actualizar la carta de voluntariado)
Aceptar la política de privacidad (publicada en techo.org) (obligatorio, falta actualizar la política de privacidad)
Aceptar que TECHO utilice mi datos para contactarme por campañas y eventos (email marketing, opcional, sin chequear por defecto).
Aceptar notificaciones operativas de la plataforma al usuario (opcional, chequeado por defecto)
Mecanismo para borrar sus datos del sistema (anonimizar datos personales) 
Agregar un unsubscribe en los mail (equivalente a destildar
En rojo está los que entiende que falta del lado de la consultora que nos asesora, algo de esto ya hablamos también.
 
Estas cosas se traducirían en funcionalidad en la plataforma según estas maquetas gráficas que te envío más abajo en el mail.

 
En el sitio principal

![sitio principal](https://user-images.githubusercontent.com/10621402/45046814-af034e80-b04d-11e8-839c-c3990e4c95f0.png)

En el registro

![emelregistro](https://user-images.githubusercontent.com/10621402/45046943-086b7d80-b04e-11e8-8eb8-9c6c39e30a88.png)

Al inscribirse en una actividad

![inscripcion](https://user-images.githubusercontent.com/10621402/45046971-1de0a780-b04e-11e8-8045-eee0cb93660e.png)

En el perfil del usuario

![perfil](https://user-images.githubusercontent.com/10621402/45047001-3486fe80-b04e-11e8-981c-dc6ed69f70a6.png)

**Comment by MicaelaTangorra** [comment]
Politica de Privacidad: Defectos:
- #180 
- #181 
- #182

**Comment by MicaelaTangorra** [comment]
#180 --> DEMO (http://sandbox.actividades.techo.org/): verificado OK

**Comment by MicaelaTangorra** [comment]
Son 2 defectos, cierro esta tarjeta y lo van a hacer en otra issue: 

#181: FE: Ingresar - Perfil - Acepto de Politica de Privacidad
#182: FE: Ingresar - Quiero ser Voluntario - Acepto la Politica de Privacidad
