### ISSUE TITLE
Vista en Mobile de Lista de actividades y flujo de inscripciones, y backoffice

### ISSUE THREAD

**Issue by lucascarra** [techo/voluntariado-eventual#151]
Cómo el sistema está pensado para facilitar el ingreso de voluntarios, se pidió que se pueda utilizar desde un celular, si bien no hace falta de que sea completamente Mobile. Si es necesario que las vistas para inscribirse a una actividad, como para tomar presentes en el sistema se puedan utilizar más o menos bien desde un celular. Hoy en día hay varios estilos que lo hacen bastante difícil

![image-2018-05-23-18-03-53-325](https://user-images.githubusercontent.com/43036107/45427422-361b7c80-b675-11e8-8bd2-81146abbc96d.png)

![image-2018-05-23-18-03-20-557](https://user-images.githubusercontent.com/43036107/45427423-36b41300-b675-11e8-9b52-449525d52515.png)

- [x] Backend - Scroll horizontal en datatables
- [x] Backend - Botones en los footer de los formularios
- [ ] Testing
- [x] Front end - Modal de desinscripción

**Comment by MicaelaTangorra** [comment]
- Backend - Scroll horizontal en datatables: OK
- Backend - Botones en los footer de los formularios: OK
- Mis Actividades - Una Actividad - Solapa “inscripciones”: NOK --> **BE: Mis Actividades - Una Actividad - solapa "Evaluaciones" se va corriendo cuando aprieto en otras solapas #178**
- Front end - Modal de desinscripción: OK
- Actividad --> botones : OK
- De la vista de usuario : NOK -->  **BE: Usuarios - Ver Listado - Ver/Guardar #179**

**Comment by MicaelaTangorra** [comment]
Son 2 defectos y lo van a desarrollar en otra tarea:

#178: BE: Mis Actividades - Una Actividad - solapa "Evaluaciones" se va corriendo cuando aprieto en otras solapas
#179: BE: Usuarios - Ver Listado - Ver/Guardar
