### ISSUE TITLE
FE: Perfil - Cancelar (bug con campos de contraseña)

### ISSUE THREAD

**Issue by lucascarra** [techo/voluntariado-eventual#152]
FE: Perfil - Cancelar ==> Presiono CANCELAR me aparece un mensaje de una red social pero con esta logueado con una red social (Login Normal)

Los pasos xa reproducir son (hay una imagen):

 ==> estoy con mi usuario (micaela.tangorra@globallogic.com ) sin red
social: lo hice con "Login Normal"

- http://dev.atlas.test/perfil#
- Ingreso: micaela.tangorra@globallogic.com
- Voy a PERFIL (en el botón derecho superior)
- No modifco nada
- Presione CANCELAR
- ... y los 3 campos de CONTRASEÑA desaparecen (Contraseña Actual, Nueva
Contraseña y Confirmar Contraseña) y aparece un mensaje que dice:
"Tu cuenta está vinculada a una red social, para cambiar tu contraseña
debes cerrar la sesión y hacer click en "Olvidé mi contraseña".

**Comment by wmarcos** [comment]
No logro reproducir este ¿alguno se acuerda bien como era o si estaba en JIRA/Backlog? sino lo damos por cerrado @MicaelaTangorra @lucascarra

**Comment by wmarcos** [comment]
¡Buenísimo @MicaelaTangorra! Ahí actualicé la descripción con tu paso a paso

**Comment by MicaelaTangorra** [comment]
Jira: https://velocity.globallogic.com/jira/browse/TEC-404

**Comment by MicaelaTangorra** [comment]
- DEMO (Sandbox) --> Verificado: OK (Login Normal)
- Red Social (Facebook y Google)  en Sandbox no funciona --> lo va a investigar Marcos.
