### ISSUE TITLE
Correciones de Sprint 6

### ISSUE THREAD

**Issue by lucascarra** [techo/voluntariado-eventual#154]
- [ ] Testing

**Comment by MicaelaTangorra** [comment]
- Un issue, el 392 (""Modificar el flujo de inscripción a actividad con pago"): hay un defecto:
==> #183  (JIRA: https://velocity.globallogic.com/jira/browse/TEC-414)

**Comment by MicaelaTangorra** [comment]
Es un defecto el #183 y  lo van a hacer en otro tarea:

#183: FE: Inscribirme a una Actividad - Monto
