### ISSUE TITLE
Vista en Mobile de Back para registro de presentes

### ISSUE THREAD

**Issue by lucascarra** [techo/voluntariado-eventual#157]

**Comment by MicaelaTangorra** [comment]
Test (http://sandbox.actividades.techo.org/) -> MOBILE:
- Celu -> Firefox --> Verificado OK

**Comment by MicaelaTangorra** [comment]
Test (http://sandbox.actividades.techo.org/) -> MOBILE:

Celu -> Chrome --> Verificado OK
