### ISSUE TITLE
Pantalla de Bienvenida al crear usuario no se vé

### ISSUE THREAD

**Issue by lucascarra** [techo/voluntariado-eventual#159]
JIRA: https://velocity.globallogic.com/jira/secure/RapidBoard.jspa?rapidView=2039&projectKey=TEC&view=planning&selectedIssue=TEC-193

Cómo persona que llega a la plataforma, al crear un usuario, completo mis datos 
y al clickear en “Crear cuenta” me muestra por un segundo una pantalla de bienvenida que no se llega a leer 
y me redirige a la home.

Debería dejarme en la pantalla de bienvenida con un link para volver al home.

![image-2018-05-23-17-40-29-184](https://user-images.githubusercontent.com/43036107/45427121-7e866a80-b674-11e8-987e-de4287701e9a.png)

Testear:

- [ ] Registración normal

- [ ] Registración con Google

- [ ] Registración con Facebook

**Comment by aabraham88** [comment]
Corregido en pull request #177

**Comment by MicaelaTangorra** [comment]
Desa (http://dev.atlas.test/):
- en desktop en Chrome: Verificado OK
- en Facebook y Google: cuando lo pasen a DEMO lo pruebo porque en DESA no lo puedo probar.

**Comment by MicaelaTangorra** [comment]
DESA: Verificado: NOK
DEMO (Sandbox): Verificado: NOK

![20180921-modifica texto de bienvenida despues de registrarse desa](https://user-images.githubusercontent.com/43036107/45882598-00694880-bd85-11e8-9899-276e7a266bbc.JPG)
![20180921-modifica texto de bienvenida despues de registrarse demo](https://user-images.githubusercontent.com/43036107/45882599-00694880-bd85-11e8-81a0-c16fed85ac30.JPG)

**Comment by MicaelaTangorra** [comment]
- DEMO (Sandbox): Verificado: OK
Celu: 
- Demo (SandBox) -> Facebook y Google : redigire a Produccion --> Verificado NOK --> (lo va a ver Marcos)

**Comment by wmarcos** [comment]
Probado en producción Navegador y Celu OK
