### ISSUE TITLE
Revisar género para que se más inclusivo

### ISSUE THREAD

**Issue by lucascarra** [techo/voluntariado-eventual#161]
https://uxdesign.cc/designing-forms-for-gender-diversity-and-inclusion-d8194cf1f51

**Comment by agustempo** [comment]
Este issue esta bien bueno, desde el principio en el registro la pregunta ya no es inclusiva y deberia tener opcion "Otrx"
![image](https://user-images.githubusercontent.com/11001346/62161711-30f70880-b2ed-11e9-8a4f-2225349037e9.png)


Asi todo, cuando se cambia el mismo el saludo sigue siendo el mismo

![image](https://user-images.githubusercontent.com/11001346/62161780-508e3100-b2ed-11e9-9bbd-a349c4d575f8.png)


Por el bien de todxs y por la falta de sentido a pedir genero lo dejaria de pedir, y despues las planillas podrian evitar el uso o, de ser imposible usar la x.

Que les parece?

**Comment by agustempo** [comment]
Se cierra y se sigue en #335
