### ISSUE TITLE
Usuario. Historial de inscripciones

### ISSUE THREAD

**Issue by lucascarra** [techo/voluntariado-eventual#162]
Como Administrador quiero poder visualizar y descargar los datos de inscripciones de un usuario desde el panel de administración.

Para eso es necesario:

- Ingresar al panel de administración con privilegios de administrador
- Clickear en el menú "Usuarios" y en "Ver listado"
- Buscar y elegir un usuario
- Seleccionar una pestaña "inscripciones"
- Poder descargar el historial de inscripciones de ese usuario.
- Poder visualizar en pantalla: listado de actividades a las que se inscribió (si tuvo presente?).

**Comment by aabraham88** [comment]
Qué sería clase en este listado?

**Comment by wmarcos** [comment]
Se muestran una tabla (paginada) con las siguientes columnas

Nombre_actividad, Tipo, Fecha_actividad, Rol, Lugar, Oficina, Presente

al clickear en cada línea de actividad te lleva a la vista de esa actividad.

El lugar es el lugar donde se llevó a cabo la actividad, no es un punto de encuentro.

![image](https://user-images.githubusercontent.com/94343/47512990-b7a92180-d853-11e8-9ce0-83a6689d4675.png)

**Comment by aabraham88** [comment]
👍
