### ISSUE TITLE
Usuarios. Evaluaciones

### ISSUE THREAD

**Issue by lucascarra** [techo/voluntariado-eventual#165]
Como *Administrador* (solamente) quiero poder visualizar y descargar los datos de evaluaciones de un usuario desde el panel de administración.

Para eso es necesario:

- Ingresar al panel de administración con privilegios de administrador
- Clickear en el menú "Usuarios" y en "Ver listado"
- Buscar y elegir un usuario
- Seleccionar una pestaña "evaluaciones"
- Poder descargar las evaluaciones que se le hicieron a ese usuario (anónimas) en las actividades donde participó
- Poder visualizar en pantalla: promedio general de puntaje (técnico y social) y un histograma de puntajes.

**Comment by aabraham88** [comment]
Clase sería tipo de actividad? La Fecha de qué sería, de la actividad o de la inscripción? Los graficos totalizan puntajes de todas sus actividades?

**Comment by wmarcos** [comment]
![image](https://user-images.githubusercontent.com/94343/47512029-baa31280-d851-11e8-835f-7b62e4a49c81.png)

El gráfico totaliza los puntajes de todas sus actividades.

**Campos en la descarga**
Nombre_actividad, Tipo, Fecha_actividad, lugar, rol, oficina, presente, puntajeSocial, puntajeTecnico, comentario.

**Comment by aabraham88** [comment]
👍
