### ISSUE TITLE
Se rompen los controles de evaluación.

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#168]
**Describí el error**
Cuando se quiere dejar feedback sobre una actividad los sliders que permiten asignar un puntaje ténico o social aparecen en gris, en la posición 0 pero con el tooltip indicando el valor 5 (imagen 1). Al clickear en cualquier punto del intervalo, aparece el valor 10 en el tooltip y no se mueve de lugar (imagen 2)

![imagen 1](https://user-images.githubusercontent.com/94343/45324154-b205af80-b523-11e8-850f-4092ce652a1f.png)

![imagen 2](https://user-images.githubusercontent.com/94343/45324196-cd70ba80-b523-11e8-816d-e7af6bae2823.png)

**Observación**: al cambiar el tamaño de la pantalla el problema parece solucionarse, y al refrescar la página, vuelve a pasar.

![Apenas carga la pantalla](https://user-images.githubusercontent.com/94343/45324455-8e8f3480-b524-11e8-919c-4b8339de858d.png)

![al hacer un resize](https://user-images.githubusercontent.com/94343/45324475-9fd84100-b524-11e8-9e11-abf2da470823.png)

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a "Mis Actividades", encontrar una actividad pasada que esté en período de evaluación.
2. Clickear en "Ver evaluaciones"
3. Clickear en la caja de evaluación de la actividad o de cualquier compañero
4. Observar como aparece la perilla del slider en 0 con el valor del tooltip en 5.

**Comportamiento esperando**
Una descripción clara y concisa de que esperabas que pase y no pasó.
Se espera que el slider esté activado, con la perilla en 5 y el tooltip en el valor 5. Si clickeo en algún punto del intervalo tiene que cambiar la perilla y el tooltipo acorde.

Si el período de evaluación está cerrado, el slider aparece inactivo, la perilla en el valor grabado con el tooltipo correspondiente.

**Si estás en una computadora (por favor completá la siguiente información):**
 - Chrome Versión 68.0.3440.106 (Build oficial) (64 bits)

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: Huawei GW
 - Sistema operativo: Android
 - Navegador Chrome 68.0.3440.91

**Comment by MicaelaTangorra** [comment]
Jira: https://velocity.globallogic.com/jira/browse/TEC-417

**Comment by MicaelaTangorra** [comment]
DESA (http://dev.atlas.test): Verificado OK
TEST (http://sandbox.actividades.techo.org/)
- Compu: Verificado OK
- Celu : Firefox: Verificado OK
