### ISSUE TITLE
Traducción FRONTEND del sitio con selección de idioma desde NAV

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#169]
**Si tu idea o funcionalidad está relacionada a un problema, describilo.**
Una descripción clara y concisa de cual es el problema. Por ejemplo, siempre me frustro cuando [...].

> Al querer utilizar la plataforma para países que no hablan español se produce un problema ya que los textos en las pantallas de la interfaz están solo en español.

**Describí la funcionalidad te gustaría tener**
Una descripción clara y concisa de que querés que pase. Utilizá el formato *historia de usuario* para contar tu idea, Por ejemplo: [**como** usuario registrado] [**quiero** loguearme con facebook] [**para** hacer más fácil la inscripción].

> Cómo usuario que navega la plataforma, quiero poder visualizar el contenido en el idioma de mi preferencia para poder entender la información e inscribirme con seguridad a las actividades.

**Capturas de pantalla o bocetos**
Agregá cualquier captura de pantalla, boceto, maqueta o información adicional que ayude a aclarar tu pedido.

> Creo que no hace falta.

**Describí alternativas que hayas considerado**
Una descripción clara de las soluciones alternativas que se te hayan ocurrido.

> Sería **importante** poder cambiar el idioma desde la interfaz. Y sería **interesante** poder darle inteligencia a la plataforma para que sepa qué idioma elegir según mi ubicación.

- [ ] Armar los directorios y cargar las primera plantillas de idiomas de Laravel (es_AR, es_PY, pt_BR)
- [X] Generar plantillas de idiomas para Vue
- [X] Seleccionar una vista del front-end y lograr traducirla
- [X] Traducir el resto del front-end
- [X] Traduccion al Ingles
- [ ] Generar ícono de cambio de idioma en el front-end

Debería haber una plantilla por país (y no una por idioma) ya que cada país va a querer "adaptar" su traducción al contexto.

**Comment by wmarcos** [comment]
@lucascarra @aabraham88 @MicaelaTangorra ¿les parece utilizar esta plantilla para cargar las historias/mejoras/nuevas funcionalidades?

**Comment by wmarcos** [comment]
Configurar laravel para soporte de idiomas.

Frontend/Backend
Icono en pantalla para cambiar de idioma
Tags de traducción (identificar que cada texto a traducir de la plataforma sea un tag en un archivo)

El idioma se resuelve por sesión y no por URL/Dominio.

**Comment by agustempo** [comment]
Para chequear, te parece bien este [commit](https://github.com/techo/voluntariado-eventual/commit/4bbd6db8a8e8e71549b319b086e9686f35328e04) para es_AR?

Empecé por el backend de actividades, y para cada objeto voy a crear un php de traduccion. Pero, para el caso de lo que no entra en este conjunto (ej, "elegir manualmente fecha de evaluacion/inscripción"), creo un editorActividad.php para este tipo de traducciones? como la ves?

mientras sigo jugando a ver si puedo levantar desde vue estas traducciones.

**Comment by wmarcos** [comment]
Parece bien, pintan a tags del backend lo único.
Parece más estratégico empezar por el front. Pero como la veas mejor. Finalmente vamos tener que hacer todo.

**Comment by jdcalaz** [comment]
Empecé a testear la versión en inglés.
![image](https://user-images.githubusercontent.com/48033083/69830177-4714c700-1202-11ea-82f6-b1ae08aa4514.png)

**Comment by jdcalaz** [comment]
Al querer registrarme con Facebook:
![Captura de pantalla de 2019-11-28 17-52-11](https://user-images.githubusercontent.com/48033083/69831386-e7b9b580-1207-11ea-985a-5eb10e7555cb.png)

**Comment by jdcalaz** [comment]
**8. (No es de traducción) pero queriendo reestablecer contraseña el botón 'SEND' está encimado con el campo donde se debe escribir el mail**
![image](https://user-images.githubusercontent.com/48033083/69832011-bc849580-120a-11ea-979b-49b7d3f83664.png)

**Comment by jdcalaz** [comment]
**11. En 'Perfil' el botón 'Cancelar' está roto.**
![image](https://user-images.githubusercontent.com/48033083/69832449-2736d080-120d-11ea-872d-49410dba8834.png)

**Comment by wmarcos** [comment]
Antes de seguir probando hacé un pull que cambié varias cosas @jdcalaz

**Comment by jdcalaz** [comment]
¿Empiezo a poner los defectos acá?
1. En la pantalla inicial Aparece en cada parte ''FRONTEND. etc'' 
![image](https://user-images.githubusercontent.com/48033083/70078089-d7775100-15e0-11ea-8143-61423b97d7fe.png)

**Comment by jdcalaz** [comment]
1. Al pre-inscribirme  a una actividad con confirmación manual y con pago  el botón 'volver' está en español
![Captura de pantalla de 2019-12-03 16-07-40](https://user-images.githubusercontent.com/48033083/70081802-f62d1600-15e7-11ea-9b91-bfba1bc44dd8.png)

**Comment by jdcalaz** [comment]
2. Al compartir la actividad 'CERRAR' Y 'COMPARTIR' están en español
![Captura de pantalla de 2019-12-03 16-15-01](https://user-images.githubusercontent.com/48033083/70081934-2b396880-15e8-11ea-9611-fc6cc8c0a7db.png)

**Comment by jdcalaz** [comment]
3. en el Mail de inscripción a una actividad cuando no está definido un lugar está en español
![Captura de pantalla de 2019-12-03 16-19-22](https://user-images.githubusercontent.com/48033083/70082272-c599ac00-15e8-11ea-8417-5b3f8afb0438.png)

**Comment by jdcalaz** [comment]
**4. en el mail de confirmacion manual está en español el asunto del mail y una frase**
'solo falta un paso para confirmar'
![Captura de pantalla de 2019-12-03 16-36-36](https://user-images.githubusercontent.com/48033083/70083430-1dd1ad80-15eb-11ea-9bc2-a51db6ecccc1.png)

![Captura de pantalla de 2019-12-03 16-32-45](https://user-images.githubusercontent.com/48033083/70083464-2c1fc980-15eb-11ea-90f1-534894589d63.png)
 
 **El mail 'Estás confirmado para participar en:...''**
![Captura de pantalla de 2019-12-03 16-37-41](https://user-images.githubusercontent.com/48033083/70083533-52de0000-15eb-11ea-812b-cf024863a5ba.png)

**Comment by jdcalaz** [comment]
5. En el mail que invita a evaluar la actividad 
![Captura de pantalla de 2019-12-03 16-50-12](https://user-images.githubusercontent.com/48033083/70084495-1a3f2600-15ed-11ea-82fe-1a22fadcc0dc.png)

**Comment by jdcalaz** [comment]
6. Esto no se si es cosa del Telescope o si pasaría esto realmente:
Cuando llega el mail de evaluación a una actividad  y hago click se abre la plataforma dentro de la casilla de mensajes para loguearme (en Telescope pasa siempre) pero en español, no en inglés.
![Captura de pantalla de 2019-12-03 17-13-06](https://user-images.githubusercontent.com/48033083/70086023-36909200-15f0-11ea-975f-4cf7f9adeec4.png)

**Comment by jdcalaz** [comment]
Al borrar una actividad el mail que llega es en español
![Captura de pantalla de 2019-12-03 17-45-03](https://user-images.githubusercontent.com/48033083/70088280-b15bac00-15f4-11ea-90c8-f86ee713bcda.png)

**Comment by jdcalaz** [comment]
Tampoco puedo evaluar si voy a ''MY  ACTIVITIES'  ¿eso había quedado así?
![Uploading Captura de pantalla de 2019-12-03 18-05-48.png…]()

**Comment by jdcalaz** [comment]
Inscribiendo a un voluntaio figura dos veces en la lista
Para reproducir el error:
1. Como usuario autenticado tratar de inscribirme a una actividad con pago
2. No concreté la operación porque el local tiene problemas con PayU
3. Inscribir a esa persona desde una cuenta de 'Coordinador'
4. Ver el listado de inscriptos que está la misma persona dos veces
![Captura de pantalla de 2019-12-03 19-09-53](https://user-images.githubusercontent.com/48033083/70094131-a0189c80-1600-11ea-8ae8-3ef51eba5329.png)

**Comment by wmarcos** [comment]
Este paso hizo falta para el deploy:

UPDATE atl_CategoriaActividad SET `nombre`='to_act' WHERE `id`='1';
UPDATE atl_CategoriaActividad SET `nombre`='to_reflect_and_learn' WHERE `id`='2';
UPDATE atl_CategoriaActividad SET `nombre`='especial_events' WHERE `id`='3';

**Comment by jdcalaz** [comment]
No me deja acceder a evaluar una actividadad, a menos que sea por el link del e-mail
![image](https://user-images.githubusercontent.com/48033083/70756682-f631c200-1d1b-11ea-9259-f2b388491b4e.png)
