### ISSUE TITLE
Componentes de selección - Clip on select

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#172]
**Reporte del Error **
En los componentes de selección, al elegir algún valor, se agrega un salto de línea, margen o alguna línea extra, lo que rompe el formato del form.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a 'http://dev.atlas.test/admin'
2. Clickear en 'Nueva Actividad'
3. Hacer un SELECT y ver como cambia el salto de linea. 

**Comportamiento esperando**
que no se agregue un salto de linea que no es necesario.

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema

**Si estás en una computadora (por favor completá la siguiente información):**
 - Chrome 

**Smartphone (completá la siguiente informaicón):**

**Contexto adicional**

alejandro.abraham Alejandro Abraham added a comment - 21/May/18 8:57 PM
Estuve investigando, y al parecer el problema es un issue conocido por los que mantienen el plugin y están en vistas de corregirlo próximamente.

En el siguiente link se puede seguir el hilo de la discusión.

https://github.com/sagalbot/vue-select/pull/512

 

Para solucionarlo nosotros, tendríamos que tocar el código propio del plugin. No tiene sentido si esto va a ser corregido próximamente y con un update traeríamos el fix.

**Comment by aabraham88** [comment]
Solucionado en la versión 2.5.1 del plugin.
