### ISSUE TITLE
BE: Usuarios - Ver Listado - Ver/Guardar

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#179]
**Describí el error**
BE: Usuarios - Ver Listado - Ver/Guardar

**Para reproducirlo**
Pasos para reproducir el comportamiento en Mobile (DESARROLLO):
1. Ir a 'http://dev.atlas.test/admin/usuarios'
2. Clickear en 'INGRESAR' --> micaela.tangorra@globallogic.com
3. Menu -> ADMIN -> Usuarios -> Ver Listado
4. Voy a un usuario -> 
- cuando scrolleo hasta la Provincia y el select..no aparece la Localidad y el select
- y cuando aprieto Editar: cuando scrolleo me muestra hasta la Provincia..sin el select y tampoco aparece la Localidad y el select
5. Registrar Usuario -> cuando scrolleo me muestra hasta la Provincia..sin el select y tampoco aparece la localidad y el select.

**Comportamiento esperando**
1. Ir a 'http://dev.atlas.test/admin/usuarios'
2. Clickear en 'INGRESAR' --> micaela.tangorra@globallogic.com
3. Menu -> ADMIN -> Usuarios -> Ver Listado
4. Voy a un usuario 
5. Me deberia mostrar todos los campos

**Capturas de pantalla**
![20180913 - be- usuarios - ver listado - ver-guardar 1](https://user-images.githubusercontent.com/43036107/45499447-d4314480-b752-11e8-86d3-51bad4b98d04.JPG)
![20180913 - be- usuarios - ver listado - ver-guardar 2](https://user-images.githubusercontent.com/43036107/45499448-d4314480-b752-11e8-8ace-755ccdf735bd.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: , iPhone6/7/8
 - Navegador navegador del celu, Chrome

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by aabraham88** [comment]
Probar en demo

**Comment by MicaelaTangorra** [comment]
MOBILE:
  SandBox: Verificado: OK
