### ISSUE TITLE
FE: Perfil - Pais de Residencia (Politica de Privacidad)

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#180]
**Describí el error**
FE: Perfil - Pais de Residencia (Politica de Privacidad)

**Para reproducirlo**
Pasos para reproducir el comportamiento:
- http://dev.atlas.test/registro 
- Ingresar 
- Quiero ser Voluntario 
- Lleno todos los campos obligatorios 
- Cliqueo el textBox: "Acepto de Politica de Privacidad" (es obligatorio) 
-Cliqueo la boton "Crear Cuenta" 
==> No me la crea a la Cuenta y me muestra a misma pantalla 
==> adjunto la pantalla (F12)

**Comportamiento esperando**
- http://dev.atlas.test/registro 
- Ingresar 
- Quiero ser Voluntario 
- Lleno todos los campos obligatorios (por ej, el Pais de Residencia es OBLIGATORIO) 
- Cliqueo el textBox: "Acepto de Politica de Privacidad" (es obligatorio) 
-Cliqueo la boton "Crear Cuenta" 
- Me crea la cuenta e ingresa con el usuario recientemente creado. 

**Capturas de pantalla**
![perfil - pais de residencia](https://user-images.githubusercontent.com/43036107/45552265-c1784780-b806-11e8-9046-30bc8677ca2c.JPG)
![20180914 - perfil-pais de residencia](https://user-images.githubusercontent.com/43036107/45552280-cb01af80-b806-11e8-845c-53c85183ee77.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 -  chrome

**Smartphone (completá la siguiente informaicón):**

**Contexto adicional**
http://dev.atlas.test/registro

**Comment by MicaelaTangorra** [comment]
JIRA: https://velocity.globallogic.com/jira/browse/TEC-411

**Comment by aabraham88** [comment]
probar en demo

**Comment by MicaelaTangorra** [comment]
DEMO (http://sandbox.actividades.techo.org/): verificado OK
