### ISSUE TITLE
FE: Ingresar - Perfil -  Acepto de Politica de Privacidad

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#181]
**Describí el error**
FE: Ingresar - Perfil -  Acepto de Politica de Privacidad

**Para reproducirlo**
Pasos para reproducir el comportamiento:
- http://dev.atlas.test/registro 
- Ingresar 
- Quiero ser Voluntario 
- Lleno algunos de los campos obligatorios 
- No Cliqueo el textBox: "Acepto de Politica de Privacidad" (es obligatorio) 
- Cliqueo la boton "Crear Cuenta" 
- No me da crea porque faltan algunos. Por ejemplo: es de la "Acepto la Politica de Privacidad" aparece con una cruz que dice: "Debe aceptar las políticas de privacidad para continuar" 
- Cliqueo el textBox: "Acepto de Politica de Privacidad" (es obligatorio) 
- Cliqueo la boton "Crear Cuenta" 
- Faltan algunos campos obligatorios pero es TextBox de "Acepta la Politica de Privacidad" lo cliquee pero... 
==> me muestra la cartel de Error habiendola cliqueado 
==> adjunto la pantalla

**Comportamiento esperando**
- http://dev.atlas.test/registro 
- Ingresar 
- Quiero ser Voluntario 
- Lleno algunos de los campos obligatorios 
- No Cliqueo el textBox: "Acepto de Politica de Privacidad" (es obligatorio) 
- Cliqueo la boton "Crear Cuenta" 
- No me da crea porque faltan algunos. Por ejemplo: es de la "Acepto la Politica de Privacidad" aparece con una cruz que dice: "Debe aceptar las políticas de privacidad para continuar" 
- Cliqueo el textBox: "Acepto de Politica de Privacidad" (es obligatorio) 
- Cliqueo la boton "Crear Cuenta" 
- Faltan algunos campos obligatorios pero es TextBox de "Acepta la Politica de Privacidad" no aparece con el mensaje del error

**Capturas de pantalla**
![perfil - acepto la politica de privacidad](https://user-images.githubusercontent.com/43036107/45552510-83c7ee80-b807-11e8-8a58-870a117ca39c.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - chrome

**Smartphone (completá la siguiente informaicón):**

**Contexto adicional**
DESARROLLO: http://dev.atlas.test/registro

**Comment by MicaelaTangorra** [comment]
JIRA: https://velocity.globallogic.com/jira/browse/TEC-412

**Comment by jdcalaz** [comment]
Lo probé el 18/7/2019 en la version de Sandbox ''Incorpora-397-panel-de-estadisticas'' y sigue teniendo el mismo problema.

**Comment by agustempo** [comment]
Hola @jdcalaz , con [este pull](https://github.com/techo/voluntariado-eventual/pull/504) sumamos esta funcionalidad a la web!

**Comment by jdcalaz** [comment]
Genial @agustempo este lo acabo de testear y dió bien, sigo con el resto de la branch 344
