### ISSUE TITLE
FE: Quiero ser Voluntario - Registrame

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#186]
**Describí el error**
FE: Quiero ser Voluntario - Registrame - 2 usuarios

**Para reproducirlo**
Pasos para reproducir el comportamiento:
- http://dev.atlas.test/registro 
- Quiero ser voluntario 
- Registrame 
- Estoy llenando los campos para registrarme 
- Cliqueo "Ingresar" 
- Ingreso con OTRO usuario (por ej: micaela.tangorra@globallogic.com) 
- Ingreso con "Micaela Tangorra" 
- Me mantiene la misma pantalla de la registracion 
- Lleno los campos pendientes de la registacion (los obligatorios) 
- Presiono el boton "Crear Cuenta" 
- Me crea el usuario nuevo 
==> y me setea el usuario nuevo: por ej: "Mica23"

**Comportamiento esperando**
- http://dev.atlas.test/registro 
- Quiero ser voluntario 
- Registrame 
- Estoy llenando los campos para registrarme 
- Cliqueo "Ingresar" 
- Ingreso con OTRO usuario (por ej: micaela.tangorra@globallogic.com) 
- Ingreso con "Micaela Tangorra" y voy a TECHO (al HOME)

**Capturas de pantalla**
![quiero ser voluntario - registrame_1](https://user-images.githubusercontent.com/43036107/45562003-7b7bad80-b81f-11e8-80c0-c0faa8690da7.JPG)
![quiero ser voluntario - registrame_2](https://user-images.githubusercontent.com/43036107/45562004-7b7bad80-b81f-11e8-928a-afa7f57daff9.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome
**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
- http://dev.atlas.test/

**Comment by MicaelaTangorra** [comment]
Testing (https://sandbox.actividades.techo.org/): Verificado OK

**Comment by MicaelaTangorra** [comment]
Testing (https://sandbox.actividades.techo.org/): Verificado OK

**Comment by aabraham88** [comment]
Mergeado a dev.
