### ISSUE TITLE
FE: Boton del Menu (Mobile)

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#187]
**Describí el error**
FE: Boton del Menu (Mobile)

**Para reproducirlo**
Pasos para reproducir el comportamiento:
- https://actividades.techo.org/ con el celular (por ej: el Samsung J7) 
- usuario: micaela.tangorra@globallogic.com 
- Me aparece a la izquierda de la pantalla: Maria Micaela (en vez de a la derecha) 
- Cuando lo presiono: me despliega el menu pero no se ve bien: 
   - "es": debe decir "Mis Actividades" 
   - y el "Perfil" y "Salir" ..no te ve.

**Comportamiento esperando**
- https://actividades.techo.org/ con el celular (por ej: el Samsung J7) 
- usuario: micaela.tangorra@globallogic.com 
- Me aparece a la derecha de la pantalla: Maria Micaela 
- Cuando lo presiono: me despliega el menu : 
   - "Mis Actividades" 
   - "Perfil" y 
   - "Salir"

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
DEMO: https://actividades.techo.org/

**Comment by jdcalaz** [comment]
Lo probé y no vi problema alguno.
