### ISSUE TITLE
En Actividad: campo Descripción se reinicia al usar cualquier select

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#188]
**Describí el error**
BE: Crear una Actividad --> Apoyo Escolar

**Para reproducirlo**
- http://dev.atlas.test/
- micaela.tangorra@globallogic.com 
- Admin 
- Nueva Actividad 
- Categoria: Apoyo Escolar 
- Descripcion: Presiono el boton "Insert link" y pongo una imagen (Por ejemplo: https://www.google.com.ar/search?q=escolar&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjn19jx2OLcAhVDjZAKHTG4BOAQ_AUICigB&biw=1920&bih=974#imgrc=8Vy3ddxFXJvH9M:) 
- Lleno todos los campos de la Actividad 
- Antes de presionar "Guardar"...voy a "Descripcion" y no esta mas la imagen 
(tambien puse "Insert image" aparecio de imagen...pero antes de "Guardar" tampoco esta mas)

**Comportamiento esperando**

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador  chrome

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by aabraham88** [comment]
Mica, desde qué dispositivo/navegador lo estás probando?

**Comment by aabraham88** [comment]
Mergeado a dev.
