### ISSUE TITLE
BE: Mensaje de error al escribir nombre de coordinador (Nueva Actividad)

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#189]
**Describí el error**
Como administrador al cargar un actividad en la mayoría de los campos para seleccionar aparece apenas se hace foco el mensaje: "Sorry not matching options"

**Para reproducirlo**
Como administrador al cargar un actividad en la mayoría de los campos para seleccionar aparece apenas se hace foco el mensaje: "Sorry not matching options"

**Comportamiento esperando**
Si todavía no comencé a escribir, no debería dar un mensaje de error. Si no encontró opciones debería dar el mensaje pero en castellano

**Capturas de pantalla**
![image-2018-05-23-17-36-18-995](https://user-images.githubusercontent.com/43036107/45629119-03ee8e00-ba6c-11e8-9718-1679f83e5dc6.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador : chrome

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
DESA: http://dev.atlas.test/admin/actividades/crear

**Comment by MicaelaTangorra** [comment]
TESTING -> VERIFICADO OK  el de "Mensaje de error al escribir nombre de coordinador (Nueva Actividad)"

**Comment by MicaelaTangorra** [comment]
hay mas que no estan arreglados: "Mensaje de error en ingles al escribir:
 GRUPO: Voluntario Inscripto y Voluntario No Inscripto" (adjunto imagenes)

![20181212 - be - mensaje de error en ingles voluntario no inscripto](https://user-images.githubusercontent.com/43036107/49879137-14fb3100-fe08-11e8-811f-fe6d971e25e6.png)
![20181212 - be - mensaje de error en ingles voluntario inscripto](https://user-images.githubusercontent.com/43036107/49879140-1593c780-fe08-11e8-868b-7a48ebceaf1c.png)

**Comment by jdcalaz** [comment]
No figura ningún mensaje de error, ni antes de escribir ni en el caso de ingresar un nombre ajeno a la actividad.
Testeado el 25/7/2019 en la versión de Sandbox ''Incorpora-397-panel-de-estadisticas''
![image](https://user-images.githubusercontent.com/48033083/61903212-5e614200-aefa-11e9-9e0d-d4a7d83eee9c.png)
