### ISSUE TITLE
Conseguir texto definitivo para pantalla de bienvenida. Último paso de la registración.

### ISSUE THREAD

**Issue by aabraham88** [techo/voluntariado-eventual#190]
![captura de pantalla 2018-09-17 11 52 33](https://user-images.githubusercontent.com/9482070/45633760-05718380-ba77-11e8-8f19-0f4b05b872f4.png)

**Comment by aabraham88** [comment]
![captura de pantalla 2018-09-17 11 52 33](https://user-images.githubusercontent.com/9482070/45633706-dd822000-ba76-11e8-98a2-582536dd258b.png)

**Comment by wmarcos** [comment]
En principio esto, si más adelante se nos ocurre algo mejor, vemos.

Ya estás registrado/a como voluntario/a ¡Te esperamos en las próximas actividades!

**Comment by aabraham88** [comment]
Resuelto.
