### ISSUE TITLE
FE: Registrame - Paso 3/3

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#192]
**Describí el error**
En el paso 3/3, la url no es de Testing sino de Produccion

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. http://sandbox.actividades.techo.org/
2. Ingresar
3. ¡QUIERO SER VOLUNTARIO!
4. Paso 1/3 : el Correo Electronico y Crear una contraseña
5. Paso 2/3:  Pongo todos los campos obligatarios -> CREAR UNA CUENTA
6. Paso 3/3: Bienvenid@ a TECHO pero... la url que aparece es la de Produccion

**Comportamiento esperando**
1. http://sandbox.actividades.techo.org/
2. Ingresar
3. ¡QUIERO SER VOLUNTARIO!
4. Paso 1/3 : el Correo Electronico y Crear una contraseña
5. Paso 2/3:  Pongo todos los campos obligatarios -> CREAR UNA CUENTA
6. Paso 3/3: Bienvenid@ a TECHO 

**Capturas de pantalla**
![20180918-finalizar usuario registrado](https://user-images.githubusercontent.com/43036107/45698238-f0abf300-bb3d-11e8-9444-638f9acf99fb.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: chrome

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by aabraham88** [comment]
Se revisó y el problema ya no se reproduce.

**Comment by MicaelaTangorra** [comment]
TESTING -> Verificado OK

![20181004 - fe- registrame - paso 3 - ok](https://user-images.githubusercontent.com/43036107/46487533-9fa32c80-c7d6-11e8-9198-fdbf540ec588.JPG)
