### ISSUE TITLE
Agregar un comando sencillo para crear un usuario admin

### ISSUE THREAD

**Issue by aabraham88** [techo/voluntariado-eventual#199]
La idea es facilitar el proceso de instalación del repositorio para aquellos desarrolladores que quieran aportar algo al proyecto.

Para esto, se requiere generar un método rápido para que el desarrollador genere un usuario admin con el cual acceder por primera vez al sistema.

**Comment by aabraham88** [comment]
@wmarcos este issue por favor probalo vos.

**Comment by wmarcos** [comment]
git checkout dev
git merge instalacion_con_docker
git merge admin-seeder
docker-compose exec app php composer.phar dump-autoload
docker-compose exec app php composer.phar update
docker-compose exec app php artisan migrate --seed
docker-compose exec app php artisan db:seed --class=adminSeeder

¡Usuario creado correctamente!

![image](https://user-images.githubusercontent.com/94343/45888597-cbfd8880-bd94-11e8-96bb-b0ce644535d5.png)
