### ISSUE TITLE
BE: Nueva Actividad - Grupo

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#205]
**Describí el error**
BE: Nueva Actividad - "Grupo" no esta un Grupo que cree pero en la solapa "Inscripciones" esta en la columna Grupo si esta el Grupo que cree.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a 'https://sandbox.actividades.techo.org' en el celular
2. Clickear en 'Nueva Actividad'
3. En la solapa Grupo me creo un Grupo "Juego 1"  y pongo un voluntario (por ej: Alejandro Abraham) en ese mismo Grupo.
4. Creo la actividad (por ej: "Juego").
5. En la compu: edito en esa misma actividad y veo:
6. En la solapa "Grupo" no aparece el Grupo "Juego 1" pero en la solapa "Inscripciones" veo que esta el voluntario "Alejandro Abraham" y en la columna Grupo esta el grupo "Juego 1"

**Comportamiento esperando**
1. Ir a 'https://sandbox.actividades.techo.org' en el celular
2. Clickear en 'Nueva Actividad'
3. En la solapa Grupo me creo un Grupo "Juego 1"  y pongo un voluntario (por ej: Alejandro Abraham) en ese mismo Grupo.
4. Creo la actividad (por ej: "Juego").
5. En la compu: edito en esa misma actividad y veo:
6. En la solapa "Grupo" aparece el Grupo "Juego 1"  y en la solapa "Inscripciones" veo que esta el voluntario "Alejandro Abraham" y en la columna Grupo esta el grupo "Juego 1"

**Capturas de pantalla**
![20180924 - en grupo no esta pero en inscripciones si_1](https://user-images.githubusercontent.com/43036107/45956280-820ce080-bfe8-11e8-86ea-1d327cdaa269.JPG)
![20180924 - en grupo no esta pero en inscripciones si_2](https://user-images.githubusercontent.com/43036107/45956282-820ce080-bfe8-11e8-85b5-995b24225c02.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador por ejemplo: chrome

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: por ejemplo:  Samsung J7]
 - Sistema operativo: por ejemplo: Android4
 - Navegador por ejemplo: navegador del celu:Chrome

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by wmarcos** [comment]
@MicaelaTangorra ¿esto no pasa más no? veo que ahora están deshabilitadas las pestañas hasta que no se guarda la actividad.

![captura de pantalla de 2018-10-05 12-08-27](https://user-images.githubusercontent.com/94343/46543555-857d5300-c897-11e8-8aaa-ae9835eadbc4.png)

**Comment by jdcalaz** [comment]
Traté de reproducir el defecto, pero no lo encontré.
