### ISSUE TITLE
Front: colores en los sub-títulos en la pantalla de actividades

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#206]
En la pantalla de actividades, los subtítulos de las tarjetas (tipo de actividad) 

![Tarjeta en la pantalla Actividades](https://user-images.githubusercontent.com/94343/45960960-cea9e900-bff3-11e8-8b44-2f6f5e63d56a.png)

debería aparecer del color correspondiente a su clase de actividad.

![Colores en la Home](https://user-images.githubusercontent.com/94343/45961005-eda87b00-bff3-11e8-9547-9019c04cca0a.png)

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a pantalla Actividades
2. Ver color del subtítulo que indica el Tipo de actividad aparece en color violeta oscuro.

**Comportamiento esperando**
Debería aparecer del color indicado en la clase de la actividad (como está en la home)

**Comment by MicaelaTangorra** [comment]
TESTING --> 
  Verificado OK -> el color correspondiente a su clase de actividad.
  Verificado NOK -> el color de “Eventos Especiales” no es el mismo de la actividad MARATON 

-Eventos Especiales -> color: rgb(215, 142, 1);
    -Maraton -> style="color: rgb(199, 138, 0);

![20181227 - eventos especiales - front - colores en los sub-titulos en la pantalla de actividades 206 imagen_1](https://user-images.githubusercontent.com/43036107/50484945-e49fbf00-09d1-11e9-98fe-6ad06e92549b.JPG)
![20181227 - maraton - front - colores en los sub-titulos en la pantalla de actividades 206 imagen_2](https://user-images.githubusercontent.com/43036107/50484947-e49fbf00-09d1-11e9-994b-fe48cb5e9a3c.JPG)

-Actividades en Asentamientos -> color: rgb(0, 146, 221);
    -Apoyo Escolar -> color: rgb(68, 138, 221);

![20181227 - apoyo escolar - front - colores en los sub-titulos en la pantalla de actividades 206 imagen_4](https://user-images.githubusercontent.com/43036107/50485372-ca66e080-09d3-11e9-8c7d-8eeaffdcc544.JPG)
![20181227 - act en asentamientos - front - colores en los sub-titulos en la pantalla de actividades 206 imagen_3](https://user-images.githubusercontent.com/43036107/50485373-ca66e080-09d3-11e9-94c0-462b1e3ba230.JPG)

- Actividades de Oficina y Formacion -> color: rgb(234, 109, 79)
    - Capacitaciones -> color: rgb(216, 102, 68)

![20181227 - act de oficina y formacion - front - colores en los sub-titulos en la pantalla de actividades 206 imagen_5](https://user-images.githubusercontent.com/43036107/50485437-16198a00-09d4-11e9-9e30-3d91bc324c0d.JPG)
![20181227 - capacitaciones - front - colores en los sub-titulos en la pantalla de actividades 206 imagen_6](https://user-images.githubusercontent.com/43036107/50485438-16b22080-09d4-11e9-953d-ec795f7f53d9.JPG)

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado OK
