### ISSUE TITLE
Mailing: Imágenes en plantilla de mail no se ven correctamente

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#212]
**Describí el error**
Al recibirse un mail desde la plataforma las imágenes no se ven correctamente.

**Para reproducirlo**
Pasos para reproducir el comportamiento:

Pre-requisito: tener clickeado "Recibir notificaciones desde la plataforma" en "Mí perfil".

1. Ir a una actividad
2. Clickear en "Inscribirme"
3. Seguir los pasos hasta inscribirse correctamente.
4. Verificar en el mail recibido que las imágenes no aparecen correctamente.

**Comportamiento esperando**
Deberían verse las imágenes de la plantilla correctamente.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/94343/46316820-8e280d80-c5a7-11e8-84e6-d28b75384738.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Chrome, en linux

**Comment by MicaelaTangorra** [comment]
TESTING : Verificado OK

**Comment by MicaelaTangorra** [comment]
Una imagen que se ve bien: APOYO ESCOLAR:

![20181004 - mailing- imagenes en plantilla de mail no se ven correctamente](https://user-images.githubusercontent.com/43036107/46478628-c99f2380-c7c3-11e8-8f30-f153a83511fa.jpg)
