### ISSUE TITLE
Mailing: Link incorrecto a la plataforma en la plantilla de mails

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#213]
**Describí el error**
Al recibir un email de la plataforma en el footer se ve un link al sitio web que está incorrecto.

**Para reproducirlo**
Pasos para reproducir el comportamiento:

Pre-requisito: tener clickeado "Recibir notificaciones desde la plataforma" en "Mí perfil".

1. Ir a una actividad
2. Clickear en "Inscribirme"
3. Seguir los pasos hasta inscribirse correctamente.
4. Verificar en el mail recibido que las imágenes no aparecen correctamente.
5. Comportamiento esperando
6. Deberían verse las imágenes de la plantilla correctamente.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/94343/46316009-54560780-c5a5-11e8-8b4c-9e33e2cc5541.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 Chrome en linux

**Comment by aabraham88** [comment]
Corregido en PR #214 
Issue relacionado: #212
