### ISSUE TITLE
(prod) Iniciar sesión con Google genera error app_id

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#218]
**Describí el error**
Una descripción concisa de cual es el error.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a '...'
2. Clickear en '....'
3. Hacer scroll hasta '....'
4. Ver el error

**Comportamiento esperando**
Una descripción clara y concisa de que esperabas que pase y no pasó.

**Capturas de pantalla**
![captura de pantalla de 2018-10-04 10-14-12](https://user-images.githubusercontent.com/94343/46479720-0f5ceb80-c7c6-11e8-8b92-6f58663b6468.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by aabraham88** [comment]
Problema de configuración corregido.
