### ISSUE TITLE
(prod) Al crear una actividad con pago no solicita los datos del pago

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#220]
**Describí el error**
Al crear una actividad con flujo de pago (por ejemplo una construcción) en ningún momento se solicitan los datos de monto y beca que son necesarios.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a '...'
2. Clickear en '....'
3. Hacer scroll hasta '....'
4. Ver el error

**Comportamiento esperando**
Una descripción clara y concisa de que esperabas que pase y no pasó.

**Capturas de pantalla**
![captura de pantalla de 2018-10-04 11-11-30](https://user-images.githubusercontent.com/94343/46479799-46330180-c7c6-11e8-8d15-42bd9945f754.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by aabraham88** [comment]
Problema de configuración corregido.

**Comment by MicaelaTangorra** [comment]
PRODUCCION: Verificado OK

![20181004 - prod al crear una actividad con pago no solicita los datos del pago-- ok](https://user-images.githubusercontent.com/43036107/46484211-af6b4280-c7cf-11e8-9968-4d62059f4a35.JPG)
