### ISSUE TITLE
Creo una Actividad "Construccion", la guarda y me da un error

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#222]
**Describí el error**
Una descripción concisa de cual es el error.

**Para reproducirlo**

1. Ir a 'https://sandbox.actividades.techo.org/'
2. Clickear en 'INGRESAR'
3. En Login Normal como COORDINADOR:
   tangorra.micaela@gmail.com
4. Ingresa: "Hola, Coord Mica
5. En el Menu: Presiono "ADMIN"
6. "Crear Una Actividad" (en el margen izquierdo)
7. Lleno todos los campos . Principalmente estos que sea CONSTRUCCION: 
Categoria: Actividad en Asentamientos
Tipo de Actividad: Construccion
y en "CONSTRUCCION":
Monto Minimo (ARS): 500,00
Formulario de solicitud de beca: https://docs.google.com/spreadsheets/d/1j9Kfs3syHEMih7qCQkq68ERM976SROqGSqufJAB-LTI/edit#gid=0
8. "GUARDAR"
Lo guarda peroo no vuelve al LISTADO me da un error: "Ooops! ..."

**Comportamiento esperando**
1. Ir a 'https://sandbox.actividades.techo.org/'
2. Clickear en 'INGRESAR'
3. En Login Normal como COORDINADOR:
   tangorra.micaela@gmail.com
4. Ingresa: "Hola, Coord Mica
5. En el Menu: Presiono "ADMIN"
6. "Crear Una Actividad" (en el margen izquierdo)
7. Lleno todos los campos . Principalmente estos que sea CONSTRUCCION: 
Categoria: Actividad en Asentamientos
Tipo de Actividad: Construccion
y en "CONSTRUCCION":
Monto Minimo (ARS): 500,00
Formulario de solicitud de beca: https://docs.google.com/spreadsheets/d/1j9Kfs3syHEMih7qCQkq68ERM976SROqGSqufJAB-LTI/edit#gid=0
8. "GUARDAR"
9. un mensaje: "la actividad se creo correctamente"
10. Vuelve a listado de las actividades  y la creo

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
TESTING -> Verificado OK

**Comment by aabraham88** [comment]
Mergeado a dev.
