### ISSUE TITLE
Al asignar grupos en una actividad, se puede asignar un grupo a si mismo y genera problemas

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#224]
**Describí el error**
Al asignar grupos, se permite asignar un grupo a si mismo. Cosa que genera errores a la hora de que el usuario vea las evaluaciones.

Pre-requisitos:
- Una actividad creada con dos o más inscriptos.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a una actividad
2. Clickear en pestaña 'Grupos'
3. Crear un grupo
4. Seleccionar el grupo
5. Clickear en 'Asignar grupo'
6. Elegir ese mismo grupo

**Comportamiento esperando**
No debería permitir asignar un grupo recursivamente. Debería dar un error.

**Capturas de pantalla**

![captura de pantalla de 2018-10-05 16-51-26](https://user-images.githubusercontent.com/94343/46560203-36501600-c8c9-11e8-9f30-b28db70215fc.png)

![image](https://user-images.githubusercontent.com/94343/46560821-7b754780-c8cb-11e8-8838-cbc06f26ad74.png)

![image](https://user-images.githubusercontent.com/94343/46560831-8334ec00-c8cb-11e8-8848-9c07da0fab8a.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
TESTING -> Verificado OK

**Comment by aabraham88** [comment]
Mergeado a dev.
