### ISSUE TITLE
(prod) Agregar etiqueta en envío evaluaciones por email

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#227]
**Describí el error**
Al enviar las evaluaciones por email, a aquellos inscriptos que no tienen el presente no les llega el mail de evaluación ¡Debería avisar esto en la interfaz para que no sea confuso!

**Para reproducirlo**

Pre requisito: Una actividad con inscriptos que ya esté en su período de evaluación.

Pasos para reproducir el comportamiento:
1. Ir a Activdad
2. Clickear en solapa "Evaluaciones"
3. Hacer click en "Enviar evaluaciones"
4. Hacer click en "Enviar"

**Comportamiento esperando**
Debería indicar que se envía solo a los que tienen el presente.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/94343/46688517-f2645600-cbd3-11e8-8800-e8df32587dc9.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Chrome en Linux

**Comment by jdcalaz** [comment]
Lo probé tres veces, solo la segunda dió el aviso previo a enviar el mensaje que se van a enviar solo los que figuren como 'PRESENTE'
De todos modos, sería útil que luego de enviar el correo figure a cuantos voluntarios se los envió y
o a quienes.

**Comment by jdcalaz** [comment]
Lo probé y está perfecto
