### ISSUE TITLE
(prod) Link al form de beca obligatorio

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#228]
**Describí el error**
Al cargar una actividad con pago, si se deja en blanco el link al form de beca da un error diciendo que es obligatorio.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Clickear "Agregar una actividad"
2. Llenar los datos y dejar "formulario de beca" sin valor
3. Clickear en "Guardar"
4. Ver el error

**Comportamiento esperando**
El link del formulario de beca no debería ser obligatorio

**Capturas de pantalla**
Error en la carga de datos
![Carga de datos](https://user-images.githubusercontent.com/94343/46690966-13c84080-cbda-11e8-9564-ff9b56d07a31.png)

Link en el frontend, no debería aparecer si no se carga el link
![frontend](https://user-images.githubusercontent.com/94343/46691005-293d6a80-cbda-11e8-923d-f1419f256f8b.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Contexto adicional**
Al no ser obligatorio, en el front, en caso de no tener un el dato cargado la opción "pedir una beca" no debería aparecer en el front end.

**Comment by MicaelaTangorra** [comment]
TESTING -> Verificado OK

**Comment by aabraham88** [comment]
Mergeado a dev.
