### ISSUE TITLE
(prod) No llega mail de cancelación al borrar una actividad

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#230]
**Describí el error**
No llega mail de cancelación al borrar una actividad.

**Para reproducirlo**

Pasos para reproducir el comportamiento:
1. Cargar una actividad nueva
2. Inscribirse en la activdad
3. Clickear "Borrar actividad"
4. Aceptar confirmación
5. Verificar que el mail de cancelación de la actividad no llegó.

**Comportamiento esperando**
Debería llegar un mail avisando de la cancelación de la actividad.

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado OK
