### ISSUE TITLE
(prod) No se ven actividades sin localidad en "Mis Actividades"

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#231]
**Describí el error**
Las actividades que no tienen cargado el dato Localidad no aparecen en la sección "Mis actividades" del front ent

**Para reproducirlo**

Pre-requisito: tener cargada una actividad sin el campo Localidad

Pasos para reproducir el comportamiento:
1. Ir a "Mis actividades"
2. Ver que la actividad no aparece listada

**Comportamiento esperando**
Debería aparecer listada.

**Contexto**
Es necesario para que aparezca la información pasada de los usuarios.

**Comment by MicaelaTangorra** [comment]
Testing -> Verificado OK

![20181011 - mis actividades sin localidad - act futura](https://user-images.githubusercontent.com/43036107/46818322-56635780-cd57-11e8-908f-41d4ae256d43.JPG)
![20181011 - mis actividades sin localidad - act pasada](https://user-images.githubusercontent.com/43036107/46818335-5d8a6580-cd57-11e8-99c0-d5d904e98ece.JPG)
