### ISSUE TITLE
Error en el campo apellido al registrar un usuario

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#245]
**Describí el error**
Al registrar un usuario en el sistema con la letra ñ aparece un error "El formato del campo apellido es inválido."

**Para reproducirlo**
Pasos para reproducir el comportamiento:
Como administrador
1. Ir a Usuarios
2. Clickear en Registrar usuario
3. Completar los campos poniendo una ñ en el campo Apellido
4. Ver el error "El formato del campo apellido es inválido."

**Comportamiento esperando**
Debería aceptar apellidos con letra ñ, tildes y otros caracteres.

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/94343/47095699-1cd19700-d204-11e8-94b9-fa187f2ca157.png)

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by aabraham88** [comment]
@MicaelaTangorra ya está en el ambiente de pruebas para que lo puedas revisar.

**Comment by MicaelaTangorra** [comment]
TESTING -> Verificado OK

**Comment by aabraham88** [comment]
Pasado a producción.
