### ISSUE TITLE
Como administrador no se puede buscar usuarios por email

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#246]
**Describí el error**
Como Administrador/Coordinador al cargar actividades, o asignar roles no se puede buscar por dirección de email.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
Ser administrador
1. Ir a Roles
2. Clickear en Asignar Roles
3. Clicker en Usuario y empezar a escribir una dirección de email existente en el sistema
4. Ver que no se encuentra al usuario por su dirección de email

**Comportamiento esperando**
Debería haber encontrado un usuario por dirección de email y no lo hizo.

**Contexto adicional**
Es muy útil para un coordinador buscar por un mail conocido.

**Comment by aabraham88** [comment]
Validado y subido a producción.
