### ISSUE TITLE
Arreglos en la plantilla de email de incripción

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#256]
**Describí el error**
En la plantilla de mail hay varios errores. Link roto a la actividad, mail fijo de problemas de pago y otras cuestiones

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a una actividad
2. Clickear en Inscribirme
3. Seguir los pasos
4. Recibir el mail
5. Ver que el link de la actividad está roto y que el mail de problemas de pago no debería estar.

**Comportamiento esperando**
Debería funcionar el link y no mencionar el mail de problemas de pago.

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/94343/47237555-dae85280-d3b5-11e8-8df3-e1649460e27f.png)

**Contexto adicional**
Algunos detalles estéticos también podrían corregirse

**Comment by aabraham88** [comment]
Subido a entorno sandbox para testing.

**Comment by MicaelaTangorra** [comment]
TESTING -> Verificado OK

**Comment by aabraham88** [comment]
Mergeado a master
