### ISSUE TITLE
Backend: editar datos del usuario

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#259]
Como Administrador quiero editar los datos básicos del usuario para poder corregir/modificar/actualizar la información de los mismos en el sistema.

Esto significa:

- Ingresar al panel de administración del sistema
- Hacer click en el menú "usuarios", "ver listado"
- Buscar y elegir un usuario
- Ver sus datos y poder modificarlos (todos inclusive el mail)

![image](https://user-images.githubusercontent.com/94343/47396084-ca124680-d6ff-11e8-9811-8efb07007c64.png)

**Comment by MicaelaTangorra** [comment]
TESTING --> NOK

Editar un Usuario:

1) Provincia - Localidad: 
      * si no selecciono una opcion del combo, el EDITAR no me deja seleccionar  nada: "Sorry, no matching  options"
     * si seleccione una opcion del combo (Provincia y/o Localidad): no me deja cambiarla.

Registrar/Editar Usuario:

1) Telefono: puedo poner letras y caracteres especiales
![20190605 - BE editar datos del usuario](https://user-images.githubusercontent.com/43036107/58962960-a679a900-8782-11e9-89fa-7a830cf8b7a1.JPG)
.

**Comment by wmarcos** [comment]
Corregido y subido al sandbox!

**Comment by MicaelaTangorra** [comment]
TESTING --> NOK

Editar un Usuario:
1) Pais - Provincia - Localidad:
       - NO aparece lo que seleccione  al "Registrar Usuario"

Registrar/Editar Usuario:
1) Telefono: cuando selecciono un solo parentesis, el el telefono, me lo toma.

![20190606 - BE editar datos del usuario (registrar usuario)](https://user-images.githubusercontent.com/43036107/59047197-cd56de80-8859-11e9-88e8-344d9617de2c.JPG)
![20190606 - BE editar datos del usuario (telefono)](https://user-images.githubusercontent.com/43036107/59047198-cd56de80-8859-11e9-826d-d40f47d9275c.JPG)
![20190606 - BE - editar datos del usuario-1 (Pais - Provincia - Localidad)](https://user-images.githubusercontent.com/43036107/59047199-cd56de80-8859-11e9-9359-3a25f6f84e93.JPG)
![20190606 - BE - editar datos del usuario-2 (Pais - Provincia - Localidad)](https://user-images.githubusercontent.com/43036107/59047200-cdef7500-8859-11e9-8081-bd16d361ce5f.JPG)
![20190606 - BE - editar datos del usuario-3(Pais - Provincia - Localidad)](https://user-images.githubusercontent.com/43036107/59047201-cdef7500-8859-11e9-8467-c3d2522d7f13.JPG)

**Comment by wmarcos** [comment]
¡Qué suerte que estás vos Miks! me faltaban un par de cositas. Fijate ahora!

El teléfono puede aceptar caracteres: + ( ) - . x y espacios (esto es porque en otros países los teléfonos se escriben en otros formatos).

**Comment by MicaelaTangorra** [comment]
TESTING --> NOK

1) Consulta: el TELEFONO, en la imagen que adjunto, esta bien? 
![20190607 - BE editar datos del usuario - Telefono](https://user-images.githubusercontent.com/43036107/59117450-1ecba000-8924-11e9-9483-838bbcbe7651.JPG)


2) EDITAR USUARIO:  
Pongo PAIS: Brasil
Provincia: me selecciona , por ej, Buenos Aires, nada mas.
Localidad: estan todas. Lo modifico y GUARDAR.
Te adjunto una imagen

![20190607 - BE editar datos del usuario](https://user-images.githubusercontent.com/43036107/59117454-2723db00-8924-11e9-9258-2fd73ebbf580.JPG)

**Comment by MicaelaTangorra** [comment]
TESTING -->  NOK

EDITAR USUARIO:

1- Pongo PAIS: Albania (ANTES: Pais - Argentina)
2- Provincia: Buenos Aires (ANTES: Buenos Aires, nada mas).
3- Localidad: 25 de Mayo (estan todas con la Provincia Buenos Aires)
4- GUARDAR
5- Me lo guarda: "Usuario editado correctamente"
Te adjunto una imagen

![20190613 - editar datos del usuario_1](https://user-images.githubusercontent.com/43036107/59443209-f0413f80-8dd1-11e9-82d0-6e52476096de.JPG)

Registrar/Editar Usuario

1- Consulta: el TELEFONO, en la imagen que adjunto, esta bien?
Te adjunto la imagen

![20190607 - BE editar datos del usuario - Telefono](https://user-images.githubusercontent.com/43036107/59443373-41513380-8dd2-11e9-973d-426691c16c71.JPG)

**Comment by wmarcos** [comment]
Bien ahí miks.

Arreglado y listo para probar en sandbox:

1) Debería limpiar los combos provincia, país al cambiar de país

Antes (país Argentina)

![Captura de pantalla de 2019-06-13 17-20-59](https://user-images.githubusercontent.com/94343/59464827-dc143700-8dff-11e9-81b3-54f12e59c96d.png)

Después (país Albania)

![Captura de pantalla de 2019-06-13 17-21-10](https://user-images.githubusercontent.com/94343/59464845-e9312600-8dff-11e9-8f4d-6006ba1c36bb.png)

2) Si! el teléfono está OK.

**Comment by MicaelaTangorra** [comment]
TESTING --> OK
