### ISSUE TITLE
Mejora en rangos de fechas para la carga de actividades

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#262]
**Describí la mejora**
En la interfaz de administración, en el alta de una actividad es necesario completar tres **rangos** de fechas: 
- inscripción (inicio y fin)
- actividad (inicio y fin)
- evaluación (inicio y fin)

![image](https://user-images.githubusercontent.com/94343/47466953-30639b80-d7ca-11e8-9dd2-6cb105af21a4.png)

Las fechas de inscripción y evaluación podrían inferirse o calcularse evitando que haya que cargar tantos datos.

El cálculo sería así:
FI(inicio) = FA(inicio) - 10 días
FI(fin) = FA(inicio) - 1 minuto
FE(inicio) = FA(fin) + 1 minuto
FE(fin) = FA(fin) + 10 días

Las inscripciones empiezan 10 días antes y las evaluaciones terminan 10 días después.

Entonces, se debería agregar un control que permita mostrar/ocultar las fechas de inscripción y evaluación por ejemplo una flecha o un checkbox. Estas debería estar ocultas por defecto.

![image](https://user-images.githubusercontent.com/94343/47515645-d4485800-d859-11e8-8ce4-7109b5b42fd1.png)

**Si las fechas están ocultas**: auto completar los controles FI y FE a partir de la fecha de actividad (por javascript)
**si las fechas están visibles** (el usuario quiere especificar las fechas manualmente): mostrar los controladores para completar manualmente.

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

2) Las fechas de Inscripciones, Evaluaciones :
-. Testing
-. Me logueo como administrador
-. Selecciono una actividad
-. Las fechas:
    Fecha de Inicio y Fin Inscripcion:   25/12/2018 (00:00 - 23:59) (no la cambio)
    Fecha de Inicio y Fin Actividad:   26/12/2018 (00:00 - 23:59) (no la cambio)
    Fecha de Inicio y Fin Evaluaciones:   27/12/2018 (00:00 - 11:59) --> esta reportado el issue en un comentario antes.
-. Completo los campos para agregarla
-. Guardar
-. y me la guarda: hay un error porque calcula es 1 dia de fecha de Inscripcion y 1 dia la fecha de Evaluaciones .

El cálculo sería así:
**FI(inicio) = FA(inicio) - 10 días
FE(fin) = FA(fin) + 10 días**

![20181226 - mejora en rangos de fechas para la carga de actividades 262 imagen_3](https://user-images.githubusercontent.com/43036107/50450319-e901a480-090b-11e9-8787-74efacd53a1f.JPG)
