### ISSUE TITLE
Mejora: no cargar punto de encuentro si no es necesario

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#263]
**Describí la mejora**

Como Coordinador/Administrador, en el panel de administración, al crear una actividad, existe un caso en que una actividad tenga como punto de encuentro el mismo lugar donde se lleva a cabo.

Lugar de la actividad = punto de encuentro único

En ese caso (que es el general) no debería hacer falta cargar un punto de encuentro y se podría cargar automáticamente a partir de los datos de la actividad.

**Específicación técnica**

1- Agregar campo en ubicación

En el backend, en el módulo de actividades, en el detalle de la actividad

![image](https://user-images.githubusercontent.com/94343/49549146-a4638a00-f8c6-11e8-84cf-6886eafc895e.png)

Agregar un campo de texto libre llamado "Lugar" 

2- Crear punto de encuentro automático

En el backend, en el alta de actividad en el texto de "No hay puntos de encuentro..."

![image](https://user-images.githubusercontent.com/94343/49549185-be04d180-f8c6-11e8-808a-959e7df1ef66.png)

agregar "..., se creará uno automáticamente."

Si al guardar la actividad nueva no se cargó un punto de encuentro crear un punto de encuentro por backend en el controlador siguiendo esta regla:

Punto_de_Encuentro = Actividad.Lugar
Hora = Actividad.Fecha_de_actividad_inicio
Responsable = Actividad.Coordinador
País = Actividad.País
Provincia = Actividad.Provincia
Localidad = Actividad.Localidad

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

   "Comportamiento esperando" --> NO PASA

![20190107 - campo localidad 325 y no cargar punto de encuentro si no es necesario 263](https://user-images.githubusercontent.com/43036107/50776086-d32ea080-1276-11e9-8027-982aba546452.JPG)

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

-. Testing
-. BackEnd
-. Crear una Actividad
-. en la solapa "General": en "Ubicacion de la Actividad" dejo sin llenar "Lugar"
-. Completo todos los campos de la actividad
-. Presiono "Guardar"
y me sale, en la Consola, 4 mensajes en rojo --> Adjunto la imagen

![20190108 - lugar - ubicacion de la actividad](https://user-images.githubusercontent.com/43036107/50841066-a647bf80-1342-11e9-9ac4-504983936508.JPG)

**Comment by MicaelaTangorra** [comment]
En "Lugar" de:
  "Ubicacion de la Actividad" y de "Puntos de Encuentro" deberian ser "requerido" (charlado con Marcos Wolff)

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

-. Testing
-. BackEnd
-. Crear una Actividad
-. No llene ningun campos en "Ubicacion de la Actividad"
-. Cargue todos los campos de la actividad menos la "Ubicacion de Actividad"
-. Presiono "Guardar"
y me aparece en la consola un error --> imagen

![20190109 - no puse ningun campos en ubicacion de la actividad](https://user-images.githubusercontent.com/43036107/50910375-7107a400-140c-11e9-930c-948951fbc5fa.JPG)

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

-. Testing
-. BackEnd
-. Selecciono uan actividad ("oficios 9/1")
-. Editar
-. Pongo en "Localiad" en "Ubicacion de la Actividad" y en "Punto de Encuentro":
     Baradero --> No definida (vacio)
-. Guardar
-. Solapa "Grupos"
-. cliqueo "Voluntario No Inscripto"
      -."Nombre" (un nombre) y 
      -. "Punto de Encuentro" --> esta vacio!
en la solapa "General" hay un "Lugar" pero no aparece nada en la solapa "Grupos"

![20190109 - punto de encuentro en grupos](https://user-images.githubusercontent.com/43036107/50911108-ede74d80-140d-11e9-9e87-056f64ba60a0.JPG)

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

-. TESTING
-. BackEnd
-. Selecciono una Actividad
-. Solapa "Inscripciones":
   - cliqueo a un inscripto: "Asignar Punto" y cambio el "Punto de Encuentro"
    - Confirmar
-. Aparece un cartel: "Punto de encuentro actualizado en 1 voluntarios correctamente"
...pero no aparece ningun mail mostrando el "cambio de Punto de Encuentro"

![20190111 - punto de encuentro no llega el mail _1](https://user-images.githubusercontent.com/43036107/51043086-91feff00-159c-11e9-9c1f-78335ff468cf.JPG)
![20190111 - punto de encuentro no llega el mail _2](https://user-images.githubusercontent.com/43036107/51043200-e30ef300-159c-11e9-96e0-1b89acab7e62.JPG)

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

-. TESTING
-. BackEnd
-. Selecciono una Actividad: 
-. Solapa "Inscripciones":
      - cliqueo a un inscripto: en el detalle la "localidad" aparece en NULL  -> la localidad esta "no definida" en el "Punto de Encuentro"

![20190111 - inscriptos en null en punto de encuentro](https://user-images.githubusercontent.com/43036107/51045809-43a12e80-15a3-11e9-99a5-7cf4cadbe463.JPG)

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

-  Aparece un mail mostrando el "cambio de Punto de Encuentro" (por ej: "oficios 9/12")  --> OK
![20190114 - manda un mail por cambio de punto de encuentro](https://user-images.githubusercontent.com/43036107/51121040-2ebbd980-17f5-11e9-98d1-330e77a093f4.JPG)
-  Nueva Actividad con otro coordinador q no sea yo (micaela.tangorra) y esta bien en mail (por ej: "encuentamiento 14/1") --> OK
-  Cliqueo a un inscripto: en el detalle la "localidad" aparece en NULL -> la localidad esta "no definida" en el "Punto de Encuentro" --> no debe aparecer la descripcion "null" --> NOK
-

**Comment by agustempo** [comment]
con el nuevo metodo de creacion este tk ya estaria solucionado

@jdcalaz
