### ISSUE TITLE
BE: Borro una actividad y aparece un cartel: "Ooops, vuelve y busca otra ruta"

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#265]
**Describí el error**
Borro una actividad y aparece un cartel: "Ooops, vuelve y busca otra ruta"

**Para reproducirlo**
Pasos para reproducir el comportamiento:
-. Ir a 'https://sandbox.actividades.techo.org/'
-. Me logueo como coordinador
-. Menu: ADMIN 
-. Creo una Actividad: CONSTRUCCION (Categoria de la Actividad)
-. Guardar
-. Vuelvo al Listado
-. Cliqueo en la actividad recien creada
-. Borro la actividad recien creada: "Borrar"
-. Me aparece un cartel: "Ooops, vuelve y busca otra ruta"
pero...me borra la actividad del backEnd y del FroetEnd

**Comportamiento esperando**

-. Ir a 'https://sandbox.actividades.techo.org/'
-. Me logueo como coordinador
-. Menu: ADMIN 
-. Creo una Actividad: CONSTRUCCION (Categoria de la Actividad)
-. Guardar
-. Vuelvo al Listado
-. Cliqueo en la actividad recien creada
-. Borro la actividad recien creada: "Borrar"
-. Vuelve al Listado de "Mis Actividades" habiendola borrado

**Capturas de pantalla**
![20181030 - be borro una actividad y aparece un cartel ooops vuelve y busca otra ruta](https://user-images.githubusercontent.com/43036107/47724994-81deb100-dc36-11e8-9eaf-cb85374a54c2.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by aabraham88** [comment]
El problema es que está redirigiendo al usuario al listado de Todas las actividades, el cual no tiene permisos para ver cómo coordinador. La solución es redirigir al usuario a Mis Actividades, dónde tanto el administrador como el coordinador tienen acceso.Saludos!El 30 oct. 2018 11:28, MicaelaTangorra <notifications@github.com> escribió:Describí el error
Borro una actividad y aparece un cartel: "Ooops, vuelve y busca otra ruta"
Para reproducirlo
Pasos para reproducir el comportamiento:
-. Ir a 'https://sandbox.actividades.techo.org/'
-. Me logueo como coordinador
-. Menu: ADMIN
-. Creo una Actividad: CONSTRUCCION (Categoria de la Actividad)
-. Guardar
-. Vuelvo al Listado
-. Cliqueo en la actividad recien creada
-. Borro la actividad recien creada: "Borrar"
-. Me aparece un cartel: "Ooops, vuelve y busca otra ruta"
pero...me borra la actividad del backEnd y del FroetEnd
Comportamiento esperando
-. Ir a 'https://sandbox.actividades.techo.org/'
-. Me logueo como coordinador
-. Menu: ADMIN
-. Creo una Actividad: CONSTRUCCION (Categoria de la Actividad)
-. Guardar
-. Vuelvo al Listado
-. Cliqueo en la actividad recien creada
-. Borro la actividad recien creada: "Borrar"
-. Vuelve al Listado de "Mis Actividades" habiendola borrado
Capturas de pantalla

Si estás en una computadora (por favor completá la siguiente información):
Navegador [por ejemplo: chrome, explorar, safari]
Smartphone (completá la siguiente informaicón):
Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]Sistema operativo: [por ejemplo: Android4, iOS8.1]Navegador [por ejemplo: navegador del celu, Chrome, Safari]
Contexto adicional
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
Si Ale, lo probe con un ADMINISTRADOR: cree un actividad CONSTRUCCION y la borre y vuelve al listado, sin problemas! Es con un COORDINADOR el problema!  Gracias Ale!

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado OK
