### ISSUE TITLE
BE: Ingreso un voluntario y me manda un mail que te has inscripto a esa actividad

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#266]
**Describí el error**
Ingreso un voluntario y me manda un mail que te has inscripto a esa actividad y en la aplicacion me figura como "ya estas inscripto!"

**Para reproducirlo**
Pasos para reproducir el comportamiento:
-. Ir a 'https://sandbox.actividades.techo.org/'
-. Me logueo como administrador (por ej: micaela.tangorra@globallogic.com)
-. Menu: ADMIN - Mis Actividades 
-. Cliqueo una Actividad: por ej: 
    - Tipo de Actividad: Deteccion y Asignacion
    - Categoria: Actividades de Asentamientos 
-. Clonar Actividad
-. la fecha de inscripcion: es la de hoy
-. La clone y veo la actividad creada (por ej: "Copia de Detec 31/10")
-. Voy a Grupos
-. Presiono el boton: "Voluntario No Inscripto"
-.Genero un voluntario
-. Voy al margen izquierdo: Portal de Actividades - Ver filtros
-. y voy al mail de globallogic (por ej) y me aparece un mail que dice: 
"TECHO: Te inscribiste a Copia de Detec 31/10"
-. Voy a la aplicacion (FE): y me figura en la actividad que me clone hoy: 
"¡Ya te inscribiste!"

**Comportamiento esperando**

-. Ir a 'https://sandbox.actividades.techo.org/'
-. Me logueo como administrador (por ej: micaela.tangorra@globallogic.com)
-. Menu: ADMIN - Mis Actividades 
-. Cliqueo una Actividad: por ej: 
    - Tipo de Actividad: Deteccion y Asignacion
    - Categoria: Actividades de Asentamientos 
-. Clonar Actividad
-. la fecha de inscripcion: es la de hoy
-. La clone y veo la actividad creada (por ej: "Copia de Detec 31/10")
-. Voy a Grupos
-. Presiono el boton: "Voluntario No Inscripto"
-.Genero un voluntario
-. Voy al margen izquierdo: Portal de Actividades - Ver filtros
-. en FE: Aparece la actividad perooo: no esta inscripto y en el mail: no me manda un mail que inscripcion.

**Capturas de pantalla**
![20181101 - ingreso un voluntario y me manda un mail que te has inscripto a esa actividad](https://user-images.githubusercontent.com/43036107/47860534-7e326200-ddcf-11e8-80b5-97010da5a810.JPG)
![20181101 - ingreso un voluntario y me manda un mail que te has inscripto a esa actividad_2](https://user-images.githubusercontent.com/43036107/47860544-82f71600-ddcf-11e8-80cf-b36cf91f7e9b.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by wmarcos** [comment]
Lo charlamos con @MicaelaTangorra en la dialy y no es un bug. Lo cerramos!
