### ISSUE TITLE
BE: No manda un mail por recordatorio de actividad

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#271]
**Describí el error**

**Para reproducirlo**
Pasos para reproducir el comportamiento: 
-. Ir a la url de TESTING'
-. Entrar como ADMINISTRADOR
-. Me inscribo a una actividad: 
por ej: Tipo de Actividad: Construccion o Emprendedores o etc
Fecha de Inscripcion: 6/11/2018
Fecha de Inicio y Fin de la actividad : del 7/11/18 al 8/11/2018
-. y..no manda un mail por recordatorio de que empieza la actividad mañana 
-> (La Fecha de Actividad es 7/11/2018 deberia mandar un mail hoy)

**Comportamiento esperando**

-. Ir a la url de TESTING'
-. Entrar como ADMINISTRADOR
-. Me inscribo a una actividad: 
por ej: Tipo de Actividad: Construccion o Emprendedores o etc
Fecha de Inscripcion: 6/11/2018
Fecha de Inicio y Fin de la actividad : del 7/11/18 al 8/11/2018
-. Manda un mail por recordatorio de actividad 

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema
**Si estás en una computadora (por favor completá la siguiente información):**

 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by aabraham88** [comment]
Esto no es tan sencillo de probar manualmente. Ya que depende de un cron job. En el ambiente de testimg si no me equivoco no está configurado, y esto es intencional, para no spammear con mails de prueba. Pero se puede ejecutar manualmente por consola.El 6 nov. 2018 12:46, MicaelaTangorra <notifications@github.com> escribió:Describí el error
Para reproducirlo
Pasos para reproducir el comportamiento:
-. Ir a la url de TESTING'
-. Entrar como ADMINISTRADOR
-. Me inscribo a una actividad:
por ej: Tipo de Actividad: Construccion o Emprendedores o etc
Fecha de Inscripcion: 6/11/2018
Fecha de Inicio y Fin de la actividad : del 7/11/18 al 8/11/2018
-. y..no manda un mail por recordatorio de que empieza la actividad mañana
-> (La Fecha de Actividad es 7/11/2018 deberia mandar un mail hoy)
Comportamiento esperando
-. Ir a la url de TESTING'
-. Entrar como ADMINISTRADOR
-. Me inscribo a una actividad:
por ej: Tipo de Actividad: Construccion o Emprendedores o etc
Fecha de Inscripcion: 6/11/2018
Fecha de Inicio y Fin de la actividad : del 7/11/18 al 8/11/2018
-. Manda un mail por recordatorio de actividad
Capturas de pantalla
Si aplica, agregá capturas de pantalla para explicar el problema
Si estás en una computadora (por favor completá la siguiente información):
Navegador [por ejemplo: chrome, explorar, safari]
Smartphone (completá la siguiente informaicón):
Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]Sistema operativo: [por ejemplo: Android4, iOS8.1]Navegador [por ejemplo: navegador del celu, Chrome, Safari]
Contexto adicional
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado OK

- Titulo del mail: "TECHO 'nombre de la actividad' esta por comenzar"
- Fecha del mail: a day ago (esta actividad comienza con fecha de actividad hoy: 14/1/2019 y esta bien!)

Adjunto una imagen:

![20190114 - manda un mail por recordatorio de actividad](https://user-images.githubusercontent.com/43036107/51118202-8acf2f80-17ee-11e9-8a1d-de9908d6d4a3.JPG)

**Comment by wmarcos** [comment]
En este issue se encontró otro problema:

En las actividades de tipo construcción, se le recuerda a "todos" los inscriptos, cuando debería recordarse solo a los confirmados.

Cómo no es una feature que se entienda como importante, se da de baja el recordatorio de actividades.
