### ISSUE TITLE
FE y BE: Bugs de los botones y los textos

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#272]
**Describí el error**
Bugs de los botones y de los textos: en diferentes paginas, hay botones/textos con mayusculas y en otra pagina, aparecen com minusculas o con la primer letra en mayuscula.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
-. Ir a TESTING
-. Adjunto/s las imagenes

**Comportamiento esperando**

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador  chrome

Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
Mis Actividades - Ver Evaluaciones:
"Nombre, apellido o DNI del voluntario" o "nombre, apellido o DNI" --> el nombre va todo con minscula o va la primera letra con mayuscula y despues todo con mayuscula. Lo mismo pasa con apellido.

![20181108 - fe y be - bugs de los botones y los textos_1](https://user-images.githubusercontent.com/43036107/48207052-9285da00-e34e-11e8-9f3d-d114045d64ca.JPG)

**Comment by MicaelaTangorra** [comment]
-. Ir a Testing
-. "Actividades" 
- Una Actividad 
- Me voy a Inscribir
- Me inscribi 
- y hay 2 links: el "VOLVER" no tiene el mismo color de azul de TECHO y tampoco el boton "CONFIRMAR"

![20181109 - el color del link no es el azul de techo_3](https://user-images.githubusercontent.com/43036107/48262038-d8e74180-e3ff-11e8-873c-b32c6466d839.JPG)

**Comment by MicaelaTangorra** [comment]
ISSUE: FE: El color del link NO es el azul de TECHO  #279 --> hay que arregarlo tambien!

**Comment by jdcalaz** [comment]
No logro entender el modo para reproducir el problema ¿es de una versión vieja de sandbox?
De ser así ¿cierro esta Issue?
