### ISSUE TITLE
FE: El color del link NO es el azul de TECHO

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#279]
**Describí el error**
El color del link NO es el azul de TECHO en varias paginas.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
-. Ir a TESTING
-. Me logueo
-. Selecciono una actividad para inscribirme
-.y los links de: "carta de voluntariado" y el <nombre de actividad> no son del mismo color azul que lo de TECHO

**Comportamiento esperando**
-. Ir a TESTING
-. Me logueo
-. Selecciono una actividad para inscribirme
-. y los links de: "carta de voluntariado" y el <nombre de actividad> son del mismo color azul que lo de TECHO.

**Capturas de pantalla**
![20181108 - el color del link no es el azul de techo_1](https://user-images.githubusercontent.com/43036107/48208632-0675b180-e352-11e8-8508-500a301b251b.JPG)
![20181108 - el color del link no es el azul de techo_2](https://user-images.githubusercontent.com/43036107/48208645-0d042900-e352-11e8-9699-1c4a22f14852.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
-Ir a Testing
- "Actividades"
- Una Actividad
- Me voy a Inscribir
- Me inscribi
y... hay 2 links: el "VOLVER" no tiene el mismo color de azul de TECHO y tampoco el boton "CONFIRMAR"

![20181109 - el color del link no es el azul de techo_3](https://user-images.githubusercontent.com/43036107/48262159-41362300-e400-11e8-9888-eae8f8303b19.JPG)

**Comment by wmarcos** [comment]
Queda en el bug general para corrección de frontend
