### ISSUE TITLE
BE: Errores al crea una actividad estan desacomodados

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#283]
**Describí el error**
Errores al crea una actividad estan desacomodados

**Para reproducirlo**
Pasos para reproducir el comportamiento:
-. Ir a TESTING
-. Menu - ADMIN - Crear una Actividad
-. Presiono el boton "Guardar"
-. Aparecen los "Errores" pero estan desacomodados. Por ejemplo:
"El campo localidad debe tener un valor valido" y despues viene, por ejemplo:
"El campo Oficina es requerido"

**Comportamiento esperando**
-. Ir a TESTING
-. Menu - ADMIN - Crear una Actividad
-. Presiono el boton "Guardar"
-. Aparecen los errores acomodados por solapa: Informacion General, Ubicacion de la Actividad, Puntos de Encuentro, Inscripciones, Construccion

**Capturas de pantalla**
![20181114 - errores al cargar una nueva actividad](https://user-images.githubusercontent.com/43036107/48492246-213f9e80-e808-11e8-85cb-5294232fdd77.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by jdcalaz** [comment]
Sigue el error, aunque no se si es tan relevante que presente los items a completar de manera desordenada. Cambio la etiqueta de ''Defecto'' a ''Mejora'', llegado al caso corrijanme.

Testeado 25/7/2019 Sandbox versión: ''Incorpora-397-panel-de-estadisticas''

**Comment by agustempo** [comment]
listo el orden de los errores, ahora los muestra según el orden de los errores y esta listo para probar en el sandbox!

**Comment by jdcalaz** [comment]
En si está bien, solo que tiene dos renglones repetidos (''Debe seleccionar una categoría y un tipo de actividad'')
![image](https://user-images.githubusercontent.com/48033083/66428159-e7612300-e9eb-11e9-8d65-d618f5343e12.png)
