### ISSUE TITLE
BE: Ver Todas - aparece un cartel que no tiene que aparecer

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#285]
**Describí el error**
Ver Todas - aparece un cartel que no tiene que aparecer porque edite una actividad en "Mis Actvidades"

**Para reproducirlo**
Pasos para reproducir el comportamiento:
-. Ir a 'TESTING'
-. Me logueo como administrador
-. Menu: ADMIN - Mis Actividades 
-. Selecciono una actividad
-. Edito un campo
-. Guardar
-. Aparece un cartel: "Actividad guardada correctamente"
-.Presiono el boton "Volver al listado"
-. Selecciono "Ver Todas" (en el menu - al margen izquierdo)
-. y me aparece una cartel que dice: "La actividad  se creo correctamente" y no debe aparecer

**Comportamiento esperando**
-. Ir a 'TESTING'
-. Me logueo como administrador
-. Menu: ADMIN - Mis Actividades 
-. Selecciono una actividad
-. Edito un campo
-. Guardar
-. Aparece un cartel: "Actividad guardada correctamente"
-.Presiono el boton "Volver al listado"
-. Selecciono "Ver Todas" (en el menu - al margen izquierdo)

**Capturas de pantalla**
![20181115 - ver todas - aparece un cartel que no tiene que aparecer](https://user-images.githubusercontent.com/43036107/48557547-d5532f00-e8c5-11e8-8f18-34aafaad171f.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by jdcalaz** [comment]
Sigue el error, aunque si se actualiza la página desaparece el mensaje.
Testeado el 25/7/2019, sandbox versión ''Incorpora-397-panel-de-estadisticas''

![image](https://user-images.githubusercontent.com/48033083/61904263-dd577a00-aefc-11e9-965b-2b30a3931b54.png)
