### ISSUE TITLE
Como coordinador al ver un usuario confirmado y con pago no puedo saber quien lo actualizó

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#286]
**Describí el error**
Como coordinador/administrador al ver los inscriptos a una actividad, no puedo saber quién confirmó o actualizó el pago de esa persona.
Es necesario poder saber quien fue el último en actualizar la inscripción y cuando lo hizo.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a una actividad con permisos
2. Clickear en Inscripciones
3. Hacer scroll hasta un usuario con el pago confirmado
4. Ver que no puedo saber quien lo confirmó

**Comportamiento esperando**
Debería poder ver en algún lado quien actualizó esa entrada y cuando lo hizo.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/94343/48576348-0f86f580-e8f3-11e8-8fdc-776a8a1e0f1d.png)

**Contexto adicional**
Esto nos pasó en la primera construcción de Posadas, cuando había voluntarios que se inscribieron, no pagaron en el momento y aparecían confirmados. Revisando la db vimos que se habían actualizado por alguien, pero no podíamos saber quien había sido.

**Comment by wmarcos** [comment]
Se implementa con dos botones de auditoría

En la pestaña general
![image](https://user-images.githubusercontent.com/94343/49740248-95882900-fc72-11e8-8b2f-8060d0517e29.png)

En la pestaña de inscripciones
![image](https://user-images.githubusercontent.com/94343/49740295-a769cc00-fc72-11e8-8ab6-c312733e96b8.png)

Permite ver cada modificación sobre ese concepto

![image](https://user-images.githubusercontent.com/94343/49740359-bbadc900-fc72-11e8-802e-37790bd946fa.png)

**Comment by wmarcos** [comment]
¿guarda el estado anterior?

**Comment by MicaelaTangorra** [comment]
Mando las imagenes de la solapa "Inscripciones" y de la solapa "General" (wmarcos: "guarda el estado anterior").
-Inscripciones:
en cualquier voluntario le pongo "Asistencia" como Presente,
Voy a ver "Ver auditoria" y  veo que en "Presente" tiene un "0"
![20181213 - auditoria en inscripciones imagen 1](https://user-images.githubusercontent.com/43036107/49950364-6d006900-fed6-11e8-8833-bf7abed2ab08.JPG)
![20181213 - auditoria en inscripciones imagen 2](https://user-images.githubusercontent.com/43036107/49950366-6d006900-fed6-11e8-8538-aa291082195c.JPG)

-General
en las "fechaInicioEvaluaciones" y "fechaFinEvaluaciones" tiene la misma fecha (2018-12-12 xx:xx:xx) y en la actividad tiene fechas "fechaInicioEvaluaciones y fechaFinEvaluaciones" por 2018-12-12  xx:xx:xx y 2018-12-13  xx:xx:xx

![20181213 - auditoria en general imagen 3](https://user-images.githubusercontent.com/43036107/49950369-6d98ff80-fed6-11e8-872a-dcb0fb618344.JPG)

**Comment by wmarcos** [comment]
Es un poco confuso que guarde el estado anterior. Le cambio la etiqueta de "Ver info" a "Ver original" para que se entienda mejor.

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado OK
TESTING --> Verificado OK
- No veo el label "Ver original"
- Con Pago: me sigue saliendo como es estado anterior
![20181214 - be - inscripciones con pago - asistencia imagen 1](https://user-images.githubusercontent.com/43036107/50010760-03955e80-ff99-11e8-9fd2-0d8108876ead.JPG)

![20181214 - be - auditoria - pago y presente imagen 2](https://user-images.githubusercontent.com/43036107/50010763-042df500-ff99-11e8-86b8-19d715ca61c5.JPG)

- General -> Auditoria: El coordinador de la actividad (Micaela Tangorra) esta la solapa "Inscripciones" tiene "Pagado" y "Ausente" y en la auditoria aparece como NULL (pago, y presente)
![20181214 - be - auditoria - pago y presente imagen 3](https://user-images.githubusercontent.com/43036107/50010764-042df500-ff99-11e8-8d57-48264ceded4d.JPG)

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado OK
(Auditoria: Guarda el "Estado Anterior" y el "Estado Actual" se ve en la pantalla)
