### ISSUE TITLE
BE - Grupos - Filtrar por - "Oficina" y "Estado" NO aparecen en las columnas

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#291]
**Describí el error**
BE - Grupos - Filtrar por - "Oficina" y "Estado" NO aparecen en las columnas. Entonces hay que sacar en grisaceo "Oficina" y "Estado" o hay que poner 2 columnas con titulo: "Oficina" o "Estado".

**Para reproducirlo**
Pasos para reproducir el comportamiento:
-.TESTING
-.Me logueo
-.Menu - ADMIN - Mis Actividades
-. Selecciono una Actividad: Por ejemplo: "Constr 28/11"
-. Voy a la solapa "Grupos"
-. En "Filtrar por:" hay en grisaceo: "Buscar por Nombre, Oficina, Tipo o Estado"
y no hay una columna donde vea: "Oficina" o el "Estado" entonces busco por "Oficina" o "Estado" y no me va a devolver nada.
Entonces hay que sacar en grisaceo "Oficina" y "Estado" o hay que poner 2 columnas con titulo: "Oficina" o "Estado".

**Comportamiento esperando**
-.TESTING
-.Me logueo
-.Menu - ADMIN - Mis Actividades
-. Selecciono una Actividad: Por ejemplo: "Constr 28/11"
-. Voy a la solapa "Grupos"
-. En "Filtrar por:" hay en grisaceo: "Buscar por Nombre, Oficina, Tipo o Estado"
-. Entonces hay que sacar en grisaceo "Oficina" y "Estado" o hay que poner 2 columnas con titulo: "Oficina" o "Estado".

**Capturas de pantalla**
![20181128 - grupos - filtrar por - oficina y estado no aparecen en las columnas](https://user-images.githubusercontent.com/43036107/49155020-ad69bf80-f2f8-11e8-9b9d-a40dcb9337c3.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador:  chrome

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by jdcalaz** [comment]
¿Esta Issue la destaco de alguna manera? ¿La paso de la columna 'Para hacer' a la columna 'Lista para tomar'?
Porque sigue sucediendo lo mismo

**Comment by agustempo** [comment]
Listo Mica para este tambien probarlo en el sandbox! >)

**Comment by jdcalaz** [comment]
Testeado OK
1. Me loguié
2. Fui a Menú -> ''Admin'' -> ''Mis Actividades''
3. Entré a una Actividad
4. Fui a la pestaña ''Grupos''
5. Veo en el campo de filtro que dice ''Buscar por nombre o por rol'' no dice ''Oficina'' ni ''Estado''
Funciona el filtro. 
![image](https://user-images.githubusercontent.com/48033083/65696775-3acc8c00-e050-11e9-932f-869c1423607a.png)

**Comment by MicaelaTangorra** [comment]
Testeado (SandBox) --> OK
