### ISSUE TITLE
BE: Tipo de Actividad (NO Construccion) - Grupos - Punto de Encuentro esta vacio

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#292]
**Describí el error**
Me logueo como Coordinador:  Edito una Actividad (NO Construccion) --> Grupos - Punto de Encuentro esta vacio

**Para reproducirlo**
Pasos para reproducir el comportamiento:
-.TESTING
-. Me logueo como COORDINADOR
-. Menu - ADMIN - Mis Actividades
-.Selecciono una Actividad (NO Construccion)
-. Voy a la solapa "Grupos"
-. Presiono el boton "Voluntario No Inscripto"
-.Quiero agregar un voluntario: pero en el combo de "Punto de Encuentro" aparece vacio (y "General" hay un/unos Puntos de Encuentro: es requerido) 

**Comportamiento esperando**
-.TESTING
-. Me logueo como COORDINADOR
-. Menu - ADMIN - Mis Actividades
-.Selecciono una Actividad (NO Construccion)
-. Voy a la solapa "Grupos"
-. Presiono el boton "Voluntario No Inscripto"
-. Ingreso un voluntario: lo agrego y presiono "Incluir y Cerrar" (o "Incluir y Agregar Nuevo")

**Capturas de pantalla**
![20181128 - coordinador - grupos - punto de encuentro esta vacio](https://user-images.githubusercontent.com/43036107/49157228-06882200-f2fe-11e8-8225-e0227287ae2d.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: chrome

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by wmarcos** [comment]
@MicaelaTangorra Creo que lo soluciona el arreglo del #298. Verificalo porfa

**Comment by MicaelaTangorra** [comment]
@wmarcos: lo verifique y hay bug en #298 . Verificalo y si es asi, cuando lo actualizen, lo pruebo!

**Comment by MicaelaTangorra** [comment]
@wmarcos lo probe ahora con la actividad "Apoyo Coord 27/11" y me sigue pasando pero lo probe con otra actividad de Apoyo Escolar (como Coordinador) y no pasa. Seguro que esta relacionada con el #298
