### ISSUE TITLE
BE: En el Listado: agregar una columna que diga "Pais"

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#294]
**Describí el error**
En el Listado: agregar una columna que diga "Pais"

**Para reproducirlo**
Pasos para reproducir el comportamiento:

-. TESTING
-. Menu - ADMIN
-. En el Listado "Mis Actividades" y en "Ver Todas" : agregar una columna que diga “Pais” (es por el multi-pais)

**Comportamiento esperando**
Una descripción clara y concisa de que esperabas que pase y no pasó.

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by agustempo** [comment]
Listo para probar en el sandbox!! :)

**Comment by jdcalaz** [comment]
Testeado OK

**Comment by MicaelaTangorra** [comment]
Testeado --> OK

![20190927 - #294 - OK](https://user-images.githubusercontent.com/43036107/65777451-72076f80-e11a-11e9-98a7-0dd471458ffb.png)
