### ISSUE TITLE
Como coordinador no puedo ver los inscriptos a una actividad

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#298]
**Describí el error**
Como coordinador no puedo ver quienes están inscriptos a una actividad que figura en "Mis actividades". Esto pasa con actividades en las que fuí coordinador, pero se asignaron a otro coordinador.

**Para reproducirlo**
Pasos para reproducir el comportamiento:

Pre-requisitos:
- Tener rol Coordinador
- Estar asignado en al menos una actividad como coordinador (pero no haberla creado con ese usuario
)
- (Si se crea con ese usuario SIEMPRE se ve en Mis Actividades no importa si sos coordinador o no)

1. Ir a "Mis actividades"
2. Clickear en la actividad
3. Editar el coordinador y elegir a otra persona que no sea yo.
4. Ver que la actividad sigue listada en "Mis actividades" y si entro no puedo ver los inscriptos.

**Comportamiento esperando**
1. Ir a "Mis actividades"
2. Clickear en la actividad
3. Editar el coordinador y elegir a otra persona que no sea yo.
4. Ver que la actividad no está más listada en "Mis actividades".

**Capturas de pantalla**
![whatsapp image 2018-11-14 at 6 54 11 pm](https://user-images.githubusercontent.com/94343/49451256-8d854080-f7bd-11e8-91b6-3468581dda9f.jpeg)
![whatsapp image 2018-11-14 at 6 51 04 pm](https://user-images.githubusercontent.com/94343/49451260-8eb66d80-f7bd-11e8-91bc-b1edcc59917f.jpeg)

**Contexto adicional**
Lo descubrimos con Sol Mendez cargando actividades para sede oeste de BA

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK
 - Coordinador -> Administrador ==> OK
 - Coordinador -> Coordinador ==> NOK

Pre-requisitos:

-Tener rol Coordinador (micaela_tangorra@yahoo.com.ar)
-Estar asignado en al menos una actividad como coordinador (Por ej: "Apoyo escolar 18/12 (310)"

Pasos:
-. Ir a "Mis actividades"
-. Clickear en la actividad
-.Editar el coordinador y elegir a otra persona que no sea yo y sea Coordinador (Por ej: "Coord mica ta).
-. Ver que la actividad sigue listada en "Mis actividades" y si entro no puedo ver los inscriptos.

![20181218 - como coordinador no puedo ver los inscriptos a una actividad_imagen1](https://user-images.githubusercontent.com/43036107/50160642-9fd0a580-02b8-11e9-9718-627e96295a9a.JPG)
![20181218 - como coordinador no puedo ver los inscriptos a una actividad_imagen 2](https://user-images.githubusercontent.com/43036107/50160643-9fd0a580-02b8-11e9-8ce8-ac40b0572544.JPG)
![20181218 - como coordinador no puedo ver los inscriptos a una actividad_imagen 3](https://user-images.githubusercontent.com/43036107/50160644-9fd0a580-02b8-11e9-9f6c-fcb381c27c47.JPG)
![20181218 - como coordinador no puedo ver los inscriptos a una actividad_imagen 4](https://user-images.githubusercontent.com/43036107/50160645-a0693c00-02b8-11e9-9e2e-9bf0464b8fef.JPG)

Me pasa tambien con la actividad: "oficios 18/12 (298)"

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

Coordinador -> Coordinador ==> NOK

Pre-requisitos:
-Tener rol Coordinador (micaela_tangorra@yahoo.com.ar)
-Estar asignado en al menos una actividad como coordinador (Por ej: "oficios 20/12 (298)"

Pasos:
-. Ir a "Mis actividades"
-. Clickear en la actividad
-.Editar el coordinador y elegir a otra persona que no sea yo y sea Coordinador (Por ej: "Coord mica ta).
-. Ver:
    - la actividad no vuelve a la "Lista de Actividad", permanece en en el,detalle de la actividad (Por ej: "oficios 20/12 (298)" **(imagen_1)**
    - Voy a "Volver al listado" y aparece en "Mis Actividades" (estoy como usuario Coordinador: micaela_tangorra@yahoo.com.ar) **(imagen_2)**
    - Y veo los inscriptos **(imagen_3)**

![20181220 - coordinador - como coordinador no puedo ver los inscriptos a una actividad imagen_1 298](https://user-images.githubusercontent.com/43036107/50289434-99bcff00-0447-11e9-8170-40c873564036.JPG)
![20181220 - coordinador - como coordinador no puedo ver los inscriptos a una actividad imagen_2 298](https://user-images.githubusercontent.com/43036107/50289435-99bcff00-0447-11e9-8446-8e1584c1d972.JPG)
![20181220 - coordinador - como coordinador no puedo ver los inscriptos a una actividad imagen_3 298](https://user-images.githubusercontent.com/43036107/50289436-99bcff00-0447-11e9-943e-095f690e497c.JPG)
