### ISSUE TITLE
FE: Me aparece una frase que NO me tiene que aparecer porq me loguee con "Login Normal"

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#303]
**Describí el error**
Me aparece una frase que NO me tiene que aparecer porq me loguee con "Login Normal" no con una red social

**Para reproducirlo**
Pasos para reproducir el comportamiento:

-. TESTING
-. Me logueo con el Login Normal (SIN red social)  --> Por ej: micaela.tangorra@globallogic.com
-. Voy a: Menu - Perfil
-. Veo en "Contraseña" una frase que NO tiene que aparecer porque me loguee con un "Login Normal" SIN red social. La frase dice:
"Tu cuenta está vinculada a una red social, para cambiar tu contraseña debes cerrar la sesión y hacer click en "Olvidé mi contraseña"."
Lo dice en: Argentina, Brasil, Bolivia

**Comportamiento esperando**
-. TESTING
-. Me logueo con el Login Normal (SIN red social)  --> Por ej: micaela.tangorra@globallogic.com
-. Voy a: Menu - Perfil
-. No aparece la frase porque me loguee con un usuario con "Login Normal"

**Capturas de pantalla**
![20181205 - login normal - perfil bo](https://user-images.githubusercontent.com/43036107/49519881-cb976880-f880-11e8-9330-8107147ef4dc.JPG)
![20181205 - login normal - perfil ar](https://user-images.githubusercontent.com/43036107/49519882-cc2fff00-f880-11e8-9f01-711458a16a22.JPG)
![20181205 - login normal - perfil br](https://user-images.githubusercontent.com/43036107/49519883-cc2fff00-f880-11e8-8652-905f694797b4.JPG)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador : chrome

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by jdcalaz** [comment]
Lo probé 18/7/2019 en la versión de sandbox ''Incorpora-397-panel-de-estadisticas'' y no pude reproducir el error (sale todo bien) cierro el Issue.
