### ISSUE TITLE
Como coordinador/administrador puedo borrar un punto de encuentro que tiene personas anotadas

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#305]
**Describí el error**
Una descripción concisa de cual es el error.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a '...'
2. Clickear en '....'
3. Hacer scroll hasta '....'
4. Ver el error

**Comportamiento esperando**
Una descripción clara y concisa de que esperabas que pase y no pasó.

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK
- ADMINISTRADOR -> OK
- COORDINADOR -> NOK (Issue: #292)

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK

-. Selecciono una Actividad (Por ej: "Copia de apoyo escolar 18/12 (310) --> ahora se llama: " Copia apoyo escolar 19/12) 
-. Agregue un "Punto de Encuentro" (Por ej: "plaza san martin")
-. Guardar
-. Solapa "Grupos": Agrego un "Voluntario No Inscripto" (Por ej: Johan Marchan) con un "Punto de Encuentro" que agregue (Por ej: "plaza san martin") -->  **imagen_1**
-. Presiono el boton "Incluir y Cerrar"
-. Solapa "General": Borro el "Punto de Encuentro" de "plaza san martin" (el tachito esta habilitado) -->  **imagen_2**
-. Solapa "Inscripciones": Busco a Johan Marchan y veo que esta con su "Punto de Encuentro" de "plaza san martin"  -->  **imagen_4**
-. Guardar
-. Vuelvo al Listado
-. Selecciono la misma actividad (Por ej: "Copia de apoyo escolar 18/12 (310) --> ahora se llama: " Copia apoyo escolar 19/12) 
-. Solapa "General": aparece el "Punto de Encuentro" de "plaza san martin" (el tachito esta deshabilitado)  -->  **imagen_3**

![20181219 - coordinador - puedo borrar un punto de encuentro que tiene personas anotadas imagen_1 305](https://user-images.githubusercontent.com/43036107/50224886-cd335700-037d-11e9-8255-e0073dedbe9c.JPG)
![20181219 - coordinador - puedo borrar un punto de encuentro que tiene personas anotadas imagen_2 305](https://user-images.githubusercontent.com/43036107/50224887-cd335700-037d-11e9-840f-753f7e6ebc33.JPG)
![20181219 - coordinador - puedo borrar un punto de encuentro que tiene personas anotadas imagen_3 305](https://user-images.githubusercontent.com/43036107/50224888-cd335700-037d-11e9-8239-b945f9990674.JPG)
![20181219 - coordinador - puedo borrar un punto de encuentro que tiene personas anotadas imagen_4 305](https://user-images.githubusercontent.com/43036107/50224889-cdcbed80-037d-11e9-9da3-2967af9e57c4.JPG)

**Comment by wmarcos** [comment]
Analizando un poco:

En el caso particular de inscribir una persona con cierto punto de encuentro, y después (sin guardar) ir y borrarlo de la pestaña "General" se da un error de interfaz que permite borrar un punto con inscriptos.

Sin embargo, aunque borre un punto y guarde, el punto realmente no se elimina y al recargar la actividad aparece con el botón deshabilitado como debería ser.

¡Podemos vivir con esto! Lo daría como OK
