### ISSUE TITLE
Si hago una búsqueda, al cambiar el presente, asistencia o pago (individual) en un usuario se cambia en otro

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#310]
**Describí el error**
Al buscar un usuario y cambiarle la asistencia, si busco otro y hago lo mismo se modifican los dos.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a Inscripciones
**2. Clickear en búqueda, tipear una búsqueda**
3. Cambiar el estado, asistencia o pago (individual)
4. Borrar la búsqueda.
5. Ver como el usuario que se modificó no quedó modificado, y se modificó otro random.

**Comportamiento esperando**
5. Se modifica correctamente el usuario

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/94343/49674908-4499ea00-fa52-11e8-9687-fc74d039abee.png)

**Información adicional**
Probar el caso donde haya varias páginas

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado OK
  Administrador
     Sin Pago (Asistencia) -> OK
     Con Pago -> OK
 Coordinador
     Sin Pago (Asistencia) -> OK
     Con Pago -> OK
