### ISSUE TITLE
Como Coord/admin al dejar la fecha inicio/fin como está por defecto se produce un error

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#320]
**Describí el error**
Una descripción concisa de cual es el error.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a "Crear actividad nueva"
2. Llenar todos los campos dejando "Fecha de Inicio y Fin de la actividad" sin tocar (por defecto está al día de hoy de las 12 a las 11:59).
3. Clickear en guardar
4. Ver el error en la consola

**Comportamiento esperando**
1. Ir a "Crear actividad nueva"
2. Llenar todos los campos dejando "Fecha de Inicio y Fin de la actividad" sin tocar
3. Clickear en guardar
4. Se guarda correctamente

**Capturas de pantalla**
![captura de pantalla de 2018-12-13 11-11-30](https://user-images.githubusercontent.com/94343/49944039-302d7580-fec8-11e8-8caf-cb8bdffd67e7.png)

**Contexto adicional**
Se puede ver en el request como el controlador de fechas no completa la hora en "Fechainicio" y por eso se da el error. Linea 449 de ActividadesController.

**Comment by wmarcos** [comment]
Se arregla con el #262

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado OK --> (arreglado con el #262)
