### ISSUE TITLE
Cómo admin/coord al filtrar en la tabla de inscripciones se filtra también en grupos.

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#321]
**Describí el error**
Cómo admin/coord al filtrar en la tabla de inscripciones se filtra también en grupos.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a una actividad
2. Clickear en Inscripciones
3. Hacer foco en "Filtrar por:" y escribir algún texto
4. Clickear en Grupos
4. Ver que esa tabla también está filtrada

**Comportamiento esperando**
**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a una actividad
2. Clickear en Inscripciones
3. Hacer foco en "Filtrar por:" y escribir algún texto
4. Clickear en Grupos
4. Ver que esa tabla no está filtrada y se pueden ver todos los integrantes del grupo.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/94343/49949224-e64a8c80-fed3-11e8-8344-2a0dfdbc6029.png)

![image](https://user-images.githubusercontent.com/94343/49949236-ee0a3100-fed3-11e8-891b-3c727de24929.png)

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
TESTING -> Verificado NOK
- ADMINISTRADOR -> OK
- COORDINADOR -> NOK

**Comment by MicaelaTangorra** [comment]
TESTING -> Verificado OK

ADMINISTRADOR -> OK
COORDINADOR -> OK

**Comment by wmarcos** [comment]
Se arregla con #310
