### ISSUE TITLE
Filtro de clase viene con valor por defecto

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#324]
**Describí el error**
El filtro de clase viene con un valor elegir por defecto y no permite ver todas las actividades juntas en el listado.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a Home
2. Clickear en "Quiero saber más" en cualquier categoría
3. Ver como el filtro viene con una clase seteada y no se puede dejar el filtro sin ninguna clase.

**Comportamiento esperando**
3. Ver como el filtro viene con una clase seteada y SE puede dejar el filtro sin ninguna clase.

**Capturas de pantalla**

![captura de pantalla de 2018-12-26 15-51-43](https://user-images.githubusercontent.com/94343/50454420-34c14780-0926-11e9-82af-1709df473005.png)

**Comment by MicaelaTangorra** [comment]
COMENTARIO: 
Cuando pongo en la "Categorias": "Eventos Especiales" (por ej) , me la muestra y presiono el boton "Volver" y me muestra otras vez las "Categorias": Esto te va a pasar con todos los filtros ,no guardan el estado de la búsqueda.

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado OK
