### ISSUE TITLE
Campo localidad opcional

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#325]
**Describí el error**
El campo localidad debería ser opcional a la hora de cargar una actividad, ya que hay países que no tienen/necesitan ese nivel de detalle.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a Crear nueva Actividad
2. Dejar el campo Localidad sin completar
3. Clickear en Guardar
4. Ver el error de validación que obliga a cargar una localidad

**Comportamiento esperando**
4. Debería guardar la actividad sin errores.

**Contexto adicional**
Además tiene que mostrar las actividades en el front end sin errores al no tener una localidad

**Comment by MicaelaTangorra** [comment]
TESTING --> Verificado NOK
   "Comportamiento esperando: Debería guardar la actividad sin errores." --> no pasa.

![20190107 - campo localidad 325 y no cargar punto de encuentro si no es necesario 263](https://user-images.githubusercontent.com/43036107/50775987-81861600-1276-11e9-82fc-fface9fae4d4.JPG)

**Comment by wmarcos** [comment]
Esto se incorpora en PR #327
