### ISSUE TITLE
BE: No aparecen las Provincia (Punto de Encuentro)

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#326]
**Describí el error**
en el Punto de Encuentro: empiezo a cargar por "Punto de Encuentro" y no aparecen las Provincia y por consiguiente, las localidades.

**Para reproducirlo**
Pasos para reproducir el comportamiento:

-. TESTING
-. Me logueo como ADMINISTRADOR
-. Menu: ADMIN - Mis Actividades
-. Creo una actividad: Crear Nueva Actividad
-. Solapa "General": 
    - Empiezo a cargar "Punto de Encuentro": 
        - "Pais": "Argentina" (esta pre-defenido)
        - "Provincia": en el combo no me aparecen las provincias
        - "Localidad":  en el combo no me aparecen las localidades

**Comportamiento esperando**
-. TESTING
-. Me logueo como ADMINISTRADOR
-. Menu: ADMIN - Mis Actividades
-. Creo una actividad: Crear Nueva Actividad
-. Solapa "General": 
    - Empiezo a cargar "Punto de Encuentro": 
        - "Pais": "Argentina" (esta pre-definido)
        - "Provincia": en el combo me aparecen las provincias
        - "Localidad":  en el combo me aparecen las localidades

**Capturas de pantalla**
![20181228 - punto de encuentro - no aparecen las provincias](https://user-images.githubusercontent.com/43036107/50517379-e7141e80-0a8e-11e9-8250-95b979db9c31.jpg)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador : chrome

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
Para reproducirlo:

-. TESTING
-. Me logueo como ADMINISTRADOR
-. Menu: ADMIN - Mis Actividades
-. Creo una actividad: Crear Nueva Actividad
-. Solapa "General":
- Empiezo a cargar "Punto de Encuentro":
    - "Pais": "Argentina" (esta pre-defenido)
    - "Provincia": en el combo NO me aparecen las provincias
    y si cargo en "Ubicacion de la Actividad" - "Pais" --> Argentina (no esta pre definido)
    - ahora si en "Punto de Encuentro" - "Provincia" aparecen las Provincias

**Comment by wmarcos** [comment]
Esto ya está arreglado
