### ISSUE TITLE
[Error] Algunos usuarios inscriptos en Argentina aparecen con país México.

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#334]
**Describí el error**
Algunos usuarios inscriptos en Argentina aparecen con país México. Esto pasa cuando los usuarios llegan desde la integración con Pilote.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Crear un usuario nuevo en Pilote con país "Argentina"
2. Esperar unos minutos
3. Buscar el usuario en la plataforma nueva 
4. Ver que el país se asignó como "México"

**Comportamiento esperando**
El usuario debería aparecer con país "Argentina"

**Contexto adicional**
Reportado por Cami Minor.

**Comment by pilote** [comment]
Fue un problema que se solucionó pero había dejado algunas filas corruptas, se solucionó con esto:

UPDATE
sigp.Persona
SET 
idPais = idPaisResidencia 
WHERE
idPais = 146 AND
idPaisResidencia <> idPais;
