### ISSUE TITLE
[Error] Ver temas de lenguaje inclusivo en la plataforma

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#335]
**Describí el error**
En algunas plantillas se refiere a "Voluntario" cuando debería decir "Voluntario/a", "Voluntarix" o "Voluntarie"

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema
![image](https://user-images.githubusercontent.com/94343/52730428-14af1b80-2f9a-11e9-951c-89ca91b2fcc6.png)

![image](https://user-images.githubusercontent.com/94343/52730382-f9dca700-2f99-11e9-9684-ec7c0e241ece.png)

Reportado por Cami Minor

**Comment by agustempo** [comment]
https://uxdesign.cc/designing-forms-for-gender-diversity-and-inclusion-d8194cf1f51
