### ISSUE TITLE
[Mejora] Borrado soft

### ISSUE THREAD

**Issue by pilote** [techo/voluntariado-eventual#338]
**El pedido está relacionado con un problema, describí**
Al borrar una actividad se borra físicamente de la tabla y se borran sus registros vinculados. Puntos de encuentro, inscripciones, grupos y asignaciones a un grupo.
Esto se vuelve un problema cuando alguien se equivoca y borra una actividad sin querer.

**Describí la solución que te gustaría**
Que al borrar una actividad se borre lógicamente, y no se borren los registros vinculados por si hay que recuperarla.

**Contexto adicional**
Esto se da porque un coordinador borró una actividad con inscriptos que necesitaba por error.

**Comment by wmarcos** [comment]
Testeado y en producción
