### ISSUE TITLE
Error al crear un punto de encuentro con usuario veronica.heredia

### ISSUE THREAD

**Issue by camilaminor** [techo/voluntariado-eventual#342]
**Describí el error**
Conectarse con usuario: veronica.heredia no puede cargar más de un punto de encuentro. 

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. 'loggearse con veronica.heredia@techo.org'
2.  'crear una actividad nueva'
3.  'crear más de un punto de encuentro'
4. Ver que al crear un segundo punto de encuentro, el punto de encuentro no se crea si no que actualiza la información del primero.

**Comportamiento esperando**
Que se cree un segundo punto de encuentro con los datos que se completo en los campos. 

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema

**Contexto adicional**
Editando la misma actividad, ella intento agregar un punto de encuentro nuevo pero le pasaba que no se creaba. Al hacerlo con otro usuario si logramos crear el punto.

**Comment by wmarcos** [comment]
Parece el error es solo en Firefox (versión 65)

![image](https://user-images.githubusercontent.com/94343/54232731-18c35000-44ea-11e9-896c-39cf8948c105.png)

Lo actualiza y ve si sigue pasando

**Comment by wmarcos** [comment]
Era problema de la versión de Firefox
