### ISSUE TITLE
[Mejora] Cerrar Punto de Encuentro en una Actividad activa

### ISSUE THREAD

**Issue by mariansio** [techo/voluntariado-eventual#344]
**El pedido está relacionado con un problema, describí**
Una descripción clara y concisa de cual es el problema. Por ejemplo: "Siempre me frustro cuando ..."
**Si armé una actividad con dos puntos de encuentros, pero tengo demasiada gente en otra, no puedo frenar que la gente se inscriba en uno de los puntos sin cerrar la actividad. 
El problema es no poder limitar la cantidad de gente que se inscribe en un punto de encuentro.**

**Describí la solución que te gustaría**
Una descripción clara y concisa de que te gustaría que pase.
Que yo pudiera o: Ponerle cupos a los puntos de encuentro, o poder cerrar manualmente los puntos de encuentro sin perder la información de los inscriptos a ese punto. 

**Describí alternativas que hayas considerado**
Una descripción clara y concisa de cualquier solución alternativa que hayas considerado.
Cerré la actividad, guardando esa información, y dupliqué la anterior actividad con un punto de encuentro unicamente. 

**Contexto adicional**
Agregá cualquier otro contexto o captura de pantalla que pueda ayudar a entender el pedido.
Caso construcción Abril 2019 BA Sur

**Comment by agustempo** [comment]
Hola @jdcalaz , con [este pull](https://github.com/techo/voluntariado-eventual/pull/504) sumamos esta funcionalidad a la web!

**Comment by jdcalaz** [comment]
Testeado OK
Lo que veo desde Administrador:
![image](https://user-images.githubusercontent.com/48033083/67522979-1fbb5f00-f684-11e9-8f8d-639abd240080.png)


Desde usuario autenticado:
![image](https://user-images.githubusercontent.com/48033083/67522584-5cd32180-f683-11e9-94bf-076ab7862781.png)
