### ISSUE TITLE
[Mejora: Orden por fecha en actividades]

### ISSUE THREAD

**Issue by mariansio** [techo/voluntariado-eventual#347]
**El pedido está relacionado con un problema, describí**
Cuando uno entra a ver las actividades, por ejemplo, charlas informativas, el orden en el que aparecen las actividades es Last Made - First In. Esto limita que las personas puedan visualizar las actividades más cercanas a la fecha actual, y se pierdan, a su vez, entre las actividades de otras sedes. 

**Describí la solución que te gustaría**
Que por default, el orden de las actividades sea de mas cercana en tiempo a menos cercana. 

**Describí alternativas que hayas considerado**
-
**Contexto adicional**
![image](https://user-images.githubusercontent.com/48734564/55100257-370b7d00-50a0-11e9-9d70-74e07071d1ca.png)

**Comment by MicaelaTangorra** [comment]
TESTING --> OK

![20190611 - Mejora Orden por fecha en actividades (OK)](https://user-images.githubusercontent.com/43036107/59276748-488f0a80-8c35-11e9-8182-07e82b749328.JPG)
