### ISSUE TITLE
BE: Grupo - Voluntario No Inscripto - Rol

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#348]
**Describí el error**
Error en BE cuando voy a Inscribir un Voluntario No Inscripto

**Para reproducirlo**
Pasos para reproducir el comportamiento:

-. TESTING
-. Me logueo como ADMINISTRADOR
-. Menu: ADMIN - Mis Actividades
-. Creo una actividad: Crear Nueva Actividad
-. "Guardar"
-. Voy a "Mis Actividades" 
- Selecciono la Actividad que cree recientemente
- Voy a "Grupos" - "Voluntario No Inscripto"
-. Agrego: "Nombre" y cuando voy al "Rol" me aparece el error en rojo (adjunto imagen) 

**Comportamiento esperando**

-. TESTING
-. Me logueo como ADMINISTRADOR
-. Menu: ADMIN - Mis Actividades
-. Creo una actividad: Crear Nueva Actividad
-. "Guardar"
-. Voy a "Mis Actividades" 
- Selecciono la Actividad que cree recientemente
- Voy a "Grupos" - "Voluntario No Inscripto"
-. Agrego: "Nombre" , "Rol", "Punto de Encuentro" 
-. "Incluir y Cerrar"

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: chrome

![20190429 - BE - Grupos - Error](https://user-images.githubusercontent.com/43036107/56973230-d2ca5600-6b42-11e9-8bba-53b40e5763c7.JPG)

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by wmarcos** [comment]
Ya no está más esa funcionalidad
