### ISSUE TITLE
Cuentas de facebook sin email generan error

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#358]
**Describí el error**
Algunas cuentas de facebook no tienen vinculado un email (tienen un número de celular solamente) y no pueden iniciar sesión y no reciben ningún feedback de error.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Conseguir una cuenta de facebook que no tenga email
2. Registrarse con esa cuenta
3. Ver error 500

La única forma de reproducirlo es simulándolo con un test.

**Comportamiento esperando**
Volver a la pantalla de registro con error "la cuenta no tiene vinculado un email"

**Capturas de pantalla**
Error en Sentry
![image](https://user-images.githubusercontent.com/94343/58763704-d29fea80-8534-11e9-9c1d-edba49db4f08.png)

**Comment by MicaelaTangorra** [comment]
El ticket: Cuentas de facebook sin email generan error #358
es el ticket, dice: 
1. Conseguir una cuenta de facebook que no tenga email
Quise hacer una cuenta de facebook SIN mail y me da: 
"Parece que intentas crear una cuenta para una empresa, una organización o un personaje público. En su lugar, crea una Página de Facebook."

Como probaste Marcos vos?

**Comment by wmarcos** [comment]
Desde el código directamente :man_shrugging: 

La única forma sería crear una cuenta solo utilizando un teléfono celular, sin mail. No es muy fácil.

Creo que lo importante es ver que no se rompan nada que ya funcionaba al menos

**Comment by MicaelaTangorra** [comment]
Marcos, 
No es tan facil de probar.
No lo pude hacer :(

Que pongo en este ticket? Lo pongo en "En progreso" de nuevo?

**Comment by wmarcos** [comment]
Tranqui! es un cambio chiquito y lo probé bien. Lo pasamos a producción nomás.

**Comment by MicaelaTangorra** [comment]
TESTING --> OK

Dale Marcos :)

**Comment by wmarcos** [comment]
Sigue pasando
