### ISSUE TITLE
Al buscar coordinadores tarda mucho y a veces da error

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#361]
**Describí el error**
Como coordinador/administrador al crear una actividad es necesario seleccionar un usuario, al escribir el nombre el sistema queda buscando mucho tiempo y a veces se cuelga.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Como Coordinador/Administrador
2. Ir a panel de administración y clickear en "Nueva Activididad"
3. Elegir coordinador
4. Ver que tarda mucho en buscar y a veces da error.

**Comportamiento esperando**
No debería tardar en encontrar el usuario.

**Capturas de pantalla**
Error en Sentry:

![image](https://user-images.githubusercontent.com/94343/58764345-527d8300-853c-11e9-9c37-84d5a7b0afd7.png)

**Comment by wmarcos** [comment]
Solución:
- Agrega un límite de 10 resultados a la búsqueda de personas.
- Empieza a buscar solo después de escribir el 4 caracter y no antes (para no hacer búsqueda sin sentido).

Por ejemplo:
Escribo: mar (no hay resultados)
Escribo. marc (empieza a buscar)

Para probar, estas 4 historias de usuario usan la funcionalidad:
- Búsqueda de coordinador en actividad
- Búsqueda de responsable en punto de encuentro
- Búsqueda de inscripto en grupos
- Búsqueda de no-inscripto en grupos

**Comment by MicaelaTangorra** [comment]
TESTING --> NOK

1) En las funcionalidades que dan (son 4), pongo lo mismo: 
En "Nombre" pongo MORALES..aparecen 10 resultados que NO esta el usuario que me interesa: que es JOAQUIN MORALES y en el scroll no tiene para seguir.

**Comment by wmarcos** [comment]
Miks.

Si, corta los resultados porque hay tantos usuarios que sino se tilda la aplicación :man_shrugging:. De todas maneras tampoco sería útil tener una lista interminable de resultados.

Venimos capacitando para que usen buscando por email, lo cual hace más certera la búsqueda.

No hay una solución fácil a este problema, así que lo vamos a dejar así nomás a menos que encuentres algún error grave.

**Comment by MicaelaTangorra** [comment]
TESTING --> OK

No hay un caso grave (lo q te puse en Comment). Barbaro  lo q me respondiste.
