### ISSUE TITLE
[Mejora] [Devathor Aerolab] Optimizar imágenes

### ISSUE THREAD

**Issue by evaferreira** [techo/voluntariado-eventual#364]
**El pedido está relacionado con un problema, describí**
Performance y peso de las imágenes

**Describí la solución que te gustaría**
Mejora en el peso y formato

**Contexto adicional**
Para desarrollar en la Devathon de Aerolab el día miércoles 5/06/2019

- [ ] Optimizar imágenes

- [ ] Aplicar `picture` donde sea necesario

**Comment by wmarcos** [comment]
Agregado también :100:
