### ISSUE TITLE
[Mejora] [Devathor Aerolab] Constraste hamburger button

### ISSUE THREAD

**Issue by evaferreira** [techo/voluntariado-eventual#365]
**El pedido está relacionado con un problema, describí**
Contraste bajo en botón de menú hamburguesa

**Describí la solución que te gustaría**
Subir la opacidad del blanco para que se vea mejor.

**Contexto adicional**
Para desarrollar en la Devathon de Aerolab el día miércoles 5/06/2019

**Comment by RamiroPinol** [comment]
🤚🏻
