### ISSUE TITLE
[Mejora] [Devathor Aerolab] Agregar font-display

### ISSUE THREAD

**Issue by evaferreira** [techo/voluntariado-eventual#367]
**El pedido está relacionado con un problema, describí**
Fuentes sin instrucción `font-display` 

**Describí la solución que te gustaría**
Agregar`font-display` a las llamadas a Google Fonts

**Contexto adicional**
Para desarrollar en la Devathon de Aerolab el día miércoles 5/06/2019

**Comment by evaferreira** [comment]
On it!

**Comment by wmarcos** [comment]
Agregado. Gracias!!
