### ISSUE TITLE
[Mejora] [Devathor Aerolab] Mejora visual en iPad Portrait

### ISSUE THREAD

**Issue by evaferreira** [techo/voluntariado-eventual#368]
**El pedido está relacionado con un problema, describí**
Visualización incorrecta en iPad Portrait

**Describí la solución que te gustaría**
Agregar las media queries necesarias para que se vea ok

**Contexto adicional**
Para desarrollar en la Devathon de Aerolab el día miércoles 5/06/2019

**Comment by victoraguilerag** [comment]
Yo puedo encargarme de este issue.

**Comment by wmarcos** [comment]
Agregado :+1:
