### ISSUE TITLE
[Mejora] [Devathor Aerolab] Agregar manifest

### ISSUE THREAD

**Issue by evaferreira** [techo/voluntariado-eventual#369]
**El pedido está relacionado con un problema, describí**
El sitio no contiene un `manifest.json`

**Describí la solución que te gustaría**
Agregar un manifest

**Contexto adicional**
Para desarrollar en la Devathon de Aerolab el día miércoles 5/06/2019

**Comment by wmarcos** [comment]
Agregado. Gracias!!
