### ISSUE TITLE
Error al cambiar el rol a un usuario

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#385]
**Describí el error**
Al intentar editar el rol de un usuario no guarda el cambio.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. iniciar como 'Admin'
2. En el panel de Administración clickear en 'Usuarios'
3. Clickear en 'Ver listado'
4. Seleccionar a un usuario con el rol de Coordinador (en este caso creé a Peperino Pomoro)
5. Clickear en Editar
6. Cambiar el Rol de 'Coordinador' a 'usuario_autenticado'
7. Clickear en 'Guardar' 
8. Clickear en 'ver listado' para verificar el cambio de rol
9. Ver que persiste en el rol de 'Coordinador'

**Comportamiento esperando**
Una descripción clara y concisa de que esperabas que pase y no pasó.
1. iniciar como 'Admin'
2. Clickear en 'Usuario'
3. Clickear en 'Ver listado'
4. Seleccionar a un usuario (en este caso Peperino Pomoro)
5. Clickear en Editar
6. Cambiar el Rol de 'Coordinador' a 'usuario_autenticado'
7. Clickear en 'Guardar' 
8. Clickear en 'ver listado' para verificar el cambio de rol
9. Ver que el rol pasó ser 'usuario_autenticado'

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema
5. Antes de editar
![antes](https://user-images.githubusercontent.com/48033083/60299652-a09b6180-9903-11e9-9c94-5849a193723f.png)
7.después de guardar el cambio de rol
![despues_1](https://user-images.githubusercontent.com/48033083/60299698-b7da4f00-9903-11e9-871b-af096e294e2c.png)

![antes_2](https://user-images.githubusercontent.com/48033083/60299706-c0cb2080-9903-11e9-8689-d80c1644c4ad.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: Chrome

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.
Trataba de crear un usuario para testear la exportación de evaluaciones, cuando lo creé le di el rol de 'Coordinador' luego traté de cambiarlo y me topé con este error.

**Comment by wmarcos** [comment]
Era problema de persmisos. Ya está solucionado.
