### ISSUE TITLE
Mail de bienvenida al registrarme en la plataforma

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#394]
**Describí el error**
Al registrarse en la plataforma no llega ningún mail de bienvenida.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a Home
2. Clickear en INGRESAR
3. Clickear en "Quiero ser voluntario"
4. Completar datos de formulario
5. Ver pantalla de Bienvenida
6. Ir a la casilla de mail y ver que no llega ningún mail de bienvenida.

**Comportamiento esperando**
Debería llegar un mail de bienvenida al sitio

**Capturas de pantalla**
Así debería ser el mail de bienvenida
![image](https://user-images.githubusercontent.com/94343/60910252-acb5e600-a256-11e9-854f-f56b501e225d.png)

**Comment by jdcalaz** [comment]
Lo probé y está todo bien, incluidos los links.
