### ISSUE TITLE
Usuarios / Actividades: Buscar en las tablas del panel de administración

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#396]
**Describí el error**
Al usar el campo de búsqueda en las tablas de "Listado de usuarios" o "Todas las actividades" tarda mucho en responder y no hay feedback al usuario mientras está cargando la información.

Además, no se puede buscar por más de un término, por ejemplo: "mixta 2015".

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a ADMIN (como administrador)
2. Clickear en "Todas las actividades" o "Ver listado de usuarios"
3. Escribir algo en el campo de búsqueda
4. Ver que no hay nada que indique que está cargando, ver que al buscar con dos términos no da resultados.

**Comportamiento esperando**
Al buscar despliega un cartel "Cargando", si búsco con más de un término me trae resultados coherentes.

**Capturas de pantalla**
Así debería resolver
![image](https://user-images.githubusercontent.com/94343/60920086-b72faa00-a26d-11e9-9253-077296956c9f.png)

Así se debería ver mientras carga
![image](https://user-images.githubusercontent.com/94343/60920140-dc241d00-a26d-11e9-86b9-2421bc74fc2f.png)

**Contexto adicional**
De tanto usarlo me voy dando cuenta de estas cosas.

**Comment by jdcalaz** [comment]
Lo probé tanto en 'Usuarios' como en 'Actividades' y funcionan bien.
