### ISSUE TITLE
Error al buscar usuario por DNI

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#404]
**Describí el error**
No se pueden buscar usuarios/as por DNI.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a usuarios.
2. Clickear en ver listado.
3. Ir a "filtrar por".
4. Tipear DNI.
5. Ver que no aparecen usuarios.

**Comportamiento esperando**
Debería mostrar el usuario que conincide con ese DNI.

**Capturas de pantalla**
![WhatsApp Image 2019-07-15 at 15 00 27](https://user-images.githubusercontent.com/52931520/61237775-9d7cdf80-a711-11e9-845d-ab33c5b44502.jpeg)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Chrome

**Comment by wmarcos** [comment]
Ya está online la modificación que arregla esto :)
