### ISSUE TITLE
Error al buscar una persona en una actividad por nombre y apellido.

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#406]
**Describí el error**
Al buscar una persona por nombre y apellido no aparecen resulados.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a la actividad.
2. Clickear en "Inscripciones"
3. Ir a "filtrar por"
4. Tipear nombre y apellido.
5. Ver error: no aparecen resultados.

**Comportamiento esperando**
Poder encontrar usuarios usando esos filtros.

**Capturas de pantalla**

![WhatsApp Image 2019-07-17 at 13 55 10](https://user-images.githubusercontent.com/52931520/61395191-30955100-a89b-11e9-9f5c-2c2a27a5cedd.jpeg)
![WhatsApp Image 2019-07-17 at 13 55 10 (1)](https://user-images.githubusercontent.com/52931520/61395195-34c16e80-a89b-11e9-802c-26620a3947b8.jpeg)

**Si estás en una computadora (por favor completá la siguiente información):**
Chrome

**Comment by agustempo** [comment]
cierro esto al probar que ya no se da este error
