### ISSUE TITLE
[Mejora]Poder ver evaluaciones de usuario desde la actividad en la que esta inscripto.

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#407]
**El pedido está relacionado con un problema, describí**
Cuando veo incriptos en una actividad no puedo ver sus evaluaciones desde ahí, sino que tengo que ir al registro de usuarios y buscarlas ahí.

**Describí la solución que te gustaría**
Sería muy útil poder verlas desde la actividad donde se encuentra inscripta la persona y evitar pasos.

**Describí alternativas que hayas considerado**
Clickear sobre la persona y que eso nos muestre últimas inscripciones y evaluaciones sin tener la necesitdad de abrirlo separado.

**Contexto adicional**
Agregaría un botón similar al que dice "ver auditoria" que diga "ver evaluaciones" o "ver perfil"

![WhatsApp Image 2019-07-17 at 14 56 06](https://user-images.githubusercontent.com/52931520/61398756-11022680-a8a3-11e9-9ab2-2f1e12d48968.jpeg)

**Comment by jdcalaz** [comment]
Testeado OK 5/9
Localhost
