### ISSUE TITLE
No llegan todos los mails de evaluaciones a los voluntarios.

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#410]
**Describí el error**
Al enviar los mail de evaluaciones, indica la cantidad de personas a las que se los envia pero al mailtrap llegan solo 2 de 5  y siempre son a las mismas dos cuentas.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
  Prerequisito: tener una actividad con voluntarios inscriptos con asistencia 'Presente' y con la fecha de evaluaciones actual.

1. Loguearse como 'Coordinador'
2. Clickear en 'Admin'
3. Elegir una actividad con el prerequisito antes aclarado.
4. Ir a la pestaña 'Evaluaciones'
5. Clickear el botón 'Enviar evaluaciones'
6. Ver el modal que informa que se los mails se los envia solo a los que figuren como 'PRESENTE'
7. Clikear en 'Enviar'
8. Ver el modal que informa a cuantos voluntarios se les envió el mail y coincide con el número de voluntarios inscriptos en la actividad.
9. Ir a mailtrap y ver que los mails llegan  solo a dos voluntarios (sin importar cuantas veces se repita el procedimiento anterior)
10. (Para verificar) Loguearse como uno de los usuarios a los que no les llegó el mail.
11. Ingresar al menú y hacer click en 'Mis actividades'
12. Seleccionar la actividad en cuestión y ver que no está la opción ''Ver evaluaciones'

**Comportamiento esperando**
9. Ir a mailtrap y ver que los mails llegan  a todos los voluntarios.
10. (Para verificar) Loguearse como uno de los usuarios  inscriptos a la actividad 
.11. Ingresar al menú y hacer click en 'Mis actividades'
12. Seleccionar la actividad en cuestión y ver que está la opción ''Ver evaluaciones'
13. Clickear en 'Ver evaluaciones' y poder llenar la evaluación, luego 'Enviar'

**Capturas de pantalla**
![no recibe mail por evaluacion](https://user-images.githubusercontent.com/48033083/61748111-d4886c00-ad75-11e9-9b94-d84f59a05923.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: Versión 75.0.3770.100 (Build oficial) (64 bits) 
 - Versión de sandbox: Incorpora-397-panel-de-estadisticas.

**Contexto adicional** 
1.Estaba tratando de testear la Issue ''Evaluaciones: Cambiar el texto ¡Gracias por tu opinión! por un flash "Enviado" #211'' pero no pude porque me topé con este problema.
2. La actividad que usé ya la había usado tiempo antes para otras cosas, ya tenía tres voluntarios inscriptos de los cuales 2 habían evaluado tanto a la actividad  como a otros voluntarios. 
Hoy le agregué mas voluntarios y le cambié las fechas varias veces.
Los mails que llegan son a los voluntarios que ya habían evaluado muchos dias antes.

**Comment by wmarcos** [comment]
Jor

No entendí cual era el error y cual era el comportamiento esperado.

**Comment by jdcalaz** [comment]
> Jor
> 
> No entendí cual era el error y cual era el comportamiento esperado.

Posiblemente lo viste cuando no había terminado de completar la Issue (en un momento, mientras lo escribía toqué algo que me había borrado casi todo)
Ahí lo completé

**Comment by jdcalaz** [comment]
> > Jor
> > No entendí cual era el error y cual era el comportamiento esperado.
> 
> Posiblemente lo viste cuando no había terminado de completar la Issue (en un momento, mientras lo escribía toqué algo que me había borrado casi todo)
> Ahí lo completé

En el punto 10. donde puse '(para verificar)'  me refería a verificarlo desde un usuario común inscripto a la actividad, en el punto 9 lo verifiqué desde mailtrap.

**Comment by wmarcos** [comment]
Opa! alto error encontraste :+1:

**Comment by wmarcos** [comment]
Acá veo dos problemas independientes:

1) llega o no el mail.
Este recién lo intenté replicar (en la rama master) y no pude. Pero me di cuenta una cosa: es posible que algunos usuarios tengan configurado en su perfil no recibir notificaciones de la plataforma por mail:

![image](https://user-images.githubusercontent.com/94343/61820557-9c436500-ae2b-11e9-8049-0a6d83fa4f9c.png)

En ese caso, a esos usuarios no le llegaría el mail. Pero al resto de los presentes debería llegarles.

2) permite o no evaluar la actividad.

Esto depende únicamente de que la fecha del día esté entre la fecha de inicio y fin de evaluaciones. (Hoy en día, se haya estado presente o no, se puede evaluar una actividad).

Vamos a centrarnos en el punto 1 para este issue. Fijate si podés reproducir ese bug en otra actividad y avanzamos desde ahí.

**Comment by jdcalaz** [comment]
Acabo de reproducirlo creando una actividad nueva con cuatro voluntarios, llegan solo dos invitaciones a evaluar.
Si se fijan en la lista de correos les llegansolo a ''jdcalaz+test4@gmail.com'' y a ''jdcalaz+test5@gmail.com'' pero no  a ''jdcalaz+test2@gmail.com'' ni a ''jdcalaz+test3@gmail.com''
Debajo de esos dos mails, hay cuatro que me indican que pude inscribirme con cada una de las cuentas.
![image](https://user-images.githubusercontent.com/48033083/61826021-e92d3880-ae37-11e9-919b-419b1536c488.png)

**Comment by jdcalaz** [comment]
> Acabo de reproducirlo creando una actividad nueva con cuatro voluntarios, llegan solo dos invitaciones a evaluar.
> Si se fijan en la lista de correos les llegansolo a ''[jdcalaz+test4@gmail.com](mailto:jdcalaz+test4@gmail.com)'' y a ''[jdcalaz+test5@gmail.com](mailto:jdcalaz+test5@gmail.com)'' pero no a ''[jdcalaz+test2@gmail.com](mailto:jdcalaz+test2@gmail.com)'' ni a ''[jdcalaz+test3@gmail.com](mailto:jdcalaz+test3@gmail.com)''
> Debajo de esos dos mails, hay cuatro que me indican que pude inscribirme con cada una de las cuentas.
> ![image](https://user-images.githubusercontent.com/48033083/61826021-e92d3880-ae37-11e9-919b-419b1536c488

**Comment by jdcalaz** [comment]
La parte 1 del envío de mail era [problema](https://stackoverflow.com/questions/35304197/laravel-email-with-queue-550-error-too-many-emails-per-second) de mailtrap. 

La parte 2  la testeamos y fue arreglado
