### ISSUE TITLE
[Mejora] Claridad en las Actividades y Call to action

### ISSUE THREAD

**Issue by agustempo** [techo/voluntariado-eventual#421]
**ENTORNO**
Me junte con un amigo a tomar una birra, le di mi celular para que se anote a una actividad. desde la pantalla actividades.techo.org/actividades directamente. No entendio que hacer, o como seguir desde ahí. (el bichito de soporte llama la atencion porque te acompaña)

**DOLOR:**
Al momento de navegar desde un navegador se vuelve muy confuso entender que se esta viendo, porque todo parece igual y no se entiende como seguir o donde clickear

**SOLUCIÓN**
1)Que las fotos sean genericas pero por actividad de categoria, para de este modo ser una foto y sobre ella la categoria escrita (deteccion, construccion, colecta, etc)
2) Call to action sobre la actividad ("Incribirme")

**BOCETO**
![WhatsApp Image 2019-08-09 at 8 24 25 PM](https://user-images.githubusercontent.com/11001346/62813905-bd6eab80-bae3-11e9-8e27-fa4d7392a0d0.jpeg)

**OTRAS POSIBLES MEJORAS**
Pienso que si pudiesemos aprovechar el bichito (para dar feedback) para que te lleve a una actividad cercana directamente podriamos evitar factor duda

**Comment by agustempo** [comment]
Qué les parece esto?

@jdcalaz @wmarcos

**Comment by wmarcos** [comment]
Buena investigación!

1)Que las fotos sean genericas pero por actividad de categoria, para de este modo ser una foto y sobre ella la categoria escrita (deteccion, construccion, colecta, etc)

> No entiendo del todo la solución. Hoy en día ya tienen fotos genéricas (por Categoría: Territorio, Formación y Eventos), pero no existe foto por Tipo de actividad (detección, construcción, etc)

2) Call to action sobre la actividad ("Incribirme")

> Parece interesante, habría que hacer una propuesta gráfica para repensar el diseño gráfico ¿tenés algun voluntarie diseñador?

**Comment by agustempo** [comment]
@wmarcos vos en un momento me mostraste una solucion que habias hecho para esto, podras subirte el branch ese? te acordas de lo que hablo?

**Comment by agustempo** [comment]
Listo esto para probar en el branch

incorpora_exportar_evaluadores

![image](https://user-images.githubusercontent.com/11001346/76458929-14aa6680-63ba-11ea-95b7-294120bb3245.png)
