### ISSUE TITLE
Búsqueda por varios términos en los inscriptos a una actividad

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#423]
**El pedido está relacionado con un problema, describí**
Cómo Coordinador al usar el campo de búsqueda rápida sobre la tabla de inscripciones, si se pone más de un término, no trae resultados.

**Describí la solución que te gustaría**
Qué traiga los resultados que coincidan para con el nombre, apellido, email, dni de esos términos

**Describí alternativas que hayas considerado**

**Contexto adicional**
Lo mismo pasaba sobre las tablas de buscar actividad o persona. Se puede copiar de ahí prácticamente.

![image](https://user-images.githubusercontent.com/94343/63716861-5bb97b80-c81d-11e9-8a81-ff6cb860b31c.png)

**Comment by jdcalaz** [comment]
Testeado OK 29/8/2019 

Cierro la Issue
