### ISSUE TITLE
[Mejora] Que los admin puedan eliminar a un usuario.

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#430]
**El pedido está relacionado con un problema, describí**
Los Admin no pueden eliminar voluntarios.

**Describí la solución que te gustaría**
Me parece que sería de utilidad para un Administrador (no así para un Coordinador) que puedan borrar usuarios, en especial para eliminar a los voluntarios que tienen varias cuentas o que no tienen actividad hace años (seguramente no recordarían la contraseña si hace un par de años no participan)

**Contexto adicional**
Agregá cualquier otro contexto o captura de pantalla que pueda ayudar a entender el pedido.

**Comment by jdcalaz** [comment]
Como admin fui a la pestaña ''Personas'' pero no encontré la manera de eliminar a una cuenta. 
¿Es desde otro lado?

**Comment by wmarcos** [comment]
Creo que faltan aplicar los cambios. 

Fijate de hacer esto:

**checkout**: incorpora-430-eliminar-personas-como-administrador

**Procesar los cambios**
php artisan migrate (este tiene cambios en la base de datos)
npm run dev

**Correr el servidor**
php artisan serve

**Comment by jdcalaz** [comment]
Marquitos era eso, no había procesado los cambios
Pude borrar una cuenta, pero al tratar de acceder de vuelta, me manda a verificar, como cuando creo una cuenta desde ''Quiero ser voluntario'' es decir que no borró la cuenta

¿Así debería quedar?
![image](https://user-images.githubusercontent.com/48033083/65818251-40f47100-e1e6-11e9-8bad-11a5f2a95a9c.png)

![image](https://user-images.githubusercontent.com/48033083/65818278-7c8f3b00-e1e6-11e9-986b-92ae883e154b.png)

![image](https://user-images.githubusercontent.com/48033083/65818396-91b89980-e1e7-11e9-8d2f-f12fd19e2712.png)

Y cuando entro como administrador a ver la lista de personas sigue estando ''jdcalaz+test31@gmail.com''

![image](https://user-images.githubusercontent.com/48033083/65818533-9d589000-e1e8-11e9-9fbf-3726434ae6eb.png)

**Comment by agustempo** [comment]
Que bueno que sos probando, no habia probado que pasaba si el usuario borrado era el que volvia a entrar que pasaba, ahora reviso y hago esa prueba yo. gracias

**Comment by agustempo** [comment]
Ahí probé:
- creo un usuario nuevo
- me logueo y activo 
- me deslogueo
- borro usuario desde admin
- confirmo no aparezca en la consulta de personas
- vuelvo a conectarme con usuario nuevo 
- me da error de "usuario no existente"
**resultado OK**

ahora bien, contame como es tu prueba asi la sigo y encuentro como te da ese error y te vuelve a aparece en la consulta de personas

**Comment by jdcalaz** [comment]
@agustempo Buenas
estoy testeandolo, pero sigue el error, ¿en que branch tengo que probarlo? lo hice en ''incorpora-430-eliminar-personas-como-administrador'' ¿las mejoras están en otra?

**Comment by jdcalaz** [comment]
Lo testié varias veces en la rama ''incorpora-430-eliminar-personas-como-administrador''
previamente corrí los comandos ''php artisan migrate'' y  ''npm run dev'' , pero no dan los resultados deseados. 
Antes no los borraba del todo, y me mandaba a verificar la cuenta de correo si entraba desde la cuenta aparentemente borrada, ahora ni siquiera me manda a verificar.
¿Se les ocurre que paso puedo estar salteandome?

**Comment by pilote** [comment]
Quizás te ayude esta página, sobre todo el que es limpiar caché y
configuración. Decime si podés probar esto y sino te lo subo a sandbox, así
ya lo ves de una!

**Comment by jdcalaz** [comment]
@pilote a que página te referís? 
clickié en el link que está al final de tu mensaje y me mostró esto:
![image](https://user-images.githubusercontent.com/48033083/66062604-1a9d4100-e518-11e9-9fa9-e0e0755fe738.png)

**Comment by pilote** [comment]
Perdona, este link
https://tecadmin.net/clear-cache-laravel-5/

**Comment by agustempo** [comment]
Encontré el error cuando lo quise hacer en sandbox, ahi lo estoy viendo, gracias jor :)

**Comment by jdcalaz** [comment]
testeado OK
