### ISSUE TITLE
[Mejora] Verificación de casilla obligatoria

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#431]
**El pedido está relacionado con un problema, describí**
Al registrarse un usuario es necesario que valide su dirección de email para evitar las cuentas "fantasma" o erróneas en el sistema.

**Describí la solución que te gustaría**
Al registrarme como usuario debería llegar un mail de bienvenida con un link que permita verificar la casilla y así activar la cuenta definitivamente.
Lo mismo debería pasar al modificar mi casilla de email.
Si intento entrar al sistema, puedo entrar, pero no puedo ver mi perfil, inscribirme a actividades ni entrar al panel de administración. Solo veo una página con el link para re-enviar el mail de verificación.

**Contexto adicional**
Con esto evitamos tener cuentas fantasmas que terminan en rebotes al hacer campañas de mailing.

**Comment by jdcalaz** [comment]
Testeado OK 4/9/2019.
Sandbox versión: incorpora-350-usuario-puede-cambiar-email

**Comment by jdcalaz** [comment]
Testeado NOK 9/9/2019
Paso s que hice
1. Creé una cuenta
2. Busqué en mailtrap si llegó el mail con el link.
3. Lo confirmé ingresando
4. Fui a actividades y me dejó anotarme a una actividad
5. Pude ver mi perfil
6. Cambié mi cuenta de correo.
7. Voy a Mailtrap y clickeo el link de verificación
8. Surge un error
![Captura de pantalla de 2019-09-09 19-13-46](https://user-images.githubusercontent.com/48033083/64570176-255c2000-d336-11e9-9350-11ac0b76ada3.png)

**Comment by jdcalaz** [comment]
Igual acabo de actualizar la pagina y me lo tomó bien, con la cuenta cambiada

**Comment by jdcalaz** [comment]
Re testeado OK 9/9/2019
Reproduje los mismos pasos que antes y ahora con la mejora de Marcos y salió todo bien.
