### ISSUE TITLE
[Mejora] Barra de novedades

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#437]
**El pedido está relacionado con un problema, describí**
Es difícil comunicar las nuevas funcionalidades de la plataforma a todos los usuarios.

**Describí la solución que te gustaría**
Barra de nuevas funcionalidades de la plataforma con un link para poder enviar a otro lugar con una explicación más completa.

**Contexto adicional**
Algo como esto, pero con novedades ¿solo en el panel de administración? o en ambos sitios?
![image](https://user-images.githubusercontent.com/94343/64699933-3f077f80-d47c-11e9-9b8d-47f8dfff3b4d.png)

**Comment by wmarcos** [comment]
Debería aparece una barra al cargar una novedad en el sistema (no hay forma de cargar por la web, tiene que ser si o si por base de datos, por ahora).

Criterios de test:
- Al clickear en la cruz no tiene que volver a verse hasta que haya un aviso nuevo.
- Si no se carga un link no debería verse el "ver más"

![image](https://user-images.githubusercontent.com/94343/64903277-13f37a80-d68c-11e9-9226-2bc60b1ee5ba.png)

**Comment by jdcalaz** [comment]
Estoy tratando de hacerlos desde el Localhost pero al clickear en el menú ''Admin'' aparece esto:
![Captura de pantalla de 2019-09-16 12-05-28](https://user-images.githubusercontent.com/48033083/64969959-43b4a500-d87b-11e9-89bd-831a091f204a.png)

**Comment by wmarcos** [comment]
Ya lo dejé listo en el sandbox! pruebenlo ahí mejor

**Comment by jdcalaz** [comment]
Testeado OK 
1. Ingresé con un a cuenta de Coordinador
2. Menú ''Admin''
3. Aparece la barra celeste
4. Clickeo el link y lo abre una pestaña
5. Cierro la barra
6. Salgo de sesión, vuelvo a entrar y no está la barra

Nota: No se si es relevante (creo que no) pero  En el caso de iniciar en modo incógnito después de cerrar la barra, si saco el usuario y vuelvo a entrar no aparece la barra, a menos que cierre la ventana del buscador y volvuelva a abrir una ventana en incógnito.

**Comment by wmarcos** [comment]
Es exactamente lo que tiene que pasar :D
