### ISSUE TITLE
[Mejora] Vincular cuentas

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#439]
**El pedido está relacionado con un problema, describí**
Hay usuarixs que están duplicados en la plataforma pero con dos mails distintos, no se puede unificar esos usuarios en uno y hoy en día tenemos su info dividida.

**Describí la solución que te gustaría**
En los casos que sea necesario poder unificar lxs usuarixs y decidir que mail dejar.

**Describí alternativas que hayas considerado**
No se me ocurre como plasmarlo.

**Contexto adicional**
Agregá cualquier otro contexto o captura de pantalla que pueda ayudar a entender el pedido.

**Comment by wmarcos** [comment]
Cambiar el texto mencionando que cuenta se borra y cual queda:
![image](https://user-images.githubusercontent.com/94343/67490466-ab63ca00-f649-11e9-8bd4-375201f3a73c.png)

Arreglar este layout:
![image](https://user-images.githubusercontent.com/94343/67490517-bc144000-f649-11e9-943a-9d391b5e5677.png)

**Comment by jdcalaz** [comment]
TESTEADO
Cuenta que quiero dejar activa:
![image](https://user-images.githubusercontent.com/48033083/67517313-bb46d280-f678-11e9-9592-1661f32e1d5f.png)

Cuenta que quiero recuperar los datos antes de borarla:
![image](https://user-images.githubusercontent.com/48033083/67517996-30ff6e00-f67a-11e9-857a-0913c48ee464.png)

Cuenta que conservo más info de la borrada (Post-fusión):
![image](https://user-images.githubusercontent.com/48033083/67518144-8e93ba80-f67a-11e9-8b4d-7f675dd38ea8.png)

**Comment by wmarcos** [comment]
probaste loguearte con la cuenta que se debería haber eliminado? @jdcalaz

**Comment by wmarcos** [comment]
@jdcalaz hay que verificar estos detalles, y el #505 

> Cambiar el texto mencionando que cuenta se borra y cual queda:
> ![image](https://user-images.githubusercontent.com/94343/67490466-ab63ca00-f649-11e9-8bd4-375201f3a73c.png)
> 
> Arreglar este layout:
> ![image](https://user-images.githubusercontent.com/94343/67490517-bc144000-f649-11e9-943a-9d391b5e5677.png)

**Comment by jdcalaz** [comment]
@wmarcos Si, traté de acceder a la cuenta borrada y no pude.
 **Testeado OK**
### **los datos antes de la fusión: borré jdcalaz+test6@gmail.com y lo pasé a jdcalaz+test3@gmail.com.**
![image](https://user-images.githubusercontent.com/48033083/68241998-79aa1600-ffee-11e9-9a73-ba7099de472c.png)
![image](https://user-images.githubusercontent.com/48033083/68242074-9c3c2f00-ffee-11e9-8738-60d9adf55632.png)
![image](https://user-images.githubusercontent.com/48033083/68242200-e02f3400-ffee-11e9-9187-c1a181418921.png)

![image](https://user-images.githubusercontent.com/48033083/68242314-0ead0f00-ffef-11e9-9b38-0a14b677bcc4.png)

### **Datos post fusión:**
![image](https://user-images.githubusercontent.com/48033083/68242564-87ac6680-ffef-11e9-9317-54dd4f087608.png)
![image](https://user-images.githubusercontent.com/48033083/68242607-9dba2700-ffef-11e9-9ed8-9f8279331d30.png)
![image](https://user-images.githubusercontent.com/48033083/68242636-a7438f00-ffef-11e9-8aa8-9dd7e44eb5bb.png)
