### ISSUE TITLE
[Mejora] Exportar inscripciones para hacer estadísticas

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#456]
**El pedido está relacionado con un problema, describí**
Como Administrador no puedo ver estadísticas de inscripciones por tipo/categoría de actividad.

**Describí la solución que te gustaría**
Una forma de poder exportar las inscripciones para un país/sede/tiempo.

**Describí alternativas que hayas considerado**
Botón de descarga en el panel de estadísticas.

**Contexto adicional**
Para que generales y coordinadores de personas puedan sacar distinto tipo de estadísticas y completar sus documentos de objetivos y resultados.

**Comment by wmarcos** [comment]
@jdcalaz 

Dejo un botón en el panel de estadísticas donde se puede descargar los datos del gráfico para hacer el propio análisis.

![image](https://user-images.githubusercontent.com/94343/64893866-95c4b300-d64e-11e9-8de6-cb81496d8825.png)

**Comment by jdcalaz** [comment]
Testeado OK 
1.Descarga datos bien
2. Desinscribí a un usuario y al descargar los datos nuevamente no está en el documento.
Funciona perfecto

**Comment by wmarcos** [comment]
*Pidieron cambios*, el único que ve accionable es este:

-Se puede exportar en esa base la fecha en la que ocurrió la actividad a la que se inscribió una persona? Esto porque en la BDD se puede ver sólo la fecha en la que se inscribió a la actividad, no en la que ocurrió.

@agustempo 

----------------------------------------------------

-Se pueden exportar los datos de la columna "rol" dentro de la BDD de inscriptos? Esto porque la que le compartiste a Ken tiene esa columna vacía.

Ignorable, andaba mal la funcionalidad de asignar rol. Ya está arreglada.
 
-Se puede exportar a la BDD el puntaje que recibieron los inscriptos en la evaluación de esa actividad puntual?

mm.. no pq cada persona recibe múltiples evaluaciones para cada actividad. Quedarían múltiples registros por persona. Esto podría estar disponible en el Menú

Estadísticas -> Personas -> Evaluaciones

Con un botón de descarga.
 
-Se puede exportar el dato del puntaje global que recibe la actividad?

Lo mismo, la actividad recibe múltiples evaluaciones por cada usuario. Esto podría estar disponible en el Menú:

Estadísticas -> Actividades -> Evaluaciones

Donde hace un promedio de las distintas evaluaciones. Quizás un botón de descarga ahí te permite descargar esos datos y tenerlos a mano.

**Comment by agustempo** [comment]
Listo para probar en Sandbox!

**Comment by jdcalaz** [comment]
Testeado OK 
Entiendo que lo único a testear es la primera pregunta de ser así, está bien resualeto (adjunto imagen)
![image](https://user-images.githubusercontent.com/48033083/66532951-99c9e080-eae7-11e9-9cbb-6619cb58a098.png)
