### ISSUE TITLE
Error para realizar evaluaciones

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#467]
**Describí el error**
Al inscribir, desincribir y volver a inscribir a gente en una actividad a la hora de evaluar las personas me aparecen duplicadas o hasta triplicadas.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a mis actividades
2. Clickear en ver valuaciones
3. Ver el error

**Comportamiento esperando**
Que las personas me aparezcan sólo una vez

**Capturas de pantalla**
![WhatsApp Image 2019-09-26 at 16 42 52](https://user-images.githubusercontent.com/52931520/65719710-bcd2aa00-e07c-11e9-84bd-b4e66bec342f.jpeg)

**Si estás en una computadora (por favor completá la siguiente información):**
 Chrome

**Comment by wmarcos** [comment]
@agustempo esto parece ser que la consulta no toma en cuenta el softdelete (no hace la consulta por el ORM sino de forma directa).

Bien ahí @celinaamar encontrando esto :raised_hands:

**Comment by jdcalaz** [comment]
Testeado OK (pero surgieron otras cosas)

Como lo testié
1. Creé una actividad con 3 voluntarios
2. Sin cambiar la fecha de inicio, desinscribí a 2 usuarios y los volví a inscribir.
3. Cambio la fecha para que conincida con las evaluaciones
4. Envié a las evaluaciones
5. Contesté esas evaluaciones con cada voluntario, en ninguno mostraba duplicados en la lista.


![image](https://user-images.githubusercontent.com/48033083/65806939-7eafb600-e162-11e9-86b1-5dedd04b902d.png)

**Comment by wmarcos** [comment]
¿y que cosas surgieron :open_mouth: ?

**Comment by jdcalaz** [comment]
@wmarcos los errores son dos que los especifiqué acá ''Permanece el botón ''Ver evaluaciones'' después de haber evaluado, o todo lo contrario #477 '' 
Si es engorroso de entender, avisame que lo redacto o te lo explico porque son dos cosas relacionadas que las puse en la misma issue.
