### ISSUE TITLE
Problema con roles, diferencia si se carga por pestaña inscripciones o grupos

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#475]
**Describí el error**
Cómo Coordinador al cargar un rol a una inscripción en la pestaña Inscripciones no lo veo en la pestaña "Grupos" y viceversa.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a una actividad
2. Clickear en Inscripciones
3. Seleccionar una inscripcion
4. Clickear "Asignar Rol"
5. Completar el nombre de rol y enviar
6. Ir a la pestaña "Grupos" y ver que el rol está vacío para ese inscripto.

**Comportamiento esperando**
Una descripción clara y concisa de que esperabas que pase y no pasó.

**Capturas de pantalla**
Pestaña "Inscripciones"
Si aplica, agregá capturas de pantalla para explicar el problema
![image](https://user-images.githubusercontent.com/94343/65803878-5de16380-e156-11e9-9a00-467af699aeef.png)

Pestaña Grupos
![image](https://user-images.githubusercontent.com/94343/65803890-676acb80-e156-11e9-8ff9-774a404f0433.png)

**Contexto adicional**
Lo mismo pasa si se usa el botón "asignar rol" de la pestaña "grupos", se ve en la de grupos pero no en la de inscriptos.

**Comment by jdcalaz** [comment]
Testeado NOK
Sigue teniendo el mismo error, de hecho le puse un rol en la pestaña ''inscripciones'' y otro en la pestaña ''Grupo''

![image](https://user-images.githubusercontent.com/48033083/65808426-73608880-e16a-11e9-9c46-a6a822010b28.png)

![image](https://user-images.githubusercontent.com/48033083/65808436-82473b00-e16a-11e9-8da4-d274ebd7ead7.png)

**Comment by wmarcos** [comment]
@jdcalaz  Lo probaste con esta rama, no?

arregla-475-problema-con-roles

Recordá hacer el:
- php artisan serve
- npm run dev

**Comment by jdcalaz** [comment]
Testeado OK en arregla-475-problema-con-roles

si, era eso Marquitos

![roles 475](https://user-images.githubusercontent.com/48033083/65819127-6a65ca80-e1ef-11e9-8470-226c00964b12.gif)
