### ISSUE TITLE
Permanece el botón ''Ver evaluaciones'' después de haber evaluado, o todo lo contrario

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#477]
**Describí el error**
Cuando quise evaluar una actividad primero no podía acceder desde la plataforma, solo desde el link que mandan por mail.
Probé reproducir el error con una actividad nueva y pude ver el botón ''Ver evaluaciones''  pero despues de evaluar cava vez que voy a ''Mis Actividades'' sigue apareciendo.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
Prerrequisito: tener actividades en etapa de evaluación y como coordinador haber enviado las evaluaciones a los inscriptos.

1. Loguearme como usuario
2. Ir a ''Mis actividades'' 
3-. Buscar el botón '' Ver Evaluaciones'' y no encontrarlo
Busque el link en la casilla de correo y desde ahí si pude acceder y evaluar lo más bien

Quise reproducirlo de otra forma y dió otro resultado. 
Diferencia entre los dos casos:
1° caso: inscribí 3 personas, en etapa de inscripción, las desinscribí y las volví a inscribir. Luego cambié la fecha para poder evaluar.
2° caso: inscribí a 4 personas, luego cambié la fecha para poder evaluar, desinscribí 2 y las volví a inscribir a las mismas personas.

**Comportamiento esperando**
1. Que al momento de querer evaluar se vea el botón ''Ver evaluaciones'' para poder acceder.
2. Que después de evaluar una actividad deje de darme la opción ''Ver Evaluaciones''

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/48033083/65807112-55435a00-e163-11e9-89fd-9be6be11b497.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador Chrome: Versión 77.0.3865.90 (Build oficial) (64 bits)

**Contexto adicional**
Surgió cuando testeaba la issue #467

**Comment by agustempo** [comment]
Voy a subir ahora un pull request que soluciona el #488 y agrega que solo inscritos presentes vean el botón.

Por sobre tu pedido @jdcalaz , si yo les quito el botón al evaluar no pueden seguir evaluando compañeros, hay una opción para agregar cualquier persona que quieras evaluar, con lo cual estaríamos quitando esa funcionalidad.

Te parece entonces que dejemos esto como esta? que opina @wmarcos ?

**Comment by agustempo** [comment]
listo esto en el sandbox por si quere verlo, igual sigamos esa prueba en el #488

**Comment by wmarcos** [comment]
El problema principal del ticket habla sobre no ver el botón "ver evaluaciones" aunque todas las condiciones para evaluar se cumplan. Ese ticket ya está cargado y es el #488.

El segundo tema que menciona este ticket es el comportamiento esperado, es decir, si la persona ya evaluó no se espera que el botón desaparezca en la interfaz. 

Dicho esto, cierro el ticket.
