### ISSUE TITLE
[Mejora] como coordinador ver los datos básicos de un inscripto (datos e inscripciones)

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#478]
**El pedido está relacionado con un problema, describí**
Cómo Coordinador poder ver los datos (básicos e inscripciones) de un inscripto. Pero NO las evaluaciones.

**Describí la solución que te gustaría**
Poder ver el perfil de una persona SIN ver las evaluaciones.

![image](https://user-images.githubusercontent.com/94343/66005425-cd6e9000-e481-11e9-8b0c-f7cc73595833.png)

**Describí alternativas que hayas considerado**
Mostrar solo los datos (email y teléfono) en el detalle de la inscripción.
![image](https://user-images.githubusercontent.com/94343/66005394-ae6ffe00-e481-11e9-8b45-01511e4f96a2.png)

**Contexto adicional**
Agregá cualquier otro contexto o captura de pantalla que pueda ayudar a entender el pedido.

**Comment by agustempo** [comment]
> Hoy con un usuario Coordinador al intentar acceder a "Ver Perfil" da error 404 no encontrado, por falta de permisos.


Podríamos entonces dar como solución que un coordinador SI pueda ver el Perfil del usuario pero que por permisos no pueda ver la solapa "Evaluaciones"? Esto también habría que poder agregarlo desde el menu de la izquierda? cosa de que pueda ver el listado de personas pero sin la posibilidad de agregar personas?

De ser así entonces habría que:
- agregar permisos al visor de la persona para que un coordi pueda solo ver solapas General e Inscripciones
- Verificar que el usuario coordinador NO pueda editar los datos de las personas
- Agregarle permiso de visualización de consulta de todos las personas de la base
- Darle permisos para visualización desde el menu

Contame @wmarcos  si es así para encararlo, o si me quedo algo sin pensar

**Comment by wmarcos** [comment]
Che. Estaba aburrido y enfermo y me puse a hacerlo :man_shrugging: 
Ahí fijate como resolví el tema de los permisos! aprendí que Spatie tiene unas cositas para chequear cositas en los blades.

**Comment by agustempo** [comment]
que zapato, dale revisoooo 🧐

**Comment by agustempo** [comment]
esos @role son una genialidad, que simplicidad de codigo, muuuy bueno

**Comment by wmarcos** [comment]
Pienso que me perdí de algo ¿qué es @ROLE?

**Comment by jdcalaz** [comment]
Testeado OK ''incorpora-478-coordinador-puede-ver-datos-basicos-de-inscripto''
 Como lo testié:
1. Como Coordinador creé una actividad y le agregué algunos voluntarios
2. Voy a inscriptos y clickeo en el reglón donde está el usuario
3. Clickeo en ''Ver perfil''
 Puedo ver el perfil del voluntario pero no así sus evaluaciones. 

![image](https://user-images.githubusercontent.com/48033083/66430652-e8e11a00-e9f0-11e9-9463-54973f710097.png)

![image](https://user-images.githubusercontent.com/48033083/66430758-17f78b80-e9f1-11e9-9409-fabaae600c28.png)
