### ISSUE TITLE
[Admin, Coord] Si cargo más de tres puntos de encuentro , no me deja ver alguno.

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#479]
**Describí el error**
En la lista de puntos de encuentro, solo permite ver hasta tres puntos de encuentro.
 
**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Loguearse como administrador
2. Ir al menú 'admin'
3. Clickear en 'Crear actividad'
4. Crear la actividad con más de tres puntos de encuentro
5. Notar que solo deja ver hasta tres

**Comportamiento esperando**
5. Poder ver todos los puntos de encuentro

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/48033083/66077140-bb4e2980-e535-11e9-9392-cfd7ada9ae60.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador Chrome

**Contexto adicional**
Quizás el rectángulo blanco en el que está la categoría ''Puntos de encuentro'' tiene un tope de filas.
testeado en la rama: incorpora-430-eliminar-personas-como-administrador

**Comment by agustempo** [comment]
Wachin, ahi me fije en mi local, desde el master o el branch "incorpora-430..." y en ambos no tuve problemas, paso print desde el visor, quizas contame si lo podes volver a probar desde el master, o algo que estes haciendo que no me hayas dicho!

![image](https://user-images.githubusercontent.com/11001346/66419560-b5939080-e9da-11e9-8d53-4c2c5c541bfb.png)

**Comment by jdcalaz** [comment]
Testeado OK  Sandbox versión: ''arregla-496-problema-con-confirmacion-por-pago''
![image](https://user-images.githubusercontent.com/48033083/67239025-a245e380-f424-11e9-9cf4-66aca0224346.png)


Pero al incribirme en un momento al ver los puntos de encuentro me figura que son en la misma provincia
![image](https://user-images.githubusercontent.com/48033083/67239078-c43f6600-f424-11e9-8ea1-9fdee6d2fb92.png)

![image](https://user-images.githubusercontent.com/48033083/67239112-e1743480-f424-11e9-9803-d5a68e263800.png)

**Comment by jdcalaz** [comment]
Testeado OK!
Ahora entendí por que era, no es un error. No le den bola a lo último que había escrito el test salió bien.
También lo testié en ''fix-494-visualizacion-error-puntosEncuentro-en-inscripcion''
