### ISSUE TITLE
[Mejora] Verificar una cuenta manualmente

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#480]
**El pedido está relacionado con un problema, describí**
Cómo administrador quiero verificar una cuenta manualmente por si la persona tiene problemas o no logra verificarla a través de su mail.

**Describí la solución que te gustaría**
Un botón en el perfil de la persona que permita verificar la cuenta.

**Contexto adicional**
Varios usuarios indican problemas de verificación de cuenta a pesar de que el sistema parece no tener errores en los envíos, entonces, la mejor solución puede ser que el administrador los verifique directamente.

**Comment by jdcalaz** [comment]
Testeado OK en localhost: incorpora-280-verificar-cuenta-manualmente
1. Creé un usuario
2. Traté de loguearme con el usuario nuevo y me pidió verificación (como correstponde)
3. Volví al admin y accedí al perfirl del usuario nuevo desde la pestaña ''Personas''
4. Clickié en ''Editar'', cambié la posición del Switch y guardé.
5. Probé loguearme con el nuevo usuario y pude, hasta me inscribí en una actividad


![image](https://user-images.githubusercontent.com/48033083/66246276-7965e480-e6e9-11e9-9c5c-9cf9c99e690f.png)
