### ISSUE TITLE
Error en la fecha límite de pago.

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#481]
**Describí el error**
Al crear una actividad con confirmación y pago, al enviarse el mail de pago no aparece la fecha límite puesta en la info general, sino que aparece la fecha límite de inscripciones.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a 'General'
2. Prender switch de  'confirmación por pago.'
3. En "configuración de pago" establecer fecha límite de pago.
4. Al confirmar a un/a voluntario/a se le envía automáticamente un mail.
5. En el mail aparece la fecha límite de inscripción y NO la fecha límite del pago.

**Comportamiento esperando**
Que aparezca la fecha límite de pago.

**Capturas de pantalla**
![WhatsApp Image 2019-10-03 at 16 47 44](https://user-images.githubusercontent.com/52931520/66159121-ba80ca80-e5fd-11e9-8475-cfc21d6be022.jpeg)
![WhatsApp Image 2019-10-03 at 16 48 24](https://user-images.githubusercontent.com/52931520/66159126-bce32480-e5fd-11e9-8b6b-dd1059a4abbf.jpeg)
![WhatsApp Image 2019-10-03 at 16 48 37](https://user-images.githubusercontent.com/52931520/66159132-beace800-e5fd-11e9-945e-8f5c8b8f21b6.jpeg)

**Si estás en una computadora (por favor completá la siguiente información):**
Chrome

**Comment by jdcalaz** [comment]
Testeado OK
1. Como Administrador inscribí a un usuario en una actividad con pago
2. Puse el switch de confirmacion en  ''Confirmado''
3. Llegó el mail para confirmar la donación

![image](https://user-images.githubusercontent.com/48033083/66335817-2c188b80-e912-11e9-8310-98269f306069.png)

![image](https://user-images.githubusercontent.com/48033083/66335866-43f00f80-e912-11e9-9ffe-a7450b428e51.png)
