### ISSUE TITLE
DEFECTO: "Mis actividades" - Evaluaciones: poner un solo dia NO aparece el "Ver Evaluaciones" (período de evaluación activo)

### ISSUE THREAD

**Issue by MicaelaTangorra** [techo/voluntariado-eventual#488]
**Describí el error**
Al ingresar una evaluación que tiene UN DIA no aparece el "Ver Evaluaciones" (período de evaluación activo)

**Para reproducirlo**
Pasos para reproducir el comportamiento:

1- "Mis actividades"
2- Clickear en "Mis actividades" de alguna actividad con período de evaluación activo
3- Si pongo en una actividad la "Fecha de Inicio y Fin de Evaluaciones": 3/10/2019 (que me deberia dejar poner un comentario y/o un puntaje)...NO aparece el boton de "Ver Evaluaciones"
4- Pero:  Si pongo: "Fecha de Inicio y Fin de Evaluaciones": 3/10/2019 a 4/10/2019 veo el boton "Ver Evaluaciones"

**Comportamiento esperando**
Si pongo en una actividad la "Fecha de Inicio y Fin de Evaluaciones": 3/10/2019 APÁRECE el boton de "Ver Evaluaciones" y  Si pongo: "Fecha de Inicio y Fin de Evaluaciones": 3/10/2019 a 4/10/2019 APARECE el boton "Ver Evaluaciones"

**Capturas de pantalla**
Te mando 2 imagenes:

<img width="847" alt="20191003 - #211 - NOK _1" src="https://user-images.githubusercontent.com/43036107/66318249-59087680-e8f1-11e9-830c-b7a980dc6dd1.PNG">

<img width="610" alt="20191003 - #211 - NOK _2" src="https://user-images.githubusercontent.com/43036107/66318250-59087680-e8f1-11e9-8959-7bc47d00fc1d.PNG">

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador [por ejemplo: chrome, explorar, safari]

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo: [por ejemplo: Huawei GW, iPhone6, Samsung J2]
 - Sistema operativo: [por ejemplo: Android4, iOS8.1]
 - Navegador [por ejemplo: navegador del celu, Chrome, Safari]

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by MicaelaTangorra** [comment]
Relacionado con #211

**Comment by agustempo** [comment]
Listo @MicaelaTangorra esto en el sandbox por si queres probarlo, tambien agregue otra funcionalidad para probar:
- solo inscriptos presentes ven el botón
(antes con solo estar inscripto y dentro de fechas te lo mostraba)

**Comment by jdcalaz** [comment]
Testeado OK 
en la imagenes hay dos actividades una con  "Fecha de Inicio y Fin de Evaluaciones" el 8/10/2019 y otra con  "Fecha de Inicio y Fin de Evaluaciones" desde el 8/10/2019 hasta el 9/10/2019
En ambos casos se puede ver el botón ''Ver Evaluaciones'' y se puede evaluar en ambas.

![image](https://user-images.githubusercontent.com/48033083/66425955-2fca1200-e9e7-11e9-871c-00b03f4cc4b7.png)

![image](https://user-images.githubusercontent.com/48033083/66427681-de238680-e9ea-11e9-9e53-dd13de6da4d8.png)
