### ISSUE TITLE
[Refactor] Sacar campo heredados de pilote y limpiar bases

### ISSUE THREAD

**Issue by agustempo** [techo/voluntariado-eventual#492]
Agrego esto a que sea un issue para poder pimponear diferentes campos a tratar y tambien los datos que estas tablas tienen que habria que limpiar.

Por ejemplo, en cuanto a datos:
PERSONA - 3252 registros con mail = ''
de los cuales 1589 tambien tienen '' en nombres y apellidoPaterno

que empiece la limpieza, dale

**Comment by jdcalaz** [comment]
Todavía terminé de testear por completo todas las funciones, pero voy agregando lo que me va apareciendo.

Como admin, no puedo crear una actividad.
 Pasos para reproducir el error:
1. Loguearme como administrador.
2. Ir a menu ''Admin''
3. Clickear en el botón ´Crear Actividad´ (o clickear desde el listado de la izquierda)
4. Ver el error.

![Captura de pantalla de 2019-11-07 15-46-10](https://user-images.githubusercontent.com/48033083/68419178-7e9ad100-0178-11ea-91bc-57e60931e0a2.png)
![Captura de pantalla de 2019-11-07 15-56-48](https://user-images.githubusercontent.com/48033083/68419192-83f81b80-0178-11ea-86c2-52d9fcb6a1ec.png)
![image](https://user-images.githubusercontent.com/48033083/68419375-dd604a80-0178-11ea-8598-2754297832b6.png)

**Comment by jdcalaz** [comment]
Cuando clono una actividad y modifico el nombre de la actividad, después de guardar, no modifica el nombre, a menos que actualice la página o salga y vuelva a entrar.
![image](https://user-images.githubusercontent.com/48033083/68420735-b7887500-017b-11ea-8b47-93635769fb59.png)

**Comment by jdcalaz** [comment]
Me impide asignarle un rol a un usuario.
1. Como administrador ir al menú 'Admin'→'Personas'→'Ver todas'
2. Filtrar a un usuario por e-mail
3. Ingresar a su perfil
4. Clickear en 'Editar'
5. Editar el campo 'Rol'
6. Clickear en 'Guardar'
7. Ver este error
![image](https://user-images.githubusercontent.com/48033083/68425125-308bca80-0184-11ea-96fe-cbe9bdf4e3e6.png)

**Comment by jdcalaz** [comment]
Otro error.
Traté de crear puntos de encuentro pero no me deja más de uno.
Pasos para reproducir el error:
1. Como Administrador, crear una actividad con un punto de encuentro y guardar la actividad.
2. Editar la actividad agregando un punto de encuentro. 
3. Clickear en guardar
4. Ver el error. (editó el punto que habia antes en vez de agregar uno nuevo)

![image](https://user-images.githubusercontent.com/48033083/68707646-e4b89700-0570-11ea-843e-5a76ed1e7053.png)

**Comment by jdcalaz** [comment]
Tratando de crear una actividad nueva como administrador me topé conque no me deja hacerla.
Acá está el screenshot del error

![image](https://user-images.githubusercontent.com/48033083/68897636-d3fd5200-0725-11ea-8355-4a05e4a500fd.png)

**Comment by jdcalaz** [comment]
Olviden todo, problemas resueltos.
Puedo crear actividades.
Puedo crear personas y asignarles un rol.
Puedo crear y  asignar puntos de encuentro.
 Era un problema al cargar la de base de datos.
