### ISSUE TITLE
Error al mostrar puntos de encuentro en la inscripción

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#494]
**Describí el error**
Como usuario al querer inscribirme en una actividad los puntos de encuentro se muestran incorrectamente.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Cargar una nueva actividad.
2. Cargar 2 puntos de encuentro en diferentes provincias
3. Como usuario ir a la actividad a inscribirme
4. Ver que las pronvincias de los puntos de encuentro se muestran incorrectamente.

**Comportamiento esperando**
Que las provincias se vean igual que en la carga de actividad.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/94343/66665466-f8e13f80-ec24-11e9-9747-c4a4f57117d2.png)

**Comment by wmarcos** [comment]
@agustempo Chequiá este cuando puedas

**Comment by jdcalaz** [comment]
Testeado NOK
Lo probé desde el sandbox rama master que está vigente el dia 14-10-2019

![image](https://user-images.githubusercontent.com/48033083/66793393-98c3f500-eed3-11e9-8803-70d756c74920.png)
![image](https://user-images.githubusercontent.com/48033083/66793413-ab3e2e80-eed3-11e9-92aa-63fcb8ecfc05.png)

**Comment by agustempo** [comment]
Hola @jdcalaz , ahi modifique y deje en el sandbox para probar. Va screen de la misma actividad con la que estabas probando vos

![image](https://user-images.githubusercontent.com/11001346/66825546-d69b3a80-ef20-11e9-9edf-c76bb988696f.png)

**Comment by jdcalaz** [comment]
Testeado OK versión Sandbox: fix-494-visualizacion-error-puntosEncuentro-en-inscripcion
Captura de cuando creé los puntos de encuentro:
![image](https://user-images.githubusercontent.com/48033083/66858402-96a77800-ef5f-11e9-92e5-6963d0460e33.png)

Captura de lo que ve el usuario 
![image](https://user-images.githubusercontent.com/48033083/66858475-bd65ae80-ef5f-11e9-9c25-f434feb54a91.png)
