### ISSUE TITLE
Demora envío mail de validación para inscripción en actividad

### ISSUE THREAD

**Issue by fogar-techo** [techo/voluntariado-eventual#500]
**Describí el error**
Al querer inscribirse en una actividad, se pide validar el mail previamente a seguir el proceso de inscripción. Este mail se envía con demoras de 2 días a 1 semana, atrasando el proceso de inscripción y hasta a veces, impidiendo el mismo si no se tiene conocimiento del caso.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a la actividad en cuestión e inscribirse
2. Clickear en Inscribirme
3. Para continuar te pide primero, entres a tu correo y valides el mail enviado.

**Comportamiento esperando**
Que el mail de de validación de correo, para continuar con la inscripción sea inmediato.

**Contexto adicional**
Ejemplos de correo en la fecha que se pidió validación y en la fecha donde recibieron el correo:

facundostyles94@gmail.com solicito validación el viernes 11 de Octubre y recibió el mail el viernes 18 de Octubre

luislopestecho@gmail.com
Miércoles 16 de Octubre solicito validación de mail y sigue sin recibir mail de validación

solgeminiani14@gmail.com Miércoles 16 de Octubre solicito la validación de Mail y el 18 recibió el mail correspondiente al correo.

**Comment by wmarcos** [comment]
@fogar-techo  Ahí estuve revisando los registros del sistema para recolectar evidencia.

Ahí te dejo lo que encontré, pero, en resumen: no parece haber un retraso del sistema, sino más bien malas interpretaciones de la interfaz o quizás mails que los usuarios se pasaron de largo (o llegaron a spam).

Lo dejo de tu lado ahora para que sigas investigando vos, pero todo indica que es una falsa alarma.

Lo cierro por ahora, vos cualquier cosa no dejes de avisarme!

------- Registros ------

Vamos caso por caso

**1) facundostyles94@gmail.com** 

El sistema recibe las solicitudes de email en estas fechas:
[2019-09-11 16:10:05] production.INFO: Mail en cola para facundostyles94@gmail.com con.  
[2019-10-17 20:28:02] production.INFO: Mail en cola para facundostyles94@gmail.com con.  

y envía los emails en estas:
![image](https://user-images.githubusercontent.com/94343/67997540-40128d00-fc33-11e9-8a8a-68cdfba85d59.png)

Que se fije que TIENE que tener un mail del 11 de Octube pq el sistema lo mandó efectivamente.

**2) luislopestecho@gmail.com**
No hay registro de que el sistema reciba un pedido de verificación ni manda un mail. Sospecho que se entiende del todo bien la interfaz y quizás no quedó claro que había que clickear en el botón para que llegue.

**3) solgeminiani14@gmail.com**
El sistema recibe el pedido:
[2019-10-17 15:02:59] production.INFO: Mail en cola para solgeminiani14@gmail.com con.

Y envía el mail a las
![image](https://user-images.githubusercontent.com/94343/67997429-d8f4d880-fc32-11e9-9a19-97e7335fcff4.png)
