### ISSUE TITLE
[Admin]Si borré una cuenta, no puedo volver a usar esa dirección de e-mail para crear otra cuenta.

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#505]
**Describí el error**
Siendo Administrador, si borré una cuenta, no puedo volver a usar esa dirección de e-mail para crear otra cuenta.

**Para reproducirlo**
Pre-requisito: Loguearse con una cuenta de Administrador.
1. Ir a menú 'Admin'
2. Clickear en 'Personas' 
3. Buscar en el filtro a un usuario y borrarlo
4. Clickear en '+ Crear persona'
5. Llenar el campo de Email con la dirección de la cuenta que borramos antes.
6. Clickear en 'Guardar' 
7. Ver el error en el aviso en rojo que dice ''El email ya existe en el sistema'' y no deja guardar los cambios.

**Comportamiento esperando**
Pre-requisito: Loguearse con una cuenta de Administrador.
1. Ir a menú 'Admin'
2. Clickear en 'Personas' 
3. Buscar en el filtro a un usuario y borrarlo
4. Clickear en '+ Crear persona'
5. Llenar el campo de Email con la dirección de la cuenta que borramos antes.
6. Clickear en 'Guardar' 
7. Ver quese creó la cuenta (si es posible con un mensaje que confirme que la cuenta fue creada) y que al buscar la dirección de email, en el filtro de personas, esté asociada a una cuenta y que al acceder como si fuera el usuario.
 
**Capturas de pantalla**
**_Creando la cuenta:_**
![image](https://user-images.githubusercontent.com/48033083/67527746-19ca7b80-f68e-11e9-8304-3d73856637e9.png)

_**Verificando si existe la cuenta con ese email:**_
![image](https://user-images.githubusercontent.com/48033083/67526890-18984f00-f68c-11e9-8dbd-12f268fdf4a6.png)

**_Tratando de loguearme igual, por si mehabía creado la cuenta igual y el bug era por otro lado._**
![image](https://user-images.githubusercontent.com/48033083/67527911-76c63180-f68e-11e9-9426-5d69174a79cb.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador Chrome Versión 77.0.3865.90 (Build oficial) (64 bits)

**Contexto adicional**
Encontré este error mientras trataba de resolver la Issue #436 
Aunque me topé con esto otras veces anteriormente, recién caigo que era una potencial issue.

**Comment by agustempo** [comment]
bárbaro, esto pasa porque al borrar un usuario el mismo se "borra", quedando en base de datos pero no mostrandolo al usuario... voy a modificar la lógica para que en el caso de querer crearlo de nuevo se "cree".

Es más un "revivír" la función porque van a volver a aparecerle las inscripciones y evaluaciones ya que nunca de borraron.

activo función "revivir"

**Comment by wmarcos** [comment]
Claro.

Creo que lo que está pasando en que el login no usa Eloquent y por lo tanto no verifica el borrado lógico.

Hay una [función](https://laravel.com/docs/5.7/eloquent#soft-deleting) de Eloquent para restaurar un registro con borrado lógico 

```
App\Flight::withTrashed()
        ->where('airline_id', 1)
        ->restore();
```

**Comment by agustempo** [comment]
es mas complejo que solo revivir, porque el error da luego de cargar los datos personales del usuario. En tal caso, y solo para casos que el administrador hayan borrado algún usuario y se quiera volver a crear un usuario con el mismo mail, tengo que levantar la información ingresada y compararla contra la ingresada en el formulario para crear un usuario fusionado. 

Toda esta lógica para un caso **muy puntual**, me parece que esto puede quedar para adelante y priorizar otra o sino borrar el usuario de raíz cuando se borre y listo, mas limpia y clara esa lógica. El borrado lógico se pensó para no perder las inscripciones, pero cuántos casos tenemos que suceda que borren usuarios y se quieran tener en cuenta las inscripciones o evaluaciones? Por qué alguien borra un usuario?

**Comment by wmarcos** [comment]
No hace falta fusionar, la pregunta es: ¿restaurar o crear nuevo?

Debería ser posible armar un usuario con un mail que se borró, sino queda una inconsistencia. Es decir, no va a existir un usuario con el mail x, pero al intentar dar de alta un usuario con mail x, el sistema va a decir que existe.

El mínimo creo que sería que la verificación sea con Eloquent y [entienda los borrados lógicos](https://wisdmlabs.com/blog/laravel-soft-delete-unique-validations/). 

`'slug' => "required|unique:post,slug,{$id},id,deleted_at,NULL",`

La funcionalidad ideal sería devolver un "el usuario ya existía y fue borrado ¿restaurar o crear uno nuevo?" pero eso puede ser un poco más costoso de lo que necesitamos. A fines prácticos, si se quiere crear un id nuevo en vez de poner un null en deleted_at, por mi está ok!

**Comment by jdcalaz** [comment]
Testeado NOK
Si borro una cuenta (o la fusiono) y luego quiero usar esa misma cuenta de correo para crear otro usuario de TECHO aparece esto:
![image](https://user-images.githubusercontent.com/48033083/68243951-744eca80-fff2-11e9-9cf8-d6549160370a.png)

**Comment by jdcalaz** [comment]
Testeado OK 
Si borro  un usuario y utilizo la misma cuenta de correo puedo crear otro usuario para la plataforma.
ESto lo pude lograr desde una cuenta ''Administrador'' o sin tener una cuenta.
