### ISSUE TITLE
[Mejora] Si una actividad no tiene punto de encuentro no debería aparecer en el listado.

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#525]
**El pedido está relacionado con un problema, describí**
Como usuario puedo ver actividades en las que no hay un punto de encuentro abrierto, pero no me deja finalizar inscripción.

**Describí la solución que te gustaría**
Que al cerrarse todos los puntos de encuentro no esté listada la actividad.
 
**Describí alternativas que hayas considerado**
Una descripción clara y concisa de cualquier solución alternativa que hayas considerado.

**Contexto adicional**
![image](https://user-images.githubusercontent.com/48033083/69677032-c8445080-1080-11ea-9ab3-5e84bc98b463.png)
![image](https://user-images.githubusercontent.com/48033083/69677070-db572080-1080-11ea-8768-3f0b47e25c79.png)

**Comment by jdcalaz** [comment]
@agustempo Te puedo asignar esta issue?

**Comment by agustempo** [comment]
este issue se resuelve en el ticket de refactor!

**Comment by jdcalaz** [comment]
Testeado ok
