### ISSUE TITLE
Switch de ''Punto de encuentro'' invertido

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#526]
**Describí el error**
El Switch que habilita o deshabilita el punto de encuentro, , por defecto está cerrado, a menos que en el momento de crear la actividad clickée sobre él.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Loguearse como 'Admininstrador' o 'Coordinador'
2. Crear una actividad con un punto de encuentro
3. Como 'usuario_autenticado' inscribirme a esa actividad.
4. Ver el error al no poder inscribirme porque no hay punto de encuentro.

**Comportamiento esperando**
4. Inscribirme con éxito porque de entrada el switch estaba en 'Abierto'. 
 
**Capturas de pantalla**
Desde 'Administrador'
Así está por defecto, en ese estado es cerrado.
![image](https://user-images.githubusercontent.com/48033083/69677979-00e52980-1083-11ea-9a2b-f6632458447b.png)
Como 'usuario_autenticado'
![image](https://user-images.githubusercontent.com/48033083/69679323-9fbf5500-1086-11ea-8ad8-72899d98727c.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: Chrome Versión 78.0.3904.97 (Build oficial) (64 bits)

**Contexto adicional**
1. Surgió mientras testeaba la branch ''incorpora-146-multipaís-por-selección''
2. Está vinculado a la issue #525

**Comment by agustempo** [comment]
con el nuevo metodo de creacion este tk ya estaria solucionado

@jdcalaz
