### ISSUE TITLE
[Mejora] ABM Tipo de actividad

### ISSUE THREAD

**Issue by wmarcos** [techo/voluntariado-eventual#528]
**El pedido está relacionado con un problema, describí**
Cómo administrador quiero poder agregar tipos de actividad

**Describí la solución que te gustaría**
Un ABM de tipos de actividad.

**Contexto adicional**
Cómo parte del lanzamiento a latam

**Comment by jdcalaz** [comment]
Testeado OK
 El error que vi es el mismo que está en el ABM Oficinas

**Comment by agustempo** [comment]
listo, ahi modifique para que vuelva al listado una vez creado el tipo de actividad

no necesita testeo
