### ISSUE TITLE
[Mejora]Tipos de actividad

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#530]
**El pedido está relacionado con un problema, describí**
Hoy en día los tipos de actividad no terminan de reflejar todas las actividades que generamos (por ejemplo no hay opcion de crear actividades de difusión como exposiciones o festivales) y aún conserva actividades viejas(ejemplo: programas de educación y de trabajo) 

**Describí la solución que te gustaría**
Que haya más amplitud de actividades y que saquemos aquellas que hoy no están activas y para que se asemejen a las actividades que hay hoy en día y la oferta sea clara.

**Describí alternativas que hayas considerado**
Quitar los tipos de actividad, y que esten especificados en la descripción, o que exista la opción "otros" por si la actividad no se engloba en niguna de las que aparezcan.

**Comment by agustempo** [comment]
@celinaamar esto ya quedo en produccion desde el menu del costado!

![image](https://user-images.githubusercontent.com/11001346/74859541-fce54280-5325-11ea-9396-a108da364e6e.png)
