### ISSUE TITLE
[Mejora] Que el/la admin pueda ver que personas completaron la evaluación

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#540]
**El pedido está relacionado con un problema, describí**
Cuesta mucho que las personas evaluen las actividades. Hoy en día no sabemos que personas completaron las evaluaciones y cuales no, por lo que es difícil saber a que público apuntar a la hora de insistir, y entender que es lo que no está llegando.

**Describí la solución que te gustaría**
Poder ver que personas ya completaron la evaluación de la construcción en general y evaluaron a sus compañeros/as.
A la hora de hacer esto me parece importante que sigamos manteniendo la confidencialidad de las evaluaciones, es decir, no saber quien evaluó a quién. Ya que muchas veces estas herramientas son usadas por voluntarios/as y es info muy sensible la que se toca como para que llegue a filtrarse que dice una persona de la otra.

**Describí alternativas que hayas considerado**
Pensaba en dos opciones:
1. Que en la solapa de inscriptos aparezca un campo más por inscripto y que corresponda a si esa persona realizó las evaluaciones o no.
2. Que en la solapa evaluaciones, así como podemos descargar la evaluación de la construcción en gral y de las personas, podamos descargar un listado de las personas que completaron la evaluación de la construcción en gral y de sus compañeros/as (quizás discriminado, ya que muchas veces se olvidan de hacer una o la otra).

**Comment by agustempo** [comment]
Listo para probar en el branch:
incorpora_exportar_evaluadores

@jdcalaz

**Comment by agustempo** [comment]
Hola @celinaamar esto ya esta para que lo veas desde produccion! si podes verlo y avisarme seria clave! gracias.. en estadisticas-generales-evaluaciones-Descargar Evaluadores

![image](https://user-images.githubusercontent.com/11001346/78924843-dbc0e880-7a70-11ea-9aa5-97ddad338132.png)

**Comment by agustempo** [comment]
y @celinaamar esto fijate que ya lo tenes disponible :)

**Comment by celinaamar** [comment]
Agus ahí lo probé y buenísimo esto, me re sirveee!!
Mil gracias!
