### ISSUE TITLE
Errores de traducción

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#543]
1) Creando una actividad
![image](https://user-images.githubusercontent.com/48033083/72378691-a2d2db00-36f0-11ea-903b-aec5084f8a7d.png)
 2) Filtrando actividades en frontend
![image](https://user-images.githubusercontent.com/48033083/72379229-c8141900-36f1-11ea-9e70-59a7e2e45fcb.png)

3) Al inscribirme en una actividad desde front
![image](https://user-images.githubusercontent.com/48033083/72382303-be8daf80-36f7-11ea-96d2-0b0bd9eb26cd.png)

**Comment by jdcalaz** [comment]
En la aclaración de las fechas mal ingresadas al crear una actividad
![image](https://user-images.githubusercontent.com/48033083/72385660-bedd7900-36fe-11ea-9135-17205b277524.png)

**Comment by jdcalaz** [comment]
en el mail de confirmación de una inscripción
![image](https://user-images.githubusercontent.com/48033083/72385891-298eb480-36ff-11ea-94ac-501760afd725.png)

**Comment by jdcalaz** [comment]
'Carta compromiso voluntariado' está solo en español

**Comment by jdcalaz** [comment]
Esta imagen en realidad la saqué del mail de evaluaciones en español pero igual es algo a corregir
 ![image](https://user-images.githubusercontent.com/48033083/72388869-cb190480-3705-11ea-9645-aca7e8ce6ec9.png)

**Comment by agustempo** [comment]
Puntos 1, 2, 3, 4 y 6 te sale porque te falto correr esto:

`php artisan vue-i18n:generate`

sobre la carta de voluntario, dejemosla en español que seguro eso lo tiene que traducir alguien del bien! jajaj

**Comment by jdcalaz** [comment]
Hice pull, migrate npm y serve del refactor. queriendo hacer una cuenta nueva con desde ''Quiero ser voluntario'' encontré dos errores que dicen ''frontend.loquesea'' .
![image](https://user-images.githubusercontent.com/48033083/72557778-2e2ea680-3880-11ea-8afe-c666cfcf926c.png)

**Comment by jdcalaz** [comment]
> Puntos 1, 2, 3, 4 y 6 te sale porque te falto correr esto:
> 
> `php artisan vue-i18n:generate`
> 
> sobre la carta de voluntario, dejemosla en español que seguro eso lo tiene que traducir alguien del bien! jajaj

ESto lo hiciste en ''refactor carga actividades'' o abriste una nueva rama?  ese comando no puedo usarlo
