### ISSUE TITLE
Asignación de coordinador

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#544]
Asignando un coordinador de actividad no me deja cambiar el que viene por defecto.
![image](https://user-images.githubusercontent.com/48033083/72380280-cc413600-36f3-11ea-81e7-cac9353b3624.png)

**Comment by agustempo** [comment]
hola @wmarcos estoy medio perdido aca
de consola tengo este error
![image](https://user-images.githubusercontent.com/11001346/72451788-4082e480-379b-11ea-9409-3b3f24df7a95.png)

y el route que llama a ese actividadesPolicy es
`    Route::post('/ajax/actividades/{actividad}/accesos/{persona}', 'backoffice\ActividadesController@guardarCoordinador')->middleware('can:ver,App\Actividad,id');
`

me das una punta de como ver este error?

**Comment by agustempo** [comment]
listoooo @jdcalaz

**Comment by jdcalaz** [comment]
@agustempo 
Testeado ok
simplemente cambié el coordinador que viene por defecto y no tuve problemas 
Genial agus!
