### ISSUE TITLE
[Confirmación de cuenta] Permite crear contraseña inválida pero no cambiarla.

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#551]
@agustempo @wmarcos 
### **Si quieren ver las capturas del problema vayan al punto 11, es al final de todo** el resto es el procedimiento que hice.

Como ''Admin'' quiero crear una persona  
1. Cargo todos los datos personales. **(no activo switch de verificación)**. OK
2. En otra ventana abro el modal de logueo. OK
3. Escribo el email y hago click en ''Olvidé mi contraseña''. OK
4. En la nueva página vuelvo a escribir mi email y clickeo en ''Enviar''. OK
![Captura de pantalla de 2020-01-20 21-25-06](https://user-images.githubusercontent.com/48033083/72765479-61986a80-3bcb-11ea-931e-1af1192080cd.png)
5. Me llega el mail a Telescope. OK
6. Clickeo en ''Establecer nueva contraseña''. OK
7. Completo email correspondiente e invento una contraseña  mas corta de lo debido **(6 caracteres y me deja crearla)**. OK
8. Automaticamente inicia sesión.
9. Ingreso a ''Perfil'' 
![Captura de pantalla de 2020-01-20 21-34-58](https://user-images.githubusercontent.com/48033083/72765756-c2747280-3bcc-11ea-8eeb-80d791cb4491.png)
Debo clickear si o si en ''Hacé click para solicitar otro'' para verificar **(no me había llegado ningún mail por defecto)** 
10. Al llegar mail clickeo en ''Verificar email''
![Captura de pantalla de 2020-01-20 21-39-12](https://user-images.githubusercontent.com/48033083/72765880-63fbc400-3bcd-11ea-87ae-41fe48940fd8.png)
 11. Pongo la  ''constraseña actual''  (la de 6 dígitos)
reemplazo por una de 8 y... 
¡TARÁN! No me permite cambiarla porque la actual es muy corta

![Captura de pantalla de 2020-01-20 21-09-01](https://user-images.githubusercontent.com/48033083/72765072-6825e280-3bc9-11ea-830d-6fb204374e23.png)

![Captura de pantalla de 2020-01-20 21-51-03](https://user-images.githubusercontent.com/48033083/72766514-049eb380-3bcf-11ea-94df-22e40848a133.png)

![Captura de pantalla de 2020-01-20 21-53-45](https://user-images.githubusercontent.com/48033083/72766600-5f380f80-3bcf-11ea-98d9-0a4b301a2db4.png)

![Captura de pantalla de 2020-01-20 21-55-16](https://user-images.githubusercontent.com/48033083/72766661-95758f00-3bcf-11ea-9dfd-d54d3a922639.png)

**Comment by jdcalaz** [comment]
@agustempo @wmarcos 
### **Dato adicional:**
puedo iniciar sesión con la contraseña inválida de 6 dígitos lo más bien. lo único en lo que afecta es que no me permite cambiar la contraseña

**Comment by agustempo** [comment]
listo esto en el brach del refactor

**Comment by jdcalaz** [comment]
Testeado OK
Reproduje cada paso y salió como era esperado
