### ISSUE TITLE
En pestaña ''Grupos'' no puedo ver a todos los inscriptos.

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#553]
@wmarcos @agustempo 
Inscribí a dos voluntarios desde backend y a uno desde frontend, este último no figura en el la pestña ''Grupos'' pero si en ''Inscripciones''
Al inscripto que no aparece  lo inscribí en otro punto de encuentro.
![image](https://user-images.githubusercontent.com/48033083/73295820-2b6c7380-41e7-11ea-9cf7-d143dbb66379.png)

![image](https://user-images.githubusercontent.com/48033083/73296403-6a4ef900-41e8-11ea-8669-6840d57e63f4.png)

![image](https://user-images.githubusercontent.com/48033083/73295942-6c648800-41e7-11ea-80a3-8a4a19d765e5.png)

**Comment by jdcalaz** [comment]
Testeado OK
Copié el link y no estaba el null sino que funcionó perfecto.

**Comment by agustempo** [comment]
con el nuevo metodo de creacion este tk ya estaria solucionado

@jdcalaz
