### ISSUE TITLE
Traducciones segunda parte.

### ISSUE THREAD

**Issue by jdcalaz** [techo/voluntariado-eventual#554]
1. En el filtro de actividades.
![image](https://user-images.githubusercontent.com/48033083/73794130-7efe3480-4786-11ea-94bc-de6b08032c16.png)

2. En el mail por registro  el asunto lo deja en español.
![image](https://user-images.githubusercontent.com/48033083/73794148-91786e00-4786-11ea-8e7d-b1541e28c582.png)

3. Es cuando vas a crear una cuenta en el cambio de contraseña, en el cambio de contraseña.
![image](https://user-images.githubusercontent.com/48033083/73794193-a8b75b80-4786-11ea-9fd5-9aab8507cc58.png)

**Comment by agustempo** [comment]
Listo para probar en el branch:
incorpora_arreglos_trad

@jdcalaz
