### ISSUE TITLE
Importar desde excel

### ISSUE THREAD

**Issue by edu-lopez** [techo/voluntariado-eventual#564]
**Describí el error**
Al importar inscriptos desde excel no importa los datos de la columna "Rol"

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a una actividad
2. Clickear en 'Inscripciones'
3. Click en "Importar desde excel"
4. Selecionar el archivo (template con los datos de la cc a importar)
5. Click en Confirmar
6. Ver el error

**Comportamiento esperando**
Al ingresar a los inscriptos de la Actividad deben aparecer completas las columnas de:
DNI/Pasaporte | Nombre | Apellido | Grupo | Rol | Asistencia
sin embargo la columna de rol aparece vacía

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/61237106/76879184-a3a0fe00-6854-11ea-97f4-54fde1b97a4b.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador Microsoft Edge  Versión 80.0.361.66

**Contexto adicional**
Toda otra cosa que ayude a explicar lo que pasó.

**Comment by agustempo** [comment]
Hola edu, podras enviarme el archivo que estas subiendo? Saludos!

**Comment by edu-lopez** [comment]
[ccoctubre2018ap.xlsx](https://github.com/techo/voluntariado-eventual/files/4344878/ccoctubre2018ap.xlsx)

**Comment by agustempo** [comment]
Hola Edu, acabo de subir a produccion la correccion de este error.

Te pido que vuelvas a cargar el excel con los inscriptos, pero que previo a estos borres todas las inscripciones, para probar que carga de una todos los datos, podrás hacerlo? me avisas cualquier cosa?

Gracis!

**Comment by edu-lopez** [comment]
Pude hacerlo y esta vez sin inconvenientes ¡Gracias!
