### ISSUE TITLE
2 o más personas puedan coordinar una actividad

### ISSUE THREAD

**Issue by agustempo** [techo/voluntariado-eventual#570]
La idea es que las actividades puedan tener mas de un coordinador y que estos manejen las mismas funcionalidades que cuando era solo uno

**Comment by agustempo** [comment]
@jdcalaz ya te dejo esto por acá por si encontras algun error!! 

el cambio esta en la branch incorpora_multiples_coordinadores

**Comment by jdcalaz** [comment]
He vuelto y en forma de fichas
En cuanto a agregar 2 o más presonas para coordinar una actividad salió todo OK, peeeero encontré este bug: 
Al crear una actividad en numero de vacantes es puede ser negativo (había pasado antes)
![image](https://user-images.githubusercontent.com/48033083/81024163-f2c4e180-8e48-11ea-8108-96fe8dab61e9.png)
Como coordinador, al inscribir voluntaries no reacciona el botón inscribir ni tampoco puedo sacar el modal clickeando la ''X'' (supuse que era porque tenía vacantes negativas, pero no porque cambié las vacantes a positivas y sigue el problema) me obliga a actualizar la página.
![image](https://user-images.githubusercontent.com/48033083/81024248-43d4d580-8e49-11ea-89dd-093951b056d1.png)

**Comment by agustempo** [comment]
Esto se paso a prod aprovechando que no hay mucha creacion de actividades.

En el modulo de Admin se ve
![image](https://user-images.githubusercontent.com/11001346/85615540-c7819600-b632-11ea-9129-18e3147db15d.png)

y al momento de incribirse
![image](https://user-images.githubusercontent.com/11001346/85615300-68238600-b632-11ea-8adf-2eb357696b4a.png)

habria que chequear si empiezan a ser muchos coordinadores no mostrarlos
