### ISSUE TITLE
[Mejora] Agregar la opción de "otra" en tipos de actividad.

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#576]
**El pedido está relacionado con un problema, describí**
Al armar una actividad luego de elegir "Categoría" tenemos que elegir "Tipo" de actividad, muchas veces la actividad a realizar no se encuentra entre los tipos que tenemos actualmente (Ejemplos: campañas específicas, cine debates, escuelas de voluntariado, etc). 

**Describí la solución que te gustaría**
Sería bueno tener una opción que sea "otra" para poder aplicarla cuando no encontramos la actividad que queremos.

**Describí alternativas que hayas considerado**
En la sección "Tipo" que podemos completar una vez que completamos como se categoriza la actividad(Eventos especiales, Actividades en Asentamientos y Actividades de oficina y formación) agregar la opción "otra".

**Comment by agustempo** [comment]
Hola Celi, podes vos misma crear los tipos de actividad que quieras en el menu de la izquierda

![image](https://user-images.githubusercontent.com/11001346/80231344-a1874780-8629-11ea-826e-7a824e13b8d0.png)
