### ISSUE TITLE
Cambiar el asunto del mail que avisa el/la usuario/a la cancelación de una actividad.

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#577]
**Describí el error**
Si el/la admin/coord elimina una actividad y hay inscriptos/as en la misma, estos/as reciben un mail que les avisa que dicha actividad fue suspendida. El contenido del mail esta ok, pero el asunto del mismo no.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a una actividad con inscriptos/as.
2. En la solapa "General" clickear en "Borrar"
3. Ver el error:  Automaticamente le llega un mail a los/as inscriptos/as con el siguiente asunto "email.activity_cancel_title (nombre de la actividad)"

**Comportamiento esperando**
Que el asunto del mail sea otro, ejemplo: Cancelación de actividad o cancelación de x actividad.

**Capturas de pantalla**
![WhatsApp Image 2020-04-20 at 16 19 20](https://user-images.githubusercontent.com/52931520/79791311-7a77ff80-8323-11ea-9d43-601ceb8845e2.jpeg)

**Si estás en una computadora (por favor completá la siguiente información):**
Chrome

**Comment by agustempo** [comment]
Listo Celi, ahi vi este tema, la semana que viene lo subo a prod!

Gracias por avisar!

**Comment by agustempo** [comment]
Listo en Produccion
