### ISSUE TITLE
Error en texto.

### ISSUE THREAD

**Issue by celinaamar** [techo/voluntariado-eventual#578]
**Describí el error**
Hoy en día al abrirse la página de actividades podemos ver un cartel de "Suspención de actividades", cambiarlo por "Suspensión de actividades".

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ingresar a la página.
2. Ver el error.

**Capturas de pantalla**
![WhatsApp Image 2020-04-20 at 16 28 36 (1)](https://user-images.githubusercontent.com/52931520/79791989-8ca66d80-8324-11ea-9f43-67726b1d1e3d.jpeg)

**Si estás en una computadora (por favor completá la siguiente información):**
Chrome

NO SE SI ESTE  APLICA CON LOS NUEVOS CAMBIOS QUE VAN A APLICAR EN EL MENSAJE, PERO POR LAS DUDAS.

**Comment by agustempo** [comment]
Celi, con el cambio que subi el jueves este error se supera

![image](https://user-images.githubusercontent.com/11001346/80231219-76045d00-8629-11ea-8ea2-5d2b98ddfd4d.png)
