### ISSUE TITLE
No carga "Mi Evaluación"

### ISSUE THREAD

**Issue by Erickdez** [techo/voluntariado-eventual#580]
**Describí el error**
Haciendo la prueba para realizar la evaluación de una actividad, no me carga la pestaña, se queda en blanco y no muestra ningún contenido.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a la parte de Listado de Actividades
2. Clickear en la esquina arriba derecha
3. Clickear en "Mi Evaluación"
4. Ver el error

**Comportamiento esperando**
Entrar a un espacio donde vería el listado de actividades que ya han pasado y tienen o tuvieron una evaluación. Que además me permitiría completarla, sin necesidad de depender de la enviada a mi correo.

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/46615121/80521946-0eac1d00-8949-11ea-822a-57ce6f8765c2.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: Chrome

**Comment by agustempo** [comment]
Listo Erick, el problema se daba porque al ser vos un usario nuevo no tenias evaluaciones y daba error. Ahora te da un mensaje de "no tenes suficientes evaluaciones"
