### ISSUE TITLE
[Mejora] Metodo de Pago Genérico

### ISSUE THREAD

**Issue by agustempo** [techo/voluntariado-eventual#581]
**PROBLEMA**
Cada país tiene su propio metodo de pago y el sistema esta solo armado para Argentina y PayU. 

**Describí la solución que te gustaría**
Que dentro de la actividad exista la posibilidad de poner un link de pago que te lleve a la plataforma de pago definida por el creador de la actividad

**Comment by agustempo** [comment]
Para solucionar esto se creo el apartado "link de pago" que se muestra una vez seleccionada la confirmación de Pago

![image](https://user-images.githubusercontent.com/11001346/81003723-b336cf00-8e21-11ea-9332-2511f94e1a21.png)


el mismo luego, para el voluntario se muestra así, dandole click abre una nueva pestaña con el link en cuestión.
![image](https://user-images.githubusercontent.com/11001346/81004507-e594fc00-8e22-11ea-9343-02e7e5a91a66.png)


Con esto ya pueden probar actividades con confirmación de pago en todos los paises.
Qué les parece? @techo/usuariosactividades

**Comment by jdcalaz** [comment]
Oh siiiiiiii 😍💗

**Comment by agustempo** [comment]
@laurapaolapina dice:

`
```
Aguss, que bueno lo del pago. Habrá forma que lo que se habilite allí sea un form? 
en el caso de Venezuela así es que llevamos los pagos te muestro acá   https://docs.google.com/forms/d/e/1FAIpQLScNiUBVzpmPfvF8GkDjdVAq-Wo4j8UnBDLRwlpiLNaPKPiIRw/viewform 
porque no tenemos plataforma. 

Lo otro que me quedó faltando fue lo de enviar evaluaciones y poder exportar, 
te adelanto que esa es mi duda para el espacio de hoy y sentirme medio graduada 
en esta primera fase jaja. 

AbRazoooo! 
```

yo respondo:
1) el formulario de pago para poner en ese campo que habilite es para **Realizar el Pago**. En caso de querer mandar un formulario para cargar ese pago como realizado podrian poner el form que me pasas en la descripción de la Actividad

2) que GENIAL que ya estes!!
 **Arriba esas pruebas** :1st_place_medal: 
`

**Comment by agustempo** [comment]
Listo en Produccion
