### ISSUE TITLE
Cambiar a lenguaje inclusivo los mensajes de confirmación y bienvenida

### ISSUE THREAD

**Issue by FlorenciaPittaro** [techo/voluntariado-eventual#582]
Cambiar a lenguaje inclusivo los mensajes de confirmación y bienvenida
![image](https://user-images.githubusercontent.com/63819834/81951438-88940580-95db-11ea-9ffd-890940b887c4.png)

![image](https://user-images.githubusercontent.com/63819834/81951549-aa8d8800-95db-11ea-9b6c-7d7df1a49234.png)

Cambiar por: 
1- Te damos la bienvenida 
2- Estas en proceso de registro en nuestra plataforma, solo falta verificar el mail

En la segunda imagen: 
El ultimo punto: 
1- Evaluar la actividad en la que participaste y a las personas que te acompañaron (o compañeros y compañeras)

![image](https://user-images.githubusercontent.com/63819834/81952079-6484f400-95dc-11ea-994e-369b104a0470.png)
En vez de estas confirmado: 
- Confirmación para participar en..
- Te enviamos tu confirmación para participar... 

![image](https://user-images.githubusercontent.com/63819834/81952400-cfcec600-95dc-11ea-9025-38e391c0193b.png)

En vez de mensaje del coordinador - Mensaje de la coordinación 
 

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador : Chrome

**Smartphone (completá la siguiente informaicón):**
 - Dispositivo:  iPhone6, Samsung J2]

**Comment by agustempo** [comment]
Genial todo esto Flor, ya lo estuve viendo, lo subo la semana próxima a Producción

**Comment by agustempo** [comment]
Listo en Produccion
