### ISSUE TITLE
[Mejora] Punto de encuentro

### ISSUE THREAD

**Issue by Danielfermin31** [techo/voluntariado-eventual#584]
**El pedido está relacionado con un problema, describí**

Hola, el problema es básicamente que a la hora de crear una nueva actividad el sistemas pide, correctamente, un punto de encuentro, pero desde Venezuela creamos una actividad Virtual y el punto de encuentro es Zoom, entonces cuando una persona se inscribe, así haya pagado o no va a poder ver el link de la sala de Zoom cosas que no creemos conveniente, aparte que se tiene que poner obligatoriamente provincia y localidad, cosas que no viene al caso al ser una actividad virtual.

**Describí la solución que te gustaría**

Nosotros buscando una solución sencilla, pensamos en estas cosas:

1- Que a la hora de crear una actividad nueva, en el apartado de Ubicación, hayan dos botones que serían: **Fisica** y **Virtual**.

2- Cuando una actividad sea física que ahí sí se tenga que poner obligatoriamente Provincia y Localidad.

3- Cuando la actividad sea virtual que solo se tenga que poner el link de donde se llevaría a cabo la actividad y que haya la opción de que este link pueda ser ocultado, para que así, la personas que se inscriban pero aún no hayan donando, no lo puedan ver hasta después de hacer el pago.

**Describí alternativas que hayas considerado**

La alternativa que usamos actualmente es dejar el link de Zoom y enviar la contraseña de la sala individualmente a cada persona inscrita.

**Contexto adicional**

Aqui les muestro:

En la primera imagen, donde se deberían colocar los botones o pestañas nuevas

En la segunda imagen, como se ve (desde el punto de vista de un usuario normal) el link de la actividad junto con provincia y localidad, cosa que no debería ser (aparte que se ve superpuesto por error)

![imagen](https://user-images.githubusercontent.com/66749262/84318506-8f5f5b00-ab3c-11ea-977b-91ef70ea3eff.png)

![imagen](https://user-images.githubusercontent.com/66749262/84318589-abfb9300-ab3c-11ea-9896-99f75e072716.png)

Sin más y atento a cualquier cosa, feliz día.

Daniel Fermín
_Coordinador de Comunidades para Techo Venezuela_
_Coordinador del Sistema de Actividades para Techo Venezuela_

**Comment by agustempo** [comment]
Me gusta mucho esta propuesta que haces para el sistema.

El sistema se pensó en primera instancia para eventos en territorio (los que teníamos antes) y con todo este tema fue necesario adaptarlo al contexto, yo lo hice para que sirviera.

Pero voy a analizar lo que me decís y ver la viabilidad de hacerlo mas especifico en casos que sea virtual.

**Comment by Danielfermin31** [comment]
Hola Agus, si justamente es lo que nosotros hablamos en sú momento, que el sistema para actividades en territorio está 10/10 pero que con este tema de la cuarentena nos toco buscarle la vuelta a todo y entre eso esta las actividades que se suben al sistema por ahora.

Espero si le vean la utilidad necesaria a lo que planteo y estoy a la orden para responder cualquier duda o cuestion. Saludos

**Comment by agustempo** [comment]
Hola Daniel, ahi estuve mejorando la interfaz, ahora al momento de elegir categoria "Virtual" queda:

![image](https://user-images.githubusercontent.com/11001346/85615605-ebdd7280-b632-11ea-8d82-cffe2881197c.png)


y en caso de cualquier otra Categoria:

![image](https://user-images.githubusercontent.com/11001346/85615878-4f67a000-b633-11ea-8392-af4f202c281b.png)


espero puedas probarlo para darme el ok y cerrar el ticket!
abrazo

**Comment by Danielfermin31** [comment]
Hola Agus, probada y verificada la adaptación, funciona como se espera y quedó como teniamos en mente. 
Muchisimas gracias.

Cualquier otra cosa abriré el respectivo ticket para comentartelo y poder seguir mejorando el sistema, quedo a la orden.

Saludos.
