### ISSUE TITLE
Correo de confirmación pre-inscripción con pago actividad virtual no coincide con el tipo de actividad

### ISSUE THREAD

**Issue by laurapaolapina** [techo/voluntariado-eventual#585]
**Describí el error**
Una vez que la persona se inscribe cuando la actividad es con pago, llega un correo de confirmación con instrucciones como si la actividad se desenvolverá en territorio. 
"_Te recordamos que el monto mínimo sugerido para abonar es de 1 , los cuales cubren los gastos de traslado, seguro y comida durante la construcción._"

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Inscribirse en actividad
2. Abrir la bandeja de entrada del usuario que se inscribió
3. Clickear en el e-mail de la actividad
4. Ver el error

**Comportamiento esperando**
Que el e-mail que llegue al correo tenga la siguiente información:
"_Te recordamos que el monto mínimo sugerido para abonar es de 1 , lo cual representa una donación que contribuye a desarrollar nuestro trabajo en comunidad._" 

**Capturas de pantalla**
Si aplica, agregá capturas de pantalla para explicar el problema
![image](https://user-images.githubusercontent.com/64121113/84322254-ab65fb00-ab42-11ea-85ac-17d70d0f9a08.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador Chrome

**Comment by agustempo** [comment]
Esto ya quedo modificado en producción, confirmame si podes probarlo! Saludos

**Comment by laurapaolapina** [comment]
Siii Agus, listo. Gracias!
