### ISSUE TITLE
Correo de confirmación pre - inscripción tiene link de donación que redirecciona a la página

### ISSUE THREAD

**Issue by laurapaolapina** [techo/voluntariado-eventual#586]
**Describí el error**
El correo de confirmación pre- inscripción " Para confirmar tu participación, haz click en el botón Confirmar con tu donación desde Aqui " en el botón "aquí" redirecciona  a la página en el sistema de actividad y no al formulario. 
**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Pre inscribirse en la actividad "El viaje del héroe creativo"
2. Revisar la bandeja de entrada del usuario que se inscribió. 
3. Clickear en el e-mail de confirmación pre-inscripción
4. En el cuerpo del texto seleccionar el botón "Confirmar con tu donación desde Aqui"
5. Ver el error

**Comportamiento esperando**
Esperaba que al hacer click en "Confirmar con tu donación desde Aqui" me redireccionara al formulario. 

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: Chrome

**Comment by agustempo** [comment]
Esto ya quedo modificado en producción, confirmame si podes probarlo! Saludos

**Comment by laurapaolapina** [comment]
Sí, gracias!
