### ISSUE TITLE
Carta de voluntarios

### ISSUE THREAD

**Issue by h30sosa** [techo/voluntariado-eventual#590]
Hola
Debido a la reapertura de algunas oficinas, desde la dirección regional solicita reemplazar la carta de aceptación al voluntariado en el SIV, con la declaración de que no se tuvo síntomas y/o que no se viajó a lugar con circulación comunitaria.

Ésta es la carta. Aplica para todas las actividades de la plataforma.

https://docs.google.com/document/d/1tjeD4iILAr0QKIbjRjI7jrI41zWAExjSY76kAfjHicU/edit?usp=sharing

**Comment by agustempo** [comment]
Hernan, para compartir ese documento se necesitan permisos, la misma esta para acceso publico?

**Comment by agustempo** [comment]
Esto ya quedo modificado en producción, confirmame si podes probarlo! Saludos
